Red [
	Title:   "Generates run-all-comp1.red run-all-comp2.red run-all-interp.red"
	Author:  "Peter W A Wood"
	Version: 0.1.0
	Tabs:	 4
	Rights:  "Copyright (C) 2015 Peter W A Wood. All rights reserved."
	License: "BSD-3 - https://github.com/red/red/blob/origin/BSD-3-License.txt"
	Purpose: {
		Red port of the Rebol make-run-all-red.r. Instead of compiling all
		65 units into 65 binaries, quick-test drives three batch drivers:
		the compiled list is split over comp1 and comp2, and the units that
		also run interpreted are inlined into interp. Run it from this
		directory: the drivers land in %auto-tests/ and the stripped copies
		of the units in %auto-tests/run-all/auto-tests/.
	}
]

;--------------- initialisations

make-dir/deep %auto-tests/run-all/auto-tests

;-- make the file lists from all-tests.txt
file-list-comp:	  copy []
file-list-interp: copy []
all-tests: read/lines %all-tests.txt

foreach test all-tests [
	;-- %auto-tests/lexer-auto-test.red has no generator left in this tree,
	;   so a missing entry is reported rather than fatal.
	either exists? to file! test [
		append file-list-comp copy test
		unless any [find test "routine" find test "evaluation"][
			append file-list-interp test
		]
	][
		print ["skipping missing unit:" test]
	]
]

;--------------- functions

;-- Drop a UTF-8 BOM: two of the units start with one, and a BOM in the
;   middle of the generated driver would not be a word.
strip-bom: func [line [string!]][
	if all [not empty? line #"^(FEFF)" = first line][remove line]
	line
]

;-- Copy a unit under %auto-tests/run-all/ without the parts that only make
;   sense when it stands alone, and return the path to #include.
move-file: func [
	file [string!]
	return: [string!]
	/local new-file new-src src line
][
	new-file: rejoin [%auto-tests/run-all/ second split-path to file! file]
	src: read/lines to file! file
	new-src: copy []
	foreach line src [
		strip-bom line
		replace line "~~~end-file~~~" ""
		unless any [
			find line "quick-test.red"
			find line "start-file~~~"
		][
			append new-src line
		]
	]
	write/lines new-file new-src
	replace to string! new-file "auto-tests/" ""
]

write-test-header: func [file-out [file!]][
	write/lines file-out [
		"Red ["
		{	Title:   "Red auto-generated test"}
		{	Author:  "Peter W A Wood"}
		{	License: "BSD-3 - https://github.com/red/red/blob/origin/BSD-3-License.txt"}
		{	Needs:	 [CSV JSON]}
		"]"
		""
		"comment ["
		"	This file is generated by make-run-all.red"
		"	Do not edit this file directly."
		"]"
		""
		"#include %../../../../quick-test/quick-test.red"
		""
	]
]

;--------------- Main Processing

file-out: %auto-tests/run-all-comp1.red
write-test-header file-out
write/append file-out {~~~start-file~~~ "run-all-comp1"^/}
i: 0
foreach file file-list-comp [
	i: i + 1
	if odd? i [write/append file-out rejoin ["#include %" move-file file lf]]
]
write/append file-out {~~~end-file~~~^/}

file-out: %auto-tests/run-all-comp2.red
write-test-header file-out
write/append file-out {~~~start-file~~~ "run-all-comp2"^/}
i: 0
foreach file file-list-comp [
	i: i + 1
	if even? i [write/append file-out rejoin ["#include %" move-file file lf]]
]
write/append file-out {~~~end-file~~~^/}

file-out: %auto-tests/run-all-interp.red
write-test-header file-out
write/append file-out {~~~start-file~~~ "run-all-interp"^/ do [^/}
foreach file file-list-interp [
	src: read/lines to file! file
	until [								;; ignore header
		src: next src
		any [tail? src find first src "~~~start"]
	]
	foreach line src [
		unless any [
			find line "quick-test.red"
			find line "start-file~~~"
			find line "end-file~~~"
		][
			replace line {"Infix operators creation"}
				{"Infix operators creation"^/ #do [interpreted?: true]^/}
			write/append file-out rejoin [line lf]
		]
	]
]
write/append file-out { ]^/~~~end-file~~~^/^/}

print ["generated:" i "units split over run-all-comp1/comp2," length? file-list-interp "inlined into run-all-interp"]
