Red [
	Title: "Generate Red/System string-table semantic fixture tests"
]

generating-wire-string-table-fixtures?: true
do %tests/wire-string-table-test.red

word-name: func [value [word!]][lowercase copy form value]

append-binary: func [output [string!] prefix [string!] name [word!] data [binary!]][
	append output rejoin [prefix word-name name ": " mold/flat data newline]
]

output: make string! 131072
source-bytes: make binary! 65536
append source-bytes read %tests/wire-string-table-test.red
append source-bytes read %tests/wire-container-test.red
append source-bytes read %generate-wire-string-table-fixtures.red
append source-bytes to binary! mold schema/WIRE_SCHEMA_FINGERPRINT
source-digest: enbase/base checksum source-bytes 'SHA256 16

append output {Red/System [
	Title: "Generated string-table cross-language tests"
]

; Generated by tools/self_hosting/generate-wire-string-table-fixtures.red.
; Do not edit. Error codes and locations are frozen by the Red semantic corpus.
}
append output rejoin ["; Fixture source SHA256: " source-digest newline]
append output {
#include %../../../system/codegen/wire-string-table.reds

}

foreach fixture valid-string-tables [
	append-binary output "string-valid-" fixture/1 fixture/3
]
foreach fixture malformed-string-tables [
	append-binary output "string-invalid-" fixture/1 fixture/7
]

append output {
poison-table: func [table [wire-string-table!]][
	table/records: as byte-ptr! 101
	table/record-count: -102
	table/record-size: -103
	table/records-offset: -104
	table/records-ordinal: -105
	table/data: as byte-ptr! 106
	table/data-size: -107
	table/data-offset: -108
	table/data-ordinal: -109
]

table-poisoned?: func [table [wire-string-table!] return: [logic!]][
	all [
		table/records = (as byte-ptr! 101)
		table/record-count = -102
		table/record-size = -103
		table/records-offset = -104
		table/records-ordinal = -105
		table/data = (as byte-ptr! 106)
		table/data-size = -107
		table/data-offset = -108
		table/data-ordinal = -109
	]
]

poison-slice: func [slice [wire-string-slice!]][
	slice/data: as byte-ptr! 201
	slice/size: -202
]

slice-poisoned?: func [slice [wire-string-slice!] return: [logic!]][
	all [slice/data = (as byte-ptr! 201) slice/size = -202]
]

test-string-table: func [
	name [c-string!]
	data [byte-ptr!]
	size magic expected-error expected-container expected-offset expected-section [integer!]
	return: [integer!]
	/local result [wire-string-table-result!] table [wire-string-table!] actual [integer!]
][
	result: declare wire-string-table-result!
	table: declare wire-string-table!
	poison-table table
	actual: wire-string-table-reader/verify data size magic result table
	if actual <> expected-error [
		print ["FAIL: " name " expected=" expected-error " actual=" actual lf]
		return 1
	]
	if result/error <> expected-error [
		print ["FAIL: " name " result/error=" result/error lf]
		return 1
	]
	if result/container-error <> expected-container [
		print [
			"FAIL: " name " container=" result/container-error
			" expected=" expected-container lf
		]
		return 1
	]
	if any [
		result/error-offset <> expected-offset
		result/error-section <> expected-section
	][
		print [
			"FAIL: " name
			" location=" result/error-offset ":" result/error-section
			" expected=" expected-offset ":" expected-section lf
		]
		return 1
	]
	if all [
		expected-error <> WIRE_STRING_TABLE_ERROR_SUCCESS
		not table-poisoned? table
	][
		print ["FAIL: " name " modified table on failure" lf]
		return 1
	]
	0
]

failures: 0
}

foreach fixture valid-string-tables [
	append output rejoin [
		{failures: failures + (test-string-table "} form fixture/1 {" }
		"string-valid-" word-name fixture/1 " " length? fixture/3 " " fixture/2 " "
		schema/WIRE_STRING_TABLE_ERROR_SUCCESS " "
		schema/WIRE_CONTAINER_ERROR_SUCCESS " 0 0)" newline
	]
]

foreach fixture malformed-string-tables [
	append output rejoin [
		{failures: failures + (test-string-table "} form fixture/1 {" }
		"string-invalid-" word-name fixture/1 " " length? fixture/7 " " fixture/2 " "
		fixture/3 " " fixture/4 " " fixture/5 " " fixture/6 ")" newline
	]
]

rsir-view: string-verifier/verify nonempty-rsir schema/WIRE_MAGIC_RSIR
utf8-view: string-verifier/verify utf8-boundaries schema/WIRE_MAGIC_RSIR

append output rejoin [{
result: declare wire-string-table-result!
table: declare wire-string-table!
slice: declare wire-string-slice!
code: wire-string-table-reader/verify
	string-valid-rsir } length? nonempty-rsir { WIRE_MAGIC_RSIR result table
if code <> WIRE_STRING_TABLE_ERROR_SUCCESS [failures: failures + 1]
if any [
	table/record-count <> 1
	table/record-size <> WIRE_STRING_SIZE
	table/records-offset <> } rsir-view/table/records-offset {
	table/records-ordinal <> } rsir-view/table/records-ordinal {
	table/data-size <> 5
	table/data-offset <> } rsir-view/table/data-offset {
	table/data-ordinal <> } rsir-view/table/data-ordinal {
][
	print ["FAIL: verified RSIR string-table view changed" lf]
	failures: failures + 1
]

poison-slice slice
unless wire-string-table-reader/get-slice table 1 slice [
	print ["FAIL: could not resolve valid string ID" lf]
	failures: failures + 1
]
if any [
	slice/size <> 5
	slice/data/1 <> as byte! 101
	slice/data/5 <> as byte! 121
][failures: failures + 1]

poison-slice slice
if wire-string-table-reader/get-slice table 0 slice [failures: failures + 1]
unless slice-poisoned? slice [failures: failures + 1]
if wire-string-table-reader/get-slice table 2 slice [failures: failures + 1]
unless slice-poisoned? slice [failures: failures + 1]

code: wire-string-table-reader/verify
	string-valid-utf8-boundaries } length? utf8-boundaries {
	WIRE_MAGIC_RSIR result table
if code <> WIRE_STRING_TABLE_ERROR_SUCCESS [failures: failures + 1]
poison-slice slice
unless wire-string-table-reader/get-slice table 1 slice [failures: failures + 1]
if any [not null? slice/data slice/size <> 0][failures: failures + 1]

poison-table table
code: wire-string-table-reader/verify
	(as byte-ptr! 0) } length? nonempty-rsir { WIRE_MAGIC_RSIR result table
if code <> WIRE_STRING_TABLE_ERROR_INVALID_ARGUMENTS [failures: failures + 1]
if any [
	result/error <> WIRE_STRING_TABLE_ERROR_INVALID_ARGUMENTS
	result/container-error <> WIRE_CONTAINER_ERROR_SUCCESS
	result/error-offset <> 0
	result/error-section <> 0
][failures: failures + 1]
unless table-poisoned? table [failures: failures + 1]

code: wire-string-table-reader/verify
	string-valid-rsir -1 WIRE_MAGIC_RSIR result table
if code <> WIRE_STRING_TABLE_ERROR_INVALID_ARGUMENTS [failures: failures + 1]
unless table-poisoned? table [failures: failures + 1]

code: wire-string-table-reader/verify
	string-valid-rsir } length? nonempty-rsir { WIRE_MAGIC_RSIR result (as wire-string-table! 0)
if code <> WIRE_STRING_TABLE_ERROR_INVALID_ARGUMENTS [failures: failures + 1]

code: wire-string-table-reader/verify
	string-valid-rsir } length? nonempty-rsir { WIRE_MAGIC_RSIR
	(as wire-string-table-result! 0) table
if code <> WIRE_STRING_TABLE_ERROR_INVALID_ARGUMENTS [failures: failures + 1]

poison-table table
code: wire-string-table-reader/verify
	string-valid-rsir } length? nonempty-rsir { WIRE_MAGIC_RSCF result table
if code <> WIRE_STRING_TABLE_ERROR_UNSUPPORTED_MESSAGE [failures: failures + 1]
if any [
	result/container-error <> WIRE_CONTAINER_ERROR_SUCCESS
	result/error-offset <> 0
	result/error-section <> 0
][failures: failures + 1]
unless table-poisoned? table [failures: failures + 1]

either failures = 0 [
	print ["PASS: Red/System string-table semantics" lf]
][
	print ["FAIL: Red/System string-table semantics failures=" failures lf]
]
quit failures
}]

target: %tests/wire-string-table-reds-test.reds
write target to binary! output
print [
	"Generated" target
	"with" length? valid-string-tables "valid and"
	length? malformed-string-tables "malformed fixtures"
]
