Red [
	Title: "Generate Red/System module lifecycle fixture tests"
]

generating-wire-module-lifecycle-fixtures?: true
do %tests/wire-module-lifecycle-test.red

word-name: func [value [word!]][lowercase copy form value]

append-binary: func [output [string!] prefix [string!] name [word!] data [binary!]][
	append output rejoin [prefix word-name name ": " mold/flat data newline]
]

output: make string! 262144
source-bytes: make binary! 262144
append source-bytes read %tests/wire-module-lifecycle-test.red
append source-bytes read %tests/wire-file-source-test.red
append source-bytes read %tests/wire-string-table-test.red
append source-bytes read %tests/wire-container-test.red
append source-bytes read %generate-wire-module-lifecycle-fixtures.red
append source-bytes to binary! mold schema/WIRE_SCHEMA_FINGERPRINT
source-digest: enbase/base checksum source-bytes 'SHA256 16

append output {Red/System [
	Title: "Generated module lifecycle cross-language tests"
]

; Generated by tools/self_hosting/generate-wire-module-lifecycle-fixtures.red.
; Do not edit. Error codes and locations are frozen by the Red semantic corpus.
}
append output rejoin ["; Fixture source SHA256: " source-digest newline]
append output {
#include %../../../system/codegen/wire-module-lifecycle.reds

}

foreach fixture valid-module-lifecycles [
	append-binary output "module-valid-" fixture/1 fixture/3
]
foreach fixture malformed-module-lifecycles [
	append-binary output "module-invalid-" fixture/1 fixture/9
]

append output {
poison-strings: func [strings [wire-string-table!]][
	strings/records: as byte-ptr! 101
	strings/record-count: -102
	strings/record-size: -103
	strings/records-offset: -104
	strings/records-ordinal: -105
	strings/data: as byte-ptr! 106
	strings/data-size: -107
	strings/data-offset: -108
	strings/data-ordinal: -109
]

strings-poisoned?: func [strings [wire-string-table!] return: [logic!]][
	all [
		strings/records = (as byte-ptr! 101)
		strings/record-count = -102
		strings/record-size = -103
		strings/records-offset = -104
		strings/records-ordinal = -105
		strings/data = (as byte-ptr! 106)
		strings/data-size = -107
		strings/data-offset = -108
		strings/data-ordinal = -109
	]
]

poison-files: func [files [wire-file-source!]][
	files/files: as byte-ptr! 201
	files/file-count: -202
	files/file-record-size: -203
	files/files-offset: -204
	files/files-ordinal: -205
	files/checksum-data: as byte-ptr! 206
	files/checksum-data-size: -207
	files/checksum-data-offset: -208
	files/checksum-data-ordinal: -209
	files/source-present: -210
	files/sources: as byte-ptr! 211
	files/source-count: -212
	files/source-record-size: -213
	files/source-offset: -214
	files/source-ordinal: -215
]

files-poisoned?: func [files [wire-file-source!] return: [logic!]][
	all [
		files/files = (as byte-ptr! 201)
		files/file-count = -202
		files/file-record-size = -203
		files/files-offset = -204
		files/files-ordinal = -205
		files/checksum-data = (as byte-ptr! 206)
		files/checksum-data-size = -207
		files/checksum-data-offset = -208
		files/checksum-data-ordinal = -209
		files/source-present = -210
		files/sources = (as byte-ptr! 211)
		files/source-count = -212
		files/source-record-size = -213
		files/source-offset = -214
		files/source-ordinal = -215
	]
]

poison-view: func [view [wire-module-lifecycle!]][
	view/modules: as byte-ptr! 301
	view/module-count: -302
	view/module-record-size: -303
	view/modules-offset: -304
	view/modules-ordinal: -305
	view/reference-count: -306
	view/image-kind: -307
	view/glue-module: -308
]

view-poisoned?: func [view [wire-module-lifecycle!] return: [logic!]][
	all [
		view/modules = (as byte-ptr! 301)
		view/module-count = -302
		view/module-record-size = -303
		view/modules-offset = -304
		view/modules-ordinal = -305
		view/reference-count = -306
		view/image-kind = -307
		view/glue-module = -308
	]
]

test-module: func [
	name [c-string!]
	data [byte-ptr!]
	size magic expected-error expected-container expected-string expected-file
	expected-offset expected-section [integer!]
	return: [integer!]
	/local result [wire-module-lifecycle-result!]
		strings [wire-string-table!]
		files [wire-file-source!]
		view [wire-module-lifecycle!]
		actual [integer!]
][
	result: declare wire-module-lifecycle-result!
	strings: declare wire-string-table!
	files: declare wire-file-source!
	view: declare wire-module-lifecycle!
	poison-strings strings
	poison-files files
	poison-view view
	actual: wire-module-lifecycle-reader/verify
		data size magic result strings files view
	if actual <> expected-error [
		print ["FAIL: " name " expected=" expected-error " actual=" actual lf]
		return 1
	]
	if result/error <> expected-error [
		print ["FAIL: " name " result/error=" result/error lf]
		return 1
	]
	if result/container-error <> expected-container [
		print [
			"FAIL: " name " container=" result/container-error
			" expected=" expected-container lf
		]
		return 1
	]
	if result/string-error <> expected-string [
		print [
			"FAIL: " name " string=" result/string-error
			" expected=" expected-string lf
		]
		return 1
	]
	if result/file-source-error <> expected-file [
		print [
			"FAIL: " name " file=" result/file-source-error
			" expected=" expected-file lf
		]
		return 1
	]
	if any [
		result/error-offset <> expected-offset
		result/error-section <> expected-section
	][
		print [
			"FAIL: " name
			" location=" result/error-offset ":" result/error-section
			" expected=" expected-offset ":" expected-section lf
		]
		return 1
	]
	if all [
		expected-error <> WIRE_MODULE_LIFECYCLE_ERROR_SUCCESS
		any [
			not strings-poisoned? strings
			not files-poisoned? files
			not view-poisoned? view
		]
	][
		print ["FAIL: " name " modified output views on failure" lf]
		return 1
	]
	0
]

failures: 0
}

foreach fixture valid-module-lifecycles [
	append output rejoin [
		{failures: failures + (test-module "} form fixture/1 {" }
		"module-valid-" word-name fixture/1 " " length? fixture/3 " " fixture/2 " "
		schema/WIRE_MODULE_LIFECYCLE_ERROR_SUCCESS " "
		schema/WIRE_CONTAINER_ERROR_SUCCESS " "
		schema/WIRE_STRING_TABLE_ERROR_SUCCESS " "
		schema/WIRE_FILE_SOURCE_ERROR_SUCCESS " 0 0)" newline
	]
]

foreach fixture malformed-module-lifecycles [
	append output rejoin [
		{failures: failures + (test-module "} form fixture/1 {" }
		"module-invalid-" word-name fixture/1 " " length? fixture/9 " " fixture/2 " "
		fixture/3 " " fixture/4 " " fixture/5 " " fixture/6 " "
		fixture/7 " " fixture/8 ")" newline
	]
]

rscg-merged-result: module-verifier/verify rscg-merged schema/WIRE_MAGIC_RSCG

append output rejoin [{
result: declare wire-module-lifecycle-result!
strings: declare wire-string-table!
files: declare wire-file-source!
view: declare wire-module-lifecycle!
code: wire-module-lifecycle-reader/verify
	module-valid-rscg-merged } length? rscg-merged {
	WIRE_MAGIC_RSCG result strings files view
if code <> WIRE_MODULE_LIFECYCLE_ERROR_SUCCESS [failures: failures + 1]
if any [
	view/module-count <> 3
	view/module-record-size <> WIRE_RSCG_MODULE_SIZE
	view/modules-offset <> } rscg-merged-result/view/modules-offset {
	view/modules-ordinal <> } rscg-merged-result/view/modules-ordinal {
	view/reference-count <> 4
	view/image-kind <> WIRE_IMAGE_KIND_EXECUTABLE
	view/glue-module <> 3
][
	print ["FAIL: verified merged RSCG module view changed" lf]
	failures: failures + 1
]
if any [
	strings/record-count <> 4
	files/file-count <> 0
	(wire-container-reader/read-i31 view/modules WIRE_RSCG_MODULE_KIND_OFFSET)
		<> WIRE_MODULE_KIND_RUNTIME
][failures: failures + 1]

poison-strings strings
poison-files files
poison-view view
code: wire-module-lifecycle-reader/verify
	(as byte-ptr! 0) } length? rsir-user {
	WIRE_MAGIC_RSIR result strings files view
if code <> WIRE_MODULE_LIFECYCLE_ERROR_INVALID_ARGUMENTS [failures: failures + 1]
unless strings-poisoned? strings [failures: failures + 1]
unless files-poisoned? files [failures: failures + 1]
unless view-poisoned? view [failures: failures + 1]

code: wire-module-lifecycle-reader/verify
	module-valid-rsir-user -1 WIRE_MAGIC_RSIR result strings files view
if code <> WIRE_MODULE_LIFECYCLE_ERROR_INVALID_ARGUMENTS [failures: failures + 1]
unless strings-poisoned? strings [failures: failures + 1]
unless files-poisoned? files [failures: failures + 1]
unless view-poisoned? view [failures: failures + 1]

code: wire-module-lifecycle-reader/verify
	module-valid-rsir-user } length? rsir-user {
	WIRE_MAGIC_RSIR result (as wire-string-table! 0) files view
if code <> WIRE_MODULE_LIFECYCLE_ERROR_INVALID_ARGUMENTS [failures: failures + 1]

code: wire-module-lifecycle-reader/verify
	module-valid-rsir-user } length? rsir-user {
	WIRE_MAGIC_RSIR result strings (as wire-file-source! 0) view
if code <> WIRE_MODULE_LIFECYCLE_ERROR_INVALID_ARGUMENTS [failures: failures + 1]

code: wire-module-lifecycle-reader/verify
	module-valid-rsir-user } length? rsir-user {
	WIRE_MAGIC_RSIR result strings files (as wire-module-lifecycle! 0)
if code <> WIRE_MODULE_LIFECYCLE_ERROR_INVALID_ARGUMENTS [failures: failures + 1]

code: wire-module-lifecycle-reader/verify
	module-valid-rsir-user } length? rsir-user {
	WIRE_MAGIC_RSIR (as wire-module-lifecycle-result! 0) strings files view
if code <> WIRE_MODULE_LIFECYCLE_ERROR_INVALID_ARGUMENTS [failures: failures + 1]

either failures = 0 [
	print ["PASS: Red/System module lifecycle semantics" lf]
][
	print ["FAIL: Red/System module lifecycle semantics failures=" failures lf]
]
quit failures
}]

target: %tests/wire-module-lifecycle-reds-test.reds
write target to binary! output
print [
	"Generated" target
	"with" length? valid-module-lifecycles "valid and"
	length? malformed-module-lifecycles "malformed fixtures"
]
