Red [
	Title: "Generate Red/System RSIR atomic operation fixture tests"
]

generating-wire-atomic-fixtures?: true
do %tests/wire-atomic-test.red

word-name: func [value [word!]][lowercase copy form value]

append-binary: func [output [string!] prefix [string!] name [word!] data [binary!]][
	append output rejoin [prefix word-name name ": " mold/flat data newline]
]

output: make string! 12'582'912
source-bytes: make binary! 4'194'304
foreach source-file [
	%tests/wire-atomic-test.red
	%tests/wire-scalar-operation-test.red
	%tests/wire-constant-initializer-test.red
	%tests/wire-symbol-linkage-test.red
	%tests/wire-function-signature-test.red
	%tests/wire-module-lifecycle-test.red
	%tests/wire-type-layout-test.red
	%tests/wire-data-layout-test.red
	%tests/wire-file-source-test.red
	%tests/wire-string-table-test.red
	%tests/wire-container-test.red
	%generate-wire-atomic-fixtures.red
][append source-bytes read source-file]
append source-bytes to binary! mold schema/WIRE_SCHEMA_FINGERPRINT
source-digest: enbase/base checksum source-bytes 'SHA256 16

append output {Red/System [
	Title: "Generated RSIR atomic operation cross-language tests"
]

; Generated by tools/self_hosting/generate-wire-atomic-fixtures.red.
; Do not edit. Error codes and locations are frozen by the Red semantic corpus.
}
append output rejoin ["; Fixture source SHA256: " source-digest newline]
append output {
#include %../../../system/codegen/wire-atomic.reds

}

foreach fixture valid-atomics [
	append-binary output "atomic-valid-" fixture/1 fixture/2
]
foreach fixture malformed-atomics [
	append-binary output "atomic-invalid-" fixture/1 fixture/15
]

append output {
poison-memory: func [
	memory [byte-ptr!]
	size [integer!]
	/local cursor [byte-ptr!] remaining [integer!]
][
	cursor: memory
	remaining: size
	while [remaining > 0][
		cursor/1: as byte! 165
		cursor: cursor + 1
		remaining: remaining - 1
	]
]

memory-poisoned?: func [
	memory [byte-ptr!]
	size [integer!]
	return: [logic!]
	/local cursor [byte-ptr!] remaining [integer!]
][
	cursor: memory
	remaining: size
	while [remaining > 0][
		if cursor/1 <> as byte! 165 [return false]
		cursor: cursor + 1
		remaining: remaining - 1
	]
	true
]

poison-outputs: func [
	strings [wire-string-table!]
	files [wire-file-source!]
	layout [wire-data-layout!]
	types [wire-type-layout!]
	functions [wire-function-signature!]
	modules [wire-module-lifecycle!]
	symbols [wire-symbol-linkage!]
	constants [wire-constant-initializer!]
	view [wire-scalar-operation!]
][
	poison-memory as byte-ptr! strings size? wire-string-table!
	poison-memory as byte-ptr! files size? wire-file-source!
	poison-memory as byte-ptr! layout size? wire-data-layout!
	poison-memory as byte-ptr! types size? wire-type-layout!
	poison-memory as byte-ptr! functions size? wire-function-signature!
	poison-memory as byte-ptr! modules size? wire-module-lifecycle!
	poison-memory as byte-ptr! symbols size? wire-symbol-linkage!
	poison-memory as byte-ptr! constants size? wire-constant-initializer!
	poison-memory as byte-ptr! view size? wire-scalar-operation!
]

outputs-poisoned?: func [
	strings [wire-string-table!]
	files [wire-file-source!]
	layout [wire-data-layout!]
	types [wire-type-layout!]
	functions [wire-function-signature!]
	modules [wire-module-lifecycle!]
	symbols [wire-symbol-linkage!]
	constants [wire-constant-initializer!]
	view [wire-scalar-operation!]
	return: [logic!]
][
	all [
		memory-poisoned? as byte-ptr! strings size? wire-string-table!
		memory-poisoned? as byte-ptr! files size? wire-file-source!
		memory-poisoned? as byte-ptr! layout size? wire-data-layout!
		memory-poisoned? as byte-ptr! types size? wire-type-layout!
		memory-poisoned? as byte-ptr! functions size? wire-function-signature!
		memory-poisoned? as byte-ptr! modules size? wire-module-lifecycle!
		memory-poisoned? as byte-ptr! symbols size? wire-symbol-linkage!
		memory-poisoned? as byte-ptr! constants size? wire-constant-initializer!
		memory-poisoned? as byte-ptr! view size? wire-scalar-operation!
	]
]

test-atomic: func [
	name [c-string!]
	data [byte-ptr!]
	size expected-error expected-scalar expected-container expected-string
	expected-file expected-layout expected-type expected-function expected-module
	expected-symbol expected-constant expected-offset expected-section [integer!]
	return: [integer!]
	/local result [wire-atomic-result!]
		strings [wire-string-table!]
		files [wire-file-source!]
		layout [wire-data-layout!]
		types [wire-type-layout!]
		functions [wire-function-signature!]
		modules [wire-module-lifecycle!]
		symbols [wire-symbol-linkage!]
		constants [wire-constant-initializer!]
		view [wire-scalar-operation!]
		actual [integer!]
][
	result: declare wire-atomic-result!
	strings: declare wire-string-table!
	files: declare wire-file-source!
	layout: declare wire-data-layout!
	types: declare wire-type-layout!
	functions: declare wire-function-signature!
	modules: declare wire-module-lifecycle!
	symbols: declare wire-symbol-linkage!
	constants: declare wire-constant-initializer!
	view: declare wire-scalar-operation!
	poison-outputs strings files layout types functions modules symbols constants view
	actual: wire-atomic-reader/verify data size result
		strings files layout types functions modules symbols constants view
	if actual <> expected-error [
		print ["FAIL: " name " expected=" expected-error " actual=" actual lf]
		return 1
	]
	if result/error <> expected-error [
		print ["FAIL: " name " result/error=" result/error lf]
		return 1
	]
	if result/scalar-operation-error <> expected-scalar [
		print ["FAIL: " name " scalar=" result/scalar-operation-error lf]
		return 1
	]
	if result/container-error <> expected-container [return 1]
	if result/string-error <> expected-string [return 1]
	if result/file-source-error <> expected-file [return 1]
	if result/data-layout-error <> expected-layout [return 1]
	if result/type-layout-error <> expected-type [return 1]
	if result/function-signature-error <> expected-function [return 1]
	if result/module-lifecycle-error <> expected-module [return 1]
	if result/symbol-linkage-error <> expected-symbol [return 1]
	if result/constant-initializer-error <> expected-constant [return 1]
	if any [
		result/error-offset <> expected-offset
		result/error-section <> expected-section
	][
		print [
			"FAIL: " name " location=" result/error-offset ":" result/error-section
			" expected=" expected-offset ":" expected-section lf
		]
		return 1
	]
	if all [
		expected-error <> WIRE_ATOMIC_ERROR_SUCCESS
		not outputs-poisoned? strings files layout types functions modules symbols
			constants view
	][
		print ["FAIL: " name " modified output views on failure" lf]
		return 1
	]
	0
]

failures: 0
}

foreach fixture valid-atomics [
	name: fixture/1
	data: fixture/2
	append output rejoin [
		{failures: failures + (test-atomic "} form name {" }
		"atomic-valid-" word-name name " " length? data
		" " schema/WIRE_ATOMIC_ERROR_SUCCESS
		" " schema/WIRE_SCALAR_OPERATION_ERROR_SUCCESS
		" " schema/WIRE_CONTAINER_ERROR_SUCCESS
		" " schema/WIRE_STRING_TABLE_ERROR_SUCCESS
		" " schema/WIRE_FILE_SOURCE_ERROR_SUCCESS
		" " schema/WIRE_DATA_LAYOUT_ERROR_SUCCESS
		" " schema/WIRE_TYPE_LAYOUT_ERROR_SUCCESS
		" " schema/WIRE_FUNCTION_SIGNATURE_ERROR_SUCCESS
		" " schema/WIRE_MODULE_LIFECYCLE_ERROR_SUCCESS
		" " schema/WIRE_SYMBOL_LINKAGE_ERROR_SUCCESS
		" " schema/WIRE_CONSTANT_INITIALIZER_ERROR_SUCCESS
		" 0 0)" newline
	]
]

foreach fixture malformed-atomics [
	append output rejoin [
		{failures: failures + (test-atomic "} form fixture/1 {" }
		"atomic-invalid-" word-name fixture/1 " " length? fixture/15
		" " fixture/2 " " fixture/3 " " fixture/4 " " fixture/5
		" " fixture/6 " " fixture/7 " " fixture/8 " " fixture/9
		" " fixture/10 " " fixture/11 " " fixture/12 " " fixture/13
		" " fixture/14 ")" newline
	]
]

verified: atomic-verifier/verify rich-atomic-message
append output rejoin [{

result: declare wire-atomic-result!
strings: declare wire-string-table!
files: declare wire-file-source!
layout: declare wire-data-layout!
types: declare wire-type-layout!
functions: declare wire-function-signature!
modules: declare wire-module-lifecycle!
symbols: declare wire-symbol-linkage!
constants: declare wire-constant-initializer!
view: declare wire-scalar-operation!
code: wire-atomic-reader/verify atomic-valid-rich } length? rich-atomic-message {
	result strings files layout types functions modules symbols constants view
if code <> WIRE_ATOMIC_ERROR_SUCCESS [failures: failures + 1]
if any [
	strings/record-count <> } verified/strings/record-count {
	files/file-count <> } verified/files/file-count {
	layout/pointer-size <> } verified/layout/pointer-size {
	types/type-count <> } verified/types/type-count {
	types/field-count <> } verified/types/field-count {
	functions/function-count <> } verified/functions/function-count {
	functions/local-count <> } verified/functions/local-count {
	modules/module-count <> } verified/modules/module-count {
	symbols/symbol-count <> } verified/symbols/symbol-count {
	symbols/global-count <> } verified/symbols/global-count {
	constants/constant-count <> } verified/constants/constant-count {
	view/value-count <> } verified/view/value-count {
	view/value-record-size <> WIRE_RSIR_VALUE_SIZE
	view/values-offset <> } verified/view/values-offset {
	view/values-ordinal <> } verified/view/values-ordinal {
	view/instruction-count <> } verified/view/instruction-count {
	view/instruction-record-size <> WIRE_RSIR_INSTRUCTION_SIZE
	view/instructions-offset <> } verified/view/instructions-offset {
	view/instructions-ordinal <> } verified/view/instructions-ordinal {
	view/operand-count <> } verified/view/operand-count {
	view/operand-record-size <> WIRE_RSIR_OPERAND_SIZE
	view/operands-offset <> } verified/view/operands-offset {
	view/operands-ordinal <> } verified/view/operands-ordinal {
	view/target-fragment-count <> } verified/view/target-fragment-count {
][
	print ["FAIL: verified atomic view changed" lf]
	failures: failures + 1
]

poison-outputs strings files layout types functions modules symbols constants view
code: wire-atomic-reader/verify (as byte-ptr! 0) } length? rich-atomic-message {
	result strings files layout types functions modules symbols constants view
if code <> WIRE_ATOMIC_ERROR_INVALID_ARGUMENTS [failures: failures + 1]
if any [
	result/error <> WIRE_ATOMIC_ERROR_INVALID_ARGUMENTS
	result/scalar-operation-error <> WIRE_SCALAR_OPERATION_ERROR_SUCCESS
	result/container-error <> WIRE_CONTAINER_ERROR_SUCCESS
	result/string-error <> WIRE_STRING_TABLE_ERROR_SUCCESS
	result/file-source-error <> WIRE_FILE_SOURCE_ERROR_SUCCESS
	result/data-layout-error <> WIRE_DATA_LAYOUT_ERROR_SUCCESS
	result/type-layout-error <> WIRE_TYPE_LAYOUT_ERROR_SUCCESS
	result/function-signature-error <> WIRE_FUNCTION_SIGNATURE_ERROR_SUCCESS
	result/module-lifecycle-error <> WIRE_MODULE_LIFECYCLE_ERROR_SUCCESS
	result/symbol-linkage-error <> WIRE_SYMBOL_LINKAGE_ERROR_SUCCESS
	result/constant-initializer-error <> WIRE_CONSTANT_INITIALIZER_ERROR_SUCCESS
	result/error-offset <> 0
	result/error-section <> 0
][failures: failures + 1]
unless outputs-poisoned? strings files layout types functions modules symbols constants view [
	failures: failures + 1
]

code: wire-atomic-reader/verify atomic-valid-rich -1 result
	strings files layout types functions modules symbols constants view
if code <> WIRE_ATOMIC_ERROR_INVALID_ARGUMENTS [failures: failures + 1]
unless outputs-poisoned? strings files layout types functions modules symbols constants view [
	failures: failures + 1
]
}]

foreach [type-name before after] [
	wire-string-table! "result " " files layout types functions modules symbols constants view"
	wire-file-source! "result strings " " layout types functions modules symbols constants view"
	wire-data-layout! "result strings files " " types functions modules symbols constants view"
	wire-type-layout! "result strings files layout " " functions modules symbols constants view"
	wire-function-signature! "result strings files layout types " " modules symbols constants view"
	wire-module-lifecycle! "result strings files layout types functions " " symbols constants view"
	wire-symbol-linkage! "result strings files layout types functions modules " " constants view"
	wire-constant-initializer! "result strings files layout types functions modules symbols " " view"
	wire-scalar-operation! "result strings files layout types functions modules symbols constants " ""
][
	append output rejoin [
		"code: wire-atomic-reader/verify atomic-valid-rich "
		length? rich-atomic-message newline tab before "(as " type-name " 0)" after newline
		"if code <> WIRE_ATOMIC_ERROR_INVALID_ARGUMENTS "
		"[failures: failures + 1]" newline
	]
]

append output rejoin [{
code: wire-atomic-reader/verify atomic-valid-rich } length? rich-atomic-message {
	(as wire-atomic-result! 0)
	strings files layout types functions modules symbols constants view
if code <> WIRE_ATOMIC_ERROR_INVALID_ARGUMENTS [failures: failures + 1]

either failures = 0 [
	print ["PASS: Red/System RSIR atomic semantics" lf]
][
	print ["FAIL: Red/System RSIR atomic semantics failures=" failures lf]
]
quit failures
}]

target: %tests/wire-atomic-reds-test.reds
write target to binary! output
print [
	"Generated" target "with" length? valid-atomics "valid and"
	length? malformed-atomics "malformed fixtures"
]
