Red [
	Title: "Generate Red/System RSIR subroutine fixture tests"
]

generating-wire-subroutine-fixtures?: true
do %tests/wire-subroutine-test.red

word-name: func [value [word!]][lowercase copy form value]

append-binary: func [output [string!] prefix [string!] name [word!] data [binary!]][
	append output rejoin [prefix word-name name ": " mold/flat data newline]
]

output: make string! 16'777'216
source-bytes: make binary! 8'388'608
foreach source-file [
	%tests/wire-subroutine-test.red
	%tests/wire-call-abi-test.red
	%tests/wire-control-flow-test.red
	%tests/wire-scalar-operation-test.red
	%tests/wire-constant-initializer-test.red
	%tests/wire-symbol-linkage-test.red
	%tests/wire-function-signature-test.red
	%tests/wire-module-lifecycle-test.red
	%tests/wire-type-layout-test.red
	%tests/wire-data-layout-test.red
	%tests/wire-file-source-test.red
	%tests/wire-string-table-test.red
	%tests/wire-container-test.red
	%generate-wire-subroutine-fixtures.red
][append source-bytes read source-file]
append source-bytes to binary! mold schema/WIRE_SCHEMA_FINGERPRINT
source-digest: enbase/base checksum source-bytes 'SHA256 16

append output {Red/System [
	Title: "Generated RSIR subroutine cross-language tests"
]

; Generated by tools/self_hosting/generate-wire-subroutine-fixtures.red.
; Do not edit. Error codes and locations are frozen by the Red semantic corpus.
}
append output rejoin ["; Fixture source SHA256: " source-digest newline]
append output {
#include %../../../system/codegen/wire-subroutine.reds

}

foreach fixture valid-subroutines [
	append-binary output "subroutine-valid-" fixture/1 fixture/2
]
foreach fixture malformed-subroutines [
	append-binary output "subroutine-invalid-" fixture/1 fixture/17
]

append output {
subroutine-workspace: #{
	00000000000000000000000000000000
	00000000000000000000000000000000
	00000000000000000000000000000000
	00000000000000000000000000000000
}
subroutine-small-workspace: #{00}

poison-memory: func [
	memory [byte-ptr!]
	size [integer!]
	/local cursor [byte-ptr!] remaining [integer!]
][
	cursor: memory
	remaining: size
	while [remaining > 0][
		cursor/1: as byte! 165
		cursor: cursor + 1
		remaining: remaining - 1
	]
]

memory-poisoned?: func [
	memory [byte-ptr!]
	size [integer!]
	return: [logic!]
	/local cursor [byte-ptr!] remaining [integer!]
][
	cursor: memory
	remaining: size
	while [remaining > 0][
		if cursor/1 <> as byte! 165 [return false]
		cursor: cursor + 1
		remaining: remaining - 1
	]
	true
]

poison-outputs: func [
	strings [wire-string-table!]
	files [wire-file-source!]
	layout [wire-data-layout!]
	types [wire-type-layout!]
	functions [wire-function-signature!]
	modules [wire-module-lifecycle!]
	symbols [wire-symbol-linkage!]
	constants [wire-constant-initializer!]
	scalar [wire-scalar-operation!]
	control [wire-control-flow!]
	calls [wire-call-abi!]
	subroutines [wire-subroutine!]
][
	poison-memory as byte-ptr! strings size? wire-string-table!
	poison-memory as byte-ptr! files size? wire-file-source!
	poison-memory as byte-ptr! layout size? wire-data-layout!
	poison-memory as byte-ptr! types size? wire-type-layout!
	poison-memory as byte-ptr! functions size? wire-function-signature!
	poison-memory as byte-ptr! modules size? wire-module-lifecycle!
	poison-memory as byte-ptr! symbols size? wire-symbol-linkage!
	poison-memory as byte-ptr! constants size? wire-constant-initializer!
	poison-memory as byte-ptr! scalar size? wire-scalar-operation!
	poison-memory as byte-ptr! control size? wire-control-flow!
	poison-memory as byte-ptr! calls size? wire-call-abi!
	poison-memory as byte-ptr! subroutines size? wire-subroutine!
]

outputs-poisoned?: func [
	strings [wire-string-table!]
	files [wire-file-source!]
	layout [wire-data-layout!]
	types [wire-type-layout!]
	functions [wire-function-signature!]
	modules [wire-module-lifecycle!]
	symbols [wire-symbol-linkage!]
	constants [wire-constant-initializer!]
	scalar [wire-scalar-operation!]
	control [wire-control-flow!]
	calls [wire-call-abi!]
	subroutines [wire-subroutine!]
	return: [logic!]
][
	all [
		memory-poisoned? as byte-ptr! strings size? wire-string-table!
		memory-poisoned? as byte-ptr! files size? wire-file-source!
		memory-poisoned? as byte-ptr! layout size? wire-data-layout!
		memory-poisoned? as byte-ptr! types size? wire-type-layout!
		memory-poisoned? as byte-ptr! functions size? wire-function-signature!
		memory-poisoned? as byte-ptr! modules size? wire-module-lifecycle!
		memory-poisoned? as byte-ptr! symbols size? wire-symbol-linkage!
		memory-poisoned? as byte-ptr! constants size? wire-constant-initializer!
		memory-poisoned? as byte-ptr! scalar size? wire-scalar-operation!
		memory-poisoned? as byte-ptr! control size? wire-control-flow!
		memory-poisoned? as byte-ptr! calls size? wire-call-abi!
		memory-poisoned? as byte-ptr! subroutines size? wire-subroutine!
	]
]

test-subroutine: func [
	name [c-string!]
	data [byte-ptr!]
	size [integer!]
	workspace [byte-ptr!]
	workspace-size [integer!]
	expected-error expected-call expected-control expected-scalar expected-container
	expected-string expected-file expected-layout expected-type expected-function
	expected-module expected-symbol expected-constant expected-offset expected-section
	expected-subroutine-count expected-member-count [integer!]
	return: [integer!]
	/local result [wire-subroutine-result!]
		strings [wire-string-table!]
		files [wire-file-source!]
		layout [wire-data-layout!]
		types [wire-type-layout!]
		functions [wire-function-signature!]
		modules [wire-module-lifecycle!]
		symbols [wire-symbol-linkage!]
		constants [wire-constant-initializer!]
		scalar [wire-scalar-operation!]
		control [wire-control-flow!]
		calls [wire-call-abi!]
		subroutines [wire-subroutine!]
		actual [integer!]
][
	result: declare wire-subroutine-result!
	strings: declare wire-string-table!
	files: declare wire-file-source!
	layout: declare wire-data-layout!
	types: declare wire-type-layout!
	functions: declare wire-function-signature!
	modules: declare wire-module-lifecycle!
	symbols: declare wire-symbol-linkage!
	constants: declare wire-constant-initializer!
	scalar: declare wire-scalar-operation!
	control: declare wire-control-flow!
	calls: declare wire-call-abi!
	subroutines: declare wire-subroutine!
	poison-outputs strings files layout types functions modules symbols constants
		scalar control calls subroutines
	actual: wire-subroutine-reader/verify data size workspace workspace-size result
		strings files layout types functions modules symbols constants scalar control
		calls subroutines
	if actual <> expected-error [
		print [
			"FAIL: " name " expected=" expected-error " actual=" actual
			" call=" result/call-abi-error " control=" result/control-flow-error
			" scalar=" result/scalar-operation-error " at=" result/error-offset
			":" result/error-section lf
		]
		return 1
	]
	if result/error <> expected-error [
		print ["FAIL: " name " result/error=" result/error lf]
		return 1
	]
	if result/call-abi-error <> expected-call [
		print ["FAIL: " name " call=" result/call-abi-error lf]
		return 1
	]
	if result/control-flow-error <> expected-control [return 1]
	if result/scalar-operation-error <> expected-scalar [return 1]
	if result/container-error <> expected-container [return 1]
	if result/string-error <> expected-string [return 1]
	if result/file-source-error <> expected-file [return 1]
	if result/data-layout-error <> expected-layout [return 1]
	if result/type-layout-error <> expected-type [return 1]
	if result/function-signature-error <> expected-function [return 1]
	if result/module-lifecycle-error <> expected-module [return 1]
	if result/symbol-linkage-error <> expected-symbol [return 1]
	if result/constant-initializer-error <> expected-constant [return 1]
	if any [
		result/error-offset <> expected-offset
		result/error-section <> expected-section
	][
		print [
			"FAIL: " name " location=" result/error-offset ":" result/error-section
			" expected=" expected-offset ":" expected-section lf
		]
		return 1
	]
	if all [
		expected-error <> WIRE_SUBROUTINE_ERROR_SUCCESS
		not outputs-poisoned? strings files layout types functions modules symbols
			constants scalar control calls subroutines
	][
		print ["FAIL: " name " modified output views on failure" lf]
		return 1
	]
	if all [
		expected-error = WIRE_SUBROUTINE_ERROR_SUCCESS
		any [
			subroutines/subroutine-count <> expected-subroutine-count
			subroutines/block-member-count <> expected-member-count
		]
	][
		print ["FAIL: " name " subroutine view counts changed" lf]
		return 1
	]
	0
]

failures: 0
}

foreach fixture valid-subroutines [
	verified-fixture: subroutine-verifier/verify fixture/2
	append output rejoin [
		{failures: failures + (test-subroutine "} form fixture/1 {" }
		"subroutine-valid-" word-name fixture/1 " " length? fixture/2
		" subroutine-workspace 64"
		" " schema/WIRE_SUBROUTINE_ERROR_SUCCESS
		" " schema/WIRE_CALL_ABI_ERROR_SUCCESS
		" " schema/WIRE_CONTROL_FLOW_ERROR_SUCCESS
		" " schema/WIRE_SCALAR_OPERATION_ERROR_SUCCESS
		" " schema/WIRE_CONTAINER_ERROR_SUCCESS
		" " schema/WIRE_STRING_TABLE_ERROR_SUCCESS
		" " schema/WIRE_FILE_SOURCE_ERROR_SUCCESS
		" " schema/WIRE_DATA_LAYOUT_ERROR_SUCCESS
		" " schema/WIRE_TYPE_LAYOUT_ERROR_SUCCESS
		" " schema/WIRE_FUNCTION_SIGNATURE_ERROR_SUCCESS
		" " schema/WIRE_MODULE_LIFECYCLE_ERROR_SUCCESS
		" " schema/WIRE_SYMBOL_LINKAGE_ERROR_SUCCESS
		" " schema/WIRE_CONSTANT_INITIALIZER_ERROR_SUCCESS
		" 0 0 " verified-fixture/view/subroutine-count
		" " verified-fixture/view/block-member-count ")" newline
	]
]

foreach fixture malformed-subroutines [
	append output rejoin [
		{failures: failures + (test-subroutine "} form fixture/1 {" }
		"subroutine-invalid-" word-name fixture/1 " " length? fixture/17
		" subroutine-workspace 64"
		" " fixture/2 " " fixture/3 " " fixture/4 " " fixture/5
		" " fixture/6 " " fixture/7 " " fixture/8 " " fixture/9
		" " fixture/10 " " fixture/11 " " fixture/12 " " fixture/13
		" " fixture/14 " " fixture/15 " " fixture/16 " -1 -1)" newline
	]
]

verified: subroutine-verifier/verify mutual-subroutine-message
append output rejoin [{

result: declare wire-subroutine-result!
strings: declare wire-string-table!
files: declare wire-file-source!
layout: declare wire-data-layout!
types: declare wire-type-layout!
functions: declare wire-function-signature!
modules: declare wire-module-lifecycle!
symbols: declare wire-symbol-linkage!
constants: declare wire-constant-initializer!
scalar: declare wire-scalar-operation!
control: declare wire-control-flow!
calls: declare wire-call-abi!
subroutines: declare wire-subroutine!
code: wire-subroutine-reader/verify subroutine-valid-mutual-recursion }
	length? mutual-subroutine-message {
	subroutine-workspace 64 result strings files layout types functions modules
	symbols constants scalar control calls subroutines
if code <> WIRE_SUBROUTINE_ERROR_SUCCESS [failures: failures + 1]
if any [
	functions/function-count <> } verified/functions/function-count {
	functions/block-count <> } verified/functions/block-count {
	scalar/value-count <> } verified/scalar-view/value-count {
	scalar/instruction-count <> } verified/scalar-view/instruction-count {
	scalar/operand-count <> } verified/scalar-view/operand-count {
	control/edge-count <> } verified/control-view/edge-count {
	calls/call-count <> } verified/call-view/call-count {
	subroutines/subroutine-count <> } verified/view/subroutine-count {
	subroutines/subroutine-record-size <> WIRE_RSIR_SUBROUTINE_SIZE
	subroutines/subroutines-offset <> } verified/view/subroutines-offset {
	subroutines/subroutines-ordinal <> } verified/view/subroutines-ordinal {
	subroutines/block-member-count <> } verified/view/block-member-count {
	subroutines/block-member-record-size <> WIRE_RSIR_SUBROUTINE_BLOCK_SIZE
	subroutines/block-members-offset <> } verified/view/block-members-offset {
	subroutines/block-members-ordinal <> } verified/view/block-members-ordinal {
][
	print ["FAIL: verified subroutine view changed" lf]
	failures: failures + 1
]
if any [
	(wire-container-reader/read-i31 subroutines/subroutines
		WIRE_RSIR_SUBROUTINE_FUNCTION_OFFSET) <> 1
	(wire-container-reader/read-i31 subroutines/subroutines
		WIRE_RSIR_SUBROUTINE_ENTRY_BLOCK_OFFSET) <> 2
	(wire-container-reader/read-i31
		(subroutines/subroutines + WIRE_RSIR_SUBROUTINE_SIZE)
		WIRE_RSIR_SUBROUTINE_ENTRY_BLOCK_OFFSET) <> 3
	(wire-container-reader/read-i31 subroutines/block-members
		WIRE_RSIR_SUBROUTINE_BLOCK_BLOCK_OFFSET) <> 2
][failures: failures + 1]

failures: failures + (test-subroutine "NULL-DATA" (as byte-ptr! 0)
	} length? subroutine-message { subroutine-workspace 64
	WIRE_SUBROUTINE_ERROR_INVALID_ARGUMENTS WIRE_CALL_ABI_ERROR_SUCCESS
	WIRE_CONTROL_FLOW_ERROR_SUCCESS WIRE_SCALAR_OPERATION_ERROR_SUCCESS
	WIRE_CONTAINER_ERROR_SUCCESS WIRE_STRING_TABLE_ERROR_SUCCESS
	WIRE_FILE_SOURCE_ERROR_SUCCESS WIRE_DATA_LAYOUT_ERROR_SUCCESS
	WIRE_TYPE_LAYOUT_ERROR_SUCCESS WIRE_FUNCTION_SIGNATURE_ERROR_SUCCESS
	WIRE_MODULE_LIFECYCLE_ERROR_SUCCESS WIRE_SYMBOL_LINKAGE_ERROR_SUCCESS
	WIRE_CONSTANT_INITIALIZER_ERROR_SUCCESS 0 0 -1 -1)
failures: failures + (test-subroutine "NEGATIVE-SIZE" subroutine-valid-basic -1
	subroutine-workspace 64 WIRE_SUBROUTINE_ERROR_INVALID_ARGUMENTS
	WIRE_CALL_ABI_ERROR_SUCCESS WIRE_CONTROL_FLOW_ERROR_SUCCESS
	WIRE_SCALAR_OPERATION_ERROR_SUCCESS WIRE_CONTAINER_ERROR_SUCCESS
	WIRE_STRING_TABLE_ERROR_SUCCESS WIRE_FILE_SOURCE_ERROR_SUCCESS
	WIRE_DATA_LAYOUT_ERROR_SUCCESS WIRE_TYPE_LAYOUT_ERROR_SUCCESS
	WIRE_FUNCTION_SIGNATURE_ERROR_SUCCESS WIRE_MODULE_LIFECYCLE_ERROR_SUCCESS
	WIRE_SYMBOL_LINKAGE_ERROR_SUCCESS WIRE_CONSTANT_INITIALIZER_ERROR_SUCCESS
	0 0 -1 -1)
failures: failures + (test-subroutine "NULL-WORKSPACE" subroutine-valid-basic
	} length? subroutine-message { (as byte-ptr! 0) 64
	WIRE_SUBROUTINE_ERROR_INVALID_ARGUMENTS WIRE_CALL_ABI_ERROR_SUCCESS
	WIRE_CONTROL_FLOW_ERROR_SUCCESS WIRE_SCALAR_OPERATION_ERROR_SUCCESS
	WIRE_CONTAINER_ERROR_SUCCESS WIRE_STRING_TABLE_ERROR_SUCCESS
	WIRE_FILE_SOURCE_ERROR_SUCCESS WIRE_DATA_LAYOUT_ERROR_SUCCESS
	WIRE_TYPE_LAYOUT_ERROR_SUCCESS WIRE_FUNCTION_SIGNATURE_ERROR_SUCCESS
	WIRE_MODULE_LIFECYCLE_ERROR_SUCCESS WIRE_SYMBOL_LINKAGE_ERROR_SUCCESS
	WIRE_CONSTANT_INITIALIZER_ERROR_SUCCESS 0 0 -1 -1)
failures: failures + (test-subroutine "NEGATIVE-WORKSPACE" subroutine-valid-basic
	} length? subroutine-message { subroutine-workspace -1
	WIRE_SUBROUTINE_ERROR_INVALID_ARGUMENTS WIRE_CALL_ABI_ERROR_SUCCESS
	WIRE_CONTROL_FLOW_ERROR_SUCCESS WIRE_SCALAR_OPERATION_ERROR_SUCCESS
	WIRE_CONTAINER_ERROR_SUCCESS WIRE_STRING_TABLE_ERROR_SUCCESS
	WIRE_FILE_SOURCE_ERROR_SUCCESS WIRE_DATA_LAYOUT_ERROR_SUCCESS
	WIRE_TYPE_LAYOUT_ERROR_SUCCESS WIRE_FUNCTION_SIGNATURE_ERROR_SUCCESS
	WIRE_MODULE_LIFECYCLE_ERROR_SUCCESS WIRE_SYMBOL_LINKAGE_ERROR_SUCCESS
	WIRE_CONSTANT_INITIALIZER_ERROR_SUCCESS 0 0 -1 -1)
failures: failures + (test-subroutine "INSUFFICIENT-WORKSPACE" subroutine-valid-basic
	} length? subroutine-message { subroutine-small-workspace 0
	WIRE_SUBROUTINE_ERROR_INVALID_CALL_ABI WIRE_CALL_ABI_ERROR_INVALID_CONTROL_FLOW
	WIRE_CONTROL_FLOW_ERROR_INSUFFICIENT_WORKSPACE WIRE_SCALAR_OPERATION_ERROR_SUCCESS
	WIRE_CONTAINER_ERROR_SUCCESS WIRE_STRING_TABLE_ERROR_SUCCESS
	WIRE_FILE_SOURCE_ERROR_SUCCESS WIRE_DATA_LAYOUT_ERROR_SUCCESS
	WIRE_TYPE_LAYOUT_ERROR_SUCCESS WIRE_FUNCTION_SIGNATURE_ERROR_SUCCESS
	WIRE_MODULE_LIFECYCLE_ERROR_SUCCESS WIRE_SYMBOL_LINKAGE_ERROR_SUCCESS
	WIRE_CONSTANT_INITIALIZER_ERROR_SUCCESS 0 0 -1 -1)

poison-outputs strings files layout types functions modules symbols constants
	scalar control calls subroutines
code: wire-subroutine-reader/verify subroutine-valid-basic } length? subroutine-message {
	subroutine-workspace 64 (as wire-subroutine-result! 0)
	strings files layout types functions modules symbols constants scalar control calls
	subroutines
if code <> WIRE_SUBROUTINE_ERROR_INVALID_ARGUMENTS [failures: failures + 1]
unless outputs-poisoned? strings files layout types functions modules symbols constants
	scalar control calls subroutines
[
	failures: failures + 1
]
}]

foreach [type-name before after] [
	wire-string-table! "result "
		" files layout types functions modules symbols constants scalar control calls subroutines"
	wire-file-source! "result strings "
		" layout types functions modules symbols constants scalar control calls subroutines"
	wire-data-layout! "result strings files "
		" types functions modules symbols constants scalar control calls subroutines"
	wire-type-layout! "result strings files layout "
		" functions modules symbols constants scalar control calls subroutines"
	wire-function-signature! "result strings files layout types "
		" modules symbols constants scalar control calls subroutines"
	wire-module-lifecycle! "result strings files layout types functions "
		" symbols constants scalar control calls subroutines"
	wire-symbol-linkage! "result strings files layout types functions modules "
		" constants scalar control calls subroutines"
	wire-constant-initializer! "result strings files layout types functions modules symbols "
		" scalar control calls subroutines"
	wire-scalar-operation! "result strings files layout types functions modules symbols constants "
		" control calls subroutines"
	wire-control-flow! "result strings files layout types functions modules symbols constants scalar "
		" calls subroutines"
	wire-call-abi! "result strings files layout types functions modules symbols constants scalar control "
		" subroutines"
	wire-subroutine! "result strings files layout types functions modules symbols constants scalar control calls "
		""
][
	append output rejoin [
		"code: wire-subroutine-reader/verify subroutine-valid-basic "
		length? subroutine-message " subroutine-workspace 64 "
		before "(as " type-name " 0)" after newline
		"if code <> WIRE_SUBROUTINE_ERROR_INVALID_ARGUMENTS "
		"[failures: failures + 1]" newline
	]
]

append output {

either failures = 0 [
	print ["PASS: Red/System RSIR subroutine semantics" lf]
][
	print ["FAIL: Red/System RSIR subroutine semantics failures=" failures lf]
]
quit failures
}

target: %tests/wire-subroutine-reds-test.reds
write target to binary! output
print [
	"Generated" target "with" length? valid-subroutines "valid and"
	length? malformed-subroutines "malformed fixtures"
]
