Red [
	Title: "Generate Red/System RSIR target-intrinsic fixture tests"
]

foreach flag [
	generating-wire-container-fixtures?
	generating-wire-string-table-fixtures?
	generating-wire-file-source-fixtures?
	generating-wire-data-layout-fixtures?
	generating-wire-type-layout-fixtures?
	generating-wire-function-signature-fixtures?
	generating-wire-module-lifecycle-fixtures?
	generating-wire-symbol-linkage-fixtures?
	generating-wire-constant-initializer-fixtures?
	generating-wire-scalar-operation-fixtures?
	generating-wire-control-flow-fixtures?
	generating-wire-call-abi-fixtures?
	generating-wire-subroutine-fixtures?
	generating-wire-exception-fixtures?
	generating-wire-stack-fixtures?
	generating-wire-target-intrinsic-fixtures?
][set flag true]
do %tests/wire-target-intrinsic-test.red

word-name: func [value [word!]][lowercase copy form value]

append-binary: func [output [string!] prefix [string!] name [word!] data [binary!]][
	append output rejoin [prefix word-name name ": " mold/flat data newline]
]

output: make string! 16'777'216
source-bytes: make binary! 8'388'608
foreach source-file [
	%tests/wire-target-intrinsic-test.red
	%tests/wire-stack-test.red
	%tests/wire-exception-test.red
	%tests/wire-subroutine-test.red
	%tests/wire-call-abi-test.red
	%tests/wire-control-flow-test.red
	%tests/wire-scalar-operation-test.red
	%tests/wire-constant-initializer-test.red
	%tests/wire-symbol-linkage-test.red
	%tests/wire-function-signature-test.red
	%tests/wire-module-lifecycle-test.red
	%tests/wire-type-layout-test.red
	%tests/wire-data-layout-test.red
	%tests/wire-file-source-test.red
	%tests/wire-string-table-test.red
	%tests/wire-container-test.red
	%generate-wire-subroutine-fixtures.red
	%generate-wire-exception-fixtures.red
	%generate-wire-stack-fixtures.red
	%generate-wire-target-intrinsic-fixtures.red
][append source-bytes read source-file]
append source-bytes to binary! mold schema/WIRE_SCHEMA_FINGERPRINT
source-digest: enbase/base checksum source-bytes 'SHA256 16

append output {Red/System [
	Title: "Generated RSIR target-intrinsic cross-language tests"
]

; Generated by tools/self_hosting/generate-wire-target-intrinsic-fixtures.red.
; Do not edit. Error codes and locations are frozen by the Red semantic corpus.
}
append output rejoin ["; Fixture source SHA256: " source-digest newline]
append output {
#include %../../../system/codegen/wire-target-intrinsic.reds

}

foreach fixture valid-targets [
	append-binary output "target-valid-" fixture/1 fixture/2
]
foreach fixture malformed-targets [
	append-binary output "target-invalid-" fixture/1 fixture/20
]

workspace-fixture: make binary! 513
append/dup workspace-fixture 0 513
append output rejoin ["target-workspace: " mold/flat workspace-fixture newline newline]

append output {
poison-memory: func [
	memory [byte-ptr!]
	size [integer!]
	/local cursor [byte-ptr!] remaining [integer!]
][
	cursor: memory
	remaining: size
	while [remaining > 0][
		cursor/1: as byte! 165
		cursor: cursor + 1
		remaining: remaining - 1
	]
]

memory-poisoned?: func [
	memory [byte-ptr!]
	size [integer!]
	return: [logic!]
	/local cursor [byte-ptr!] remaining [integer!]
][
	cursor: memory
	remaining: size
	while [remaining > 0][
		if cursor/1 <> as byte! 165 [return false]
		cursor: cursor + 1
		remaining: remaining - 1
	]
	true
]

poison-outputs: func [
	strings [wire-string-table!]
	files [wire-file-source!]
	layout [wire-data-layout!]
	types [wire-type-layout!]
	functions [wire-function-signature!]
	modules [wire-module-lifecycle!]
	symbols [wire-symbol-linkage!]
	constants [wire-constant-initializer!]
	scalar [wire-scalar-operation!]
	control [wire-control-flow!]
	calls [wire-call-abi!]
	subroutines [wire-subroutine!]
	exceptions [wire-exception!]
	view [wire-target-intrinsic!]
][
	poison-memory as byte-ptr! strings size? wire-string-table!
	poison-memory as byte-ptr! files size? wire-file-source!
	poison-memory as byte-ptr! layout size? wire-data-layout!
	poison-memory as byte-ptr! types size? wire-type-layout!
	poison-memory as byte-ptr! functions size? wire-function-signature!
	poison-memory as byte-ptr! modules size? wire-module-lifecycle!
	poison-memory as byte-ptr! symbols size? wire-symbol-linkage!
	poison-memory as byte-ptr! constants size? wire-constant-initializer!
	poison-memory as byte-ptr! scalar size? wire-scalar-operation!
	poison-memory as byte-ptr! control size? wire-control-flow!
	poison-memory as byte-ptr! calls size? wire-call-abi!
	poison-memory as byte-ptr! subroutines size? wire-subroutine!
	poison-memory as byte-ptr! exceptions size? wire-exception!
	poison-memory as byte-ptr! view size? wire-target-intrinsic!
]

outputs-poisoned?: func [
	strings [wire-string-table!]
	files [wire-file-source!]
	layout [wire-data-layout!]
	types [wire-type-layout!]
	functions [wire-function-signature!]
	modules [wire-module-lifecycle!]
	symbols [wire-symbol-linkage!]
	constants [wire-constant-initializer!]
	scalar [wire-scalar-operation!]
	control [wire-control-flow!]
	calls [wire-call-abi!]
	subroutines [wire-subroutine!]
	exceptions [wire-exception!]
	view [wire-target-intrinsic!]
	return: [logic!]
][
	all [
		memory-poisoned? as byte-ptr! strings size? wire-string-table!
		memory-poisoned? as byte-ptr! files size? wire-file-source!
		memory-poisoned? as byte-ptr! layout size? wire-data-layout!
		memory-poisoned? as byte-ptr! types size? wire-type-layout!
		memory-poisoned? as byte-ptr! functions size? wire-function-signature!
		memory-poisoned? as byte-ptr! modules size? wire-module-lifecycle!
		memory-poisoned? as byte-ptr! symbols size? wire-symbol-linkage!
		memory-poisoned? as byte-ptr! constants size? wire-constant-initializer!
		memory-poisoned? as byte-ptr! scalar size? wire-scalar-operation!
		memory-poisoned? as byte-ptr! control size? wire-control-flow!
		memory-poisoned? as byte-ptr! calls size? wire-call-abi!
		memory-poisoned? as byte-ptr! subroutines size? wire-subroutine!
		memory-poisoned? as byte-ptr! exceptions size? wire-exception!
		memory-poisoned? as byte-ptr! view size? wire-target-intrinsic!
	]
]

test-target: func [
	name [c-string!]
	data [byte-ptr!]
	size [integer!]
	workspace [byte-ptr!]
	workspace-size [integer!]
	expected-error expected-stack expected-exception expected-subroutine expected-call
	expected-control expected-scalar expected-container expected-string expected-file
	expected-layout expected-type expected-function expected-module expected-symbol
	expected-constant expected-offset expected-section expected-fragments
	expected-owned-data expected-data-size expected-instructions expected-calls [integer!]
	return: [integer!]
	/local result [wire-target-intrinsic-result!]
		strings [wire-string-table!]
		files [wire-file-source!]
		layout [wire-data-layout!]
		types [wire-type-layout!]
		functions [wire-function-signature!]
		modules [wire-module-lifecycle!]
		symbols [wire-symbol-linkage!]
		constants [wire-constant-initializer!]
		scalar [wire-scalar-operation!]
		control [wire-control-flow!]
		calls [wire-call-abi!]
		subroutines [wire-subroutine!]
		exceptions [wire-exception!]
		view [wire-target-intrinsic!]
		actual [integer!]
][
	result: declare wire-target-intrinsic-result!
	strings: declare wire-string-table!
	files: declare wire-file-source!
	layout: declare wire-data-layout!
	types: declare wire-type-layout!
	functions: declare wire-function-signature!
	modules: declare wire-module-lifecycle!
	symbols: declare wire-symbol-linkage!
	constants: declare wire-constant-initializer!
	scalar: declare wire-scalar-operation!
	control: declare wire-control-flow!
	calls: declare wire-call-abi!
	subroutines: declare wire-subroutine!
	exceptions: declare wire-exception!
	view: declare wire-target-intrinsic!
	poison-outputs strings files layout types functions modules symbols constants
		scalar control calls subroutines exceptions view
	actual: wire-target-intrinsic-reader/verify data size workspace workspace-size result
		strings files layout types functions modules symbols constants scalar control calls
		subroutines exceptions view
	if actual <> expected-error [
		print ["FAIL: " name " expected=" expected-error " actual=" actual lf]
		return 1
	]
	if result/error <> expected-error [return 1]
	if result/stack-error <> expected-stack [return 1]
	if result/exception-error <> expected-exception [return 1]
	if result/subroutine-error <> expected-subroutine [return 1]
	if result/call-abi-error <> expected-call [return 1]
	if result/control-flow-error <> expected-control [return 1]
	if result/scalar-operation-error <> expected-scalar [return 1]
	if result/container-error <> expected-container [return 1]
	if result/string-error <> expected-string [return 1]
	if result/file-source-error <> expected-file [return 1]
	if result/data-layout-error <> expected-layout [return 1]
	if result/type-layout-error <> expected-type [return 1]
	if result/function-signature-error <> expected-function [return 1]
	if result/module-lifecycle-error <> expected-module [return 1]
	if result/symbol-linkage-error <> expected-symbol [return 1]
	if result/constant-initializer-error <> expected-constant [return 1]
	if any [
		result/error-offset <> expected-offset
		result/error-section <> expected-section
	][
		print [
			"FAIL: " name " location=" result/error-offset ":" result/error-section
			" expected=" expected-offset ":" expected-section lf
		]
		return 1
	]
	if all [
		expected-error <> WIRE_TARGET_INTRINSIC_ERROR_SUCCESS
		not outputs-poisoned? strings files layout types functions modules symbols
			constants scalar control calls subroutines exceptions view
	][
		print ["FAIL: " name " modified output views on failure" lf]
		return 1
	]
	if all [
		expected-error = WIRE_TARGET_INTRINSIC_ERROR_SUCCESS
		any [
			view/target-fragment-count <> expected-fragments
			view/target-fragment-record-size <> WIRE_RSIR_TARGET_FRAGMENT_SIZE
			constants/constant-data-owned-size <> expected-owned-data
			constants/constant-data-size <> expected-data-size
			scalar/instruction-count <> expected-instructions
			calls/call-count <> expected-calls
		]
	][
		print ["FAIL: " name " published view counts changed" lf]
		return 1
	]
	0
]

failures: 0
}

foreach fixture valid-targets [
	verified: target-verifier/verify fixture/2
	append output rejoin [
		{failures: failures + (test-target "} form fixture/1 {" }
		"target-valid-" word-name fixture/1 " " length? fixture/2
		" target-workspace 513"
		" " schema/WIRE_TARGET_INTRINSIC_ERROR_SUCCESS
		" " schema/WIRE_STACK_ERROR_SUCCESS
		" " schema/WIRE_EXCEPTION_ERROR_SUCCESS
		" " schema/WIRE_SUBROUTINE_ERROR_SUCCESS
		" " schema/WIRE_CALL_ABI_ERROR_SUCCESS
		" " schema/WIRE_CONTROL_FLOW_ERROR_SUCCESS
		" " schema/WIRE_SCALAR_OPERATION_ERROR_SUCCESS
		" " schema/WIRE_CONTAINER_ERROR_SUCCESS
		" " schema/WIRE_STRING_TABLE_ERROR_SUCCESS
		" " schema/WIRE_FILE_SOURCE_ERROR_SUCCESS
		" " schema/WIRE_DATA_LAYOUT_ERROR_SUCCESS
		" " schema/WIRE_TYPE_LAYOUT_ERROR_SUCCESS
		" " schema/WIRE_FUNCTION_SIGNATURE_ERROR_SUCCESS
		" " schema/WIRE_MODULE_LIFECYCLE_ERROR_SUCCESS
		" " schema/WIRE_SYMBOL_LINKAGE_ERROR_SUCCESS
		" " schema/WIRE_CONSTANT_INITIALIZER_ERROR_SUCCESS
		" 0 0 " verified/view/target-fragment-count
		" " verified/constants/constant-data-owned-size
		" " verified/constants/constant-data-size
		" " verified/scalar-view/instruction-count
		" " verified/call-view/call-count ")" newline
	]
]

foreach fixture malformed-targets [
	append output rejoin [
		{failures: failures + (test-target "} form fixture/1 {" }
		"target-invalid-" word-name fixture/1 " " length? fixture/20
		" target-workspace 513"
		" " fixture/2 " " fixture/3 " " fixture/4 " " fixture/5
		" " fixture/6 " " fixture/7 " " fixture/8 " " fixture/9
		" " fixture/10 " " fixture/11 " " fixture/12 " " fixture/13
		" " fixture/14 " " fixture/15 " " fixture/16 " " fixture/17
		" " fixture/18 " " fixture/19 " -1 -1 -1 -1 -1)" newline
	]
]

verified-target: target-verifier/verify valid-target-message
append output rejoin [{

failures: failures + (test-target "EXACT-WORKSPACE" target-valid-target-intrinsics
	} length? valid-target-message { target-workspace 24
	WIRE_TARGET_INTRINSIC_ERROR_SUCCESS WIRE_STACK_ERROR_SUCCESS
	WIRE_EXCEPTION_ERROR_SUCCESS WIRE_SUBROUTINE_ERROR_SUCCESS
	WIRE_CALL_ABI_ERROR_SUCCESS WIRE_CONTROL_FLOW_ERROR_SUCCESS
	WIRE_SCALAR_OPERATION_ERROR_SUCCESS WIRE_CONTAINER_ERROR_SUCCESS
	WIRE_STRING_TABLE_ERROR_SUCCESS WIRE_FILE_SOURCE_ERROR_SUCCESS
	WIRE_DATA_LAYOUT_ERROR_SUCCESS WIRE_TYPE_LAYOUT_ERROR_SUCCESS
	WIRE_FUNCTION_SIGNATURE_ERROR_SUCCESS WIRE_MODULE_LIFECYCLE_ERROR_SUCCESS
	WIRE_SYMBOL_LINKAGE_ERROR_SUCCESS WIRE_CONSTANT_INITIALIZER_ERROR_SUCCESS
	0 0 } verified-target/view/target-fragment-count " "
	verified-target/constants/constant-data-owned-size " "
	verified-target/constants/constant-data-size " "
	verified-target/scalar-view/instruction-count " "
	verified-target/call-view/call-count {)
failures: failures + (test-target "UNALIGNED-WORKSPACE" target-valid-target-intrinsics
	} length? valid-target-message { (target-workspace + 1) 24
	WIRE_TARGET_INTRINSIC_ERROR_SUCCESS WIRE_STACK_ERROR_SUCCESS
	WIRE_EXCEPTION_ERROR_SUCCESS WIRE_SUBROUTINE_ERROR_SUCCESS
	WIRE_CALL_ABI_ERROR_SUCCESS WIRE_CONTROL_FLOW_ERROR_SUCCESS
	WIRE_SCALAR_OPERATION_ERROR_SUCCESS WIRE_CONTAINER_ERROR_SUCCESS
	WIRE_STRING_TABLE_ERROR_SUCCESS WIRE_FILE_SOURCE_ERROR_SUCCESS
	WIRE_DATA_LAYOUT_ERROR_SUCCESS WIRE_TYPE_LAYOUT_ERROR_SUCCESS
	WIRE_FUNCTION_SIGNATURE_ERROR_SUCCESS WIRE_MODULE_LIFECYCLE_ERROR_SUCCESS
	WIRE_SYMBOL_LINKAGE_ERROR_SUCCESS WIRE_CONSTANT_INITIALIZER_ERROR_SUCCESS
	0 0 } verified-target/view/target-fragment-count " "
	verified-target/constants/constant-data-owned-size " "
	verified-target/constants/constant-data-size " "
	verified-target/scalar-view/instruction-count " "
	verified-target/call-view/call-count {)
failures: failures + (test-target "INSUFFICIENT-WORKSPACE"
	target-valid-target-intrinsics } length? valid-target-message { target-workspace 23
	WIRE_TARGET_INTRINSIC_ERROR_INVALID_STACK WIRE_STACK_ERROR_INSUFFICIENT_WORKSPACE
	WIRE_EXCEPTION_ERROR_SUCCESS WIRE_SUBROUTINE_ERROR_SUCCESS
	WIRE_CALL_ABI_ERROR_SUCCESS WIRE_CONTROL_FLOW_ERROR_SUCCESS
	WIRE_SCALAR_OPERATION_ERROR_SUCCESS WIRE_CONTAINER_ERROR_SUCCESS
	WIRE_STRING_TABLE_ERROR_SUCCESS WIRE_FILE_SOURCE_ERROR_SUCCESS
	WIRE_DATA_LAYOUT_ERROR_SUCCESS WIRE_TYPE_LAYOUT_ERROR_SUCCESS
	WIRE_FUNCTION_SIGNATURE_ERROR_SUCCESS WIRE_MODULE_LIFECYCLE_ERROR_SUCCESS
	WIRE_SYMBOL_LINKAGE_ERROR_SUCCESS WIRE_CONSTANT_INITIALIZER_ERROR_SUCCESS
	0 0 -1 -1 -1 -1 -1)
failures: failures + (test-target "NULL-DATA" (as byte-ptr! 0)
	} length? valid-target-message { target-workspace 513
	WIRE_TARGET_INTRINSIC_ERROR_INVALID_ARGUMENTS WIRE_STACK_ERROR_SUCCESS
	WIRE_EXCEPTION_ERROR_SUCCESS WIRE_SUBROUTINE_ERROR_SUCCESS
	WIRE_CALL_ABI_ERROR_SUCCESS WIRE_CONTROL_FLOW_ERROR_SUCCESS
	WIRE_SCALAR_OPERATION_ERROR_SUCCESS WIRE_CONTAINER_ERROR_SUCCESS
	WIRE_STRING_TABLE_ERROR_SUCCESS WIRE_FILE_SOURCE_ERROR_SUCCESS
	WIRE_DATA_LAYOUT_ERROR_SUCCESS WIRE_TYPE_LAYOUT_ERROR_SUCCESS
	WIRE_FUNCTION_SIGNATURE_ERROR_SUCCESS WIRE_MODULE_LIFECYCLE_ERROR_SUCCESS
	WIRE_SYMBOL_LINKAGE_ERROR_SUCCESS WIRE_CONSTANT_INITIALIZER_ERROR_SUCCESS
	0 0 -1 -1 -1 -1 -1)
failures: failures + (test-target "NEGATIVE-SIZE" target-valid-target-intrinsics -1
	target-workspace 513 WIRE_TARGET_INTRINSIC_ERROR_INVALID_ARGUMENTS
	WIRE_STACK_ERROR_SUCCESS WIRE_EXCEPTION_ERROR_SUCCESS
	WIRE_SUBROUTINE_ERROR_SUCCESS WIRE_CALL_ABI_ERROR_SUCCESS
	WIRE_CONTROL_FLOW_ERROR_SUCCESS WIRE_SCALAR_OPERATION_ERROR_SUCCESS
	WIRE_CONTAINER_ERROR_SUCCESS WIRE_STRING_TABLE_ERROR_SUCCESS
	WIRE_FILE_SOURCE_ERROR_SUCCESS WIRE_DATA_LAYOUT_ERROR_SUCCESS
	WIRE_TYPE_LAYOUT_ERROR_SUCCESS WIRE_FUNCTION_SIGNATURE_ERROR_SUCCESS
	WIRE_MODULE_LIFECYCLE_ERROR_SUCCESS WIRE_SYMBOL_LINKAGE_ERROR_SUCCESS
	WIRE_CONSTANT_INITIALIZER_ERROR_SUCCESS 0 0 -1 -1 -1 -1 -1)
failures: failures + (test-target "NULL-WORKSPACE" target-valid-target-intrinsics
	} length? valid-target-message { (as byte-ptr! 0) 513
	WIRE_TARGET_INTRINSIC_ERROR_INVALID_ARGUMENTS WIRE_STACK_ERROR_SUCCESS
	WIRE_EXCEPTION_ERROR_SUCCESS WIRE_SUBROUTINE_ERROR_SUCCESS
	WIRE_CALL_ABI_ERROR_SUCCESS WIRE_CONTROL_FLOW_ERROR_SUCCESS
	WIRE_SCALAR_OPERATION_ERROR_SUCCESS WIRE_CONTAINER_ERROR_SUCCESS
	WIRE_STRING_TABLE_ERROR_SUCCESS WIRE_FILE_SOURCE_ERROR_SUCCESS
	WIRE_DATA_LAYOUT_ERROR_SUCCESS WIRE_TYPE_LAYOUT_ERROR_SUCCESS
	WIRE_FUNCTION_SIGNATURE_ERROR_SUCCESS WIRE_MODULE_LIFECYCLE_ERROR_SUCCESS
	WIRE_SYMBOL_LINKAGE_ERROR_SUCCESS WIRE_CONSTANT_INITIALIZER_ERROR_SUCCESS
	0 0 -1 -1 -1 -1 -1)
failures: failures + (test-target "NEGATIVE-WORKSPACE" target-valid-target-intrinsics
	} length? valid-target-message { target-workspace -1
	WIRE_TARGET_INTRINSIC_ERROR_INVALID_ARGUMENTS WIRE_STACK_ERROR_SUCCESS
	WIRE_EXCEPTION_ERROR_SUCCESS WIRE_SUBROUTINE_ERROR_SUCCESS
	WIRE_CALL_ABI_ERROR_SUCCESS WIRE_CONTROL_FLOW_ERROR_SUCCESS
	WIRE_SCALAR_OPERATION_ERROR_SUCCESS WIRE_CONTAINER_ERROR_SUCCESS
	WIRE_STRING_TABLE_ERROR_SUCCESS WIRE_FILE_SOURCE_ERROR_SUCCESS
	WIRE_DATA_LAYOUT_ERROR_SUCCESS WIRE_TYPE_LAYOUT_ERROR_SUCCESS
	WIRE_FUNCTION_SIGNATURE_ERROR_SUCCESS WIRE_MODULE_LIFECYCLE_ERROR_SUCCESS
	WIRE_SYMBOL_LINKAGE_ERROR_SUCCESS WIRE_CONSTANT_INITIALIZER_ERROR_SUCCESS
	0 0 -1 -1 -1 -1 -1)

result: declare wire-target-intrinsic-result!
strings: declare wire-string-table!
files: declare wire-file-source!
layout: declare wire-data-layout!
types: declare wire-type-layout!
functions: declare wire-function-signature!
modules: declare wire-module-lifecycle!
symbols: declare wire-symbol-linkage!
constants: declare wire-constant-initializer!
scalar: declare wire-scalar-operation!
control: declare wire-control-flow!
calls: declare wire-call-abi!
subroutines: declare wire-subroutine!
exceptions: declare wire-exception!
view: declare wire-target-intrinsic!
poison-outputs strings files layout types functions modules symbols constants
	scalar control calls subroutines exceptions view
code: wire-target-intrinsic-reader/verify target-valid-target-intrinsics
	} length? valid-target-message { target-workspace 513 (as wire-target-intrinsic-result! 0)
	strings files layout types functions modules symbols constants scalar control calls
	subroutines exceptions view
if code <> WIRE_TARGET_INTRINSIC_ERROR_INVALID_ARGUMENTS [failures: failures + 1]
unless outputs-poisoned? strings files layout types functions modules symbols constants
	scalar control calls subroutines exceptions view
[
	failures: failures + 1
]
code: wire-target-intrinsic-reader/verify target-valid-target-intrinsics
	} length? valid-target-message { target-workspace 513 result strings files layout types
	functions modules symbols constants scalar control calls subroutines exceptions
	(as wire-target-intrinsic! 0)
if code <> WIRE_TARGET_INTRINSIC_ERROR_INVALID_ARGUMENTS [failures: failures + 1]
}]

append output {

either failures = 0 [
	print ["PASS: Red/System RSIR target-intrinsic semantics" lf]
][
	print ["FAIL: Red/System RSIR target-intrinsic semantics failures=" failures lf]
]
quit failures
}

target: %tests/wire-target-intrinsic-reds-test.reds
write target to binary! output
print [
	"Generated" target "with" length? valid-targets "valid and"
	length? malformed-targets "malformed fixtures"
]
