Red [
	Title: "Generate Red/System RSCF semantic fixture tests"
]

generating-wire-rscf-fixtures?: true
do %tests/wire-rscf-test.red

word-name: func [value [word!]][lowercase copy form value]

append-binary: func [output [string!] prefix [string!] name [word!] data [binary!]][
	append output rejoin [
		prefix word-name name ": " mold/flat data newline
	]
]

output: make string! 65536
source-bytes: make binary! 65536
append source-bytes read %tests/wire-rscf-test.red
append source-bytes read %generate-wire-rscf-fixtures.red
append source-bytes to binary! mold schema/WIRE_SCHEMA_FINGERPRINT
source-digest: enbase/base checksum source-bytes 'SHA256 16

append output {Red/System [
	Title: "Generated RSCF semantic cross-language tests"
]

; Generated by tools/self_hosting/generate-wire-rscf-fixtures.red.
; Do not edit. Error codes and locations are frozen by the Red semantic corpus.
}
append output rejoin ["; Fixture source SHA256: " source-digest newline]
append output {
#include %../../../system/codegen/wire-rscf.reds

}

foreach fixture valid-rscf [
	append-binary output "rscf-valid-" fixture/1 fixture/2
]
foreach fixture malformed-rscf [
	append-binary output "rscf-invalid-" fixture/1 fixture/6
]

append output {
poison-config: func [config [wire-rscf-config!]][
	config/optimization-level: -101
	config/flags: -102
	config/code-model: -103
	config/relocation-model: -104
	config/debug-format: -105
	config/cpu-baseline: -106
	config/cpu-features-low: -107
	config/cpu-features-high: -108
	config/max-output-bytes: -109
	config/max-diagnostic-bytes: -110
	config/worker-count: -111
	config/deterministic-seed: -112
]

config-poisoned?: func [config [wire-rscf-config!] return: [logic!]][
	all [
		config/optimization-level = -101
		config/flags = -102
		config/code-model = -103
		config/relocation-model = -104
		config/debug-format = -105
		config/cpu-baseline = -106
		config/cpu-features-low = -107
		config/cpu-features-high = -108
		config/max-output-bytes = -109
		config/max-diagnostic-bytes = -110
		config/worker-count = -111
		config/deterministic-seed = -112
	]
]

test-rscf: func [
	name [c-string!]
	data [byte-ptr!]
	size expected-error expected-container expected-offset expected-section [integer!]
	return: [integer!]
	/local result [wire-rscf-result!] config [wire-rscf-config!] actual [integer!]
][
	result: declare wire-rscf-result!
	config: declare wire-rscf-config!
	poison-config config
	actual: wire-rscf-reader/verify data size result config
	if actual <> expected-error [
		print ["FAIL: " name " expected=" expected-error " actual=" actual lf]
		return 1
	]
	if result/error <> expected-error [
		print ["FAIL: " name " result/error=" result/error lf]
		return 1
	]
	if result/container-error <> expected-container [
		print [
			"FAIL: " name " container=" result/container-error
			" expected=" expected-container lf
		]
		return 1
	]
	if any [
		result/error-offset <> expected-offset
		result/error-section <> expected-section
	][
		print [
			"FAIL: " name
			" location=" result/error-offset ":" result/error-section
			" expected=" expected-offset ":" expected-section lf
		]
		return 1
	]
	if all [
		expected-error <> WIRE_RSCF_ERROR_SUCCESS
		not config-poisoned? config
	][
		print ["FAIL: " name " modified config on failure" lf]
		return 1
	]
	0
]

failures: 0
}

foreach fixture valid-rscf [
	append output rejoin [
		{failures: failures + (test-rscf "} form fixture/1 {" }
		"rscf-valid-" word-name fixture/1 " " length? fixture/2 " "
		schema/WIRE_RSCF_ERROR_SUCCESS " " schema/WIRE_CONTAINER_ERROR_SUCCESS
		" 0 0)" newline
	]
]

foreach fixture malformed-rscf [
	append output rejoin [
		{failures: failures + (test-rscf "} form fixture/1 {" }
		"rscf-invalid-" word-name fixture/1 " " length? fixture/6 " "
		fixture/2 " " fixture/3 " " fixture/4 " " fixture/5 ")" newline
	]
]

append output {

result: declare wire-rscf-result!
config: declare wire-rscf-config!
code: wire-rscf-reader/verify rscf-valid-base 160 result config
if code <> WIRE_RSCF_ERROR_SUCCESS [failures: failures + 1]
if any [
	config/optimization-level <> WIRE_OPTIMIZATION_LEVEL_O0
	config/flags <> 0
	config/code-model <> WIRE_CODE_MODEL_SMALL
	config/relocation-model <> WIRE_RELOCATION_MODEL_STATIC
	config/debug-format <> WIRE_DEBUG_FORMAT_NONE
	config/cpu-baseline <> WIRE_CPU_BASELINE_X86_64_BASE
	config/cpu-features-low <> 0
	config/cpu-features-high <> 0
	config/max-output-bytes <> 1048576
	config/max-diagnostic-bytes <> 65536
	config/worker-count <> 1
	config/deterministic-seed <> 0
][
	print ["FAIL: base RSCF config decode changed" lf]
	failures: failures + 1
]

poison-config config
code: wire-rscf-reader/verify
	(as byte-ptr! 0) 160 result config
if code <> WIRE_RSCF_ERROR_INVALID_ARGUMENTS [failures: failures + 1]
if any [
	result/error <> WIRE_RSCF_ERROR_INVALID_ARGUMENTS
	result/container-error <> WIRE_CONTAINER_ERROR_SUCCESS
	result/error-offset <> 0
	result/error-section <> 0
][failures: failures + 1]
unless config-poisoned? config [failures: failures + 1]

code: wire-rscf-reader/verify rscf-valid-base -1 result config
if code <> WIRE_RSCF_ERROR_INVALID_ARGUMENTS [failures: failures + 1]
unless config-poisoned? config [failures: failures + 1]

code: wire-rscf-reader/verify
	rscf-valid-base 160 result (as wire-rscf-config! 0)
if code <> WIRE_RSCF_ERROR_INVALID_ARGUMENTS [failures: failures + 1]

code: wire-rscf-reader/verify
	rscf-valid-base 160 (as wire-rscf-result! 0) config
if code <> WIRE_RSCF_ERROR_INVALID_ARGUMENTS [failures: failures + 1]

either failures = 0 [
	print ["PASS: Red/System RSCF semantics" lf]
][
	print ["FAIL: Red/System RSCF semantics failures=" failures lf]
]
quit failures
}

target: %tests/wire-rscf-reds-test.reds
write target to binary! output
print [
	"Generated" target
	"with" length? valid-rscf "valid and" length? malformed-rscf "malformed fixtures"
]
