Red [
	Title: "Generate Red/System RSIR function and signature fixture tests"
]

generating-wire-function-signature-fixtures?: true
do %tests/wire-function-signature-test.red

word-name: func [value [word!]][lowercase copy form value]

append-binary: func [output [string!] prefix [string!] name [word!] data [binary!]][
	append output rejoin [prefix word-name name ": " mold/flat data newline]
]

output: make string! 2'097'152
source-bytes: make binary! 524288
append source-bytes read %tests/wire-function-signature-test.red
append source-bytes read %tests/wire-type-layout-test.red
append source-bytes read %tests/wire-file-source-test.red
append source-bytes read %tests/wire-string-table-test.red
append source-bytes read %tests/wire-container-test.red
append source-bytes read %generate-wire-function-signature-fixtures.red
append source-bytes to binary! mold schema/WIRE_SCHEMA_FINGERPRINT
source-digest: enbase/base checksum source-bytes 'SHA256 16

append output {Red/System [
	Title: "Generated RSIR function and signature cross-language tests"
]

; Generated by tools/self_hosting/generate-wire-function-signature-fixtures.red.
; Do not edit. Error codes and locations are frozen by the Red semantic corpus.
}
append output rejoin ["; Fixture source SHA256: " source-digest newline]
append output {
#include %../../../system/codegen/wire-function-signature.reds

}

foreach fixture valid-function-signatures [
	append-binary output "function-valid-" fixture/1 fixture/2
]
foreach fixture malformed-function-signatures [
	append-binary output "function-invalid-" fixture/1 fixture/10
]

append output {
poison-strings: func [strings [wire-string-table!]][
	strings/records: as byte-ptr! 101
	strings/record-count: -102
	strings/record-size: -103
	strings/records-offset: -104
	strings/records-ordinal: -105
	strings/data: as byte-ptr! 106
	strings/data-size: -107
	strings/data-offset: -108
	strings/data-ordinal: -109
]

strings-poisoned?: func [strings [wire-string-table!] return: [logic!]][
	all [
		strings/records = (as byte-ptr! 101)
		strings/record-count = -102
		strings/record-size = -103
		strings/records-offset = -104
		strings/records-ordinal = -105
		strings/data = (as byte-ptr! 106)
		strings/data-size = -107
		strings/data-offset = -108
		strings/data-ordinal = -109
	]
]

poison-files: func [files [wire-file-source!]][
	files/files: as byte-ptr! 201
	files/file-count: -202
	files/file-record-size: -203
	files/files-offset: -204
	files/files-ordinal: -205
	files/checksum-data: as byte-ptr! 206
	files/checksum-data-size: -207
	files/checksum-data-offset: -208
	files/checksum-data-ordinal: -209
	files/source-present: -210
	files/sources: as byte-ptr! 211
	files/source-count: -212
	files/source-record-size: -213
	files/source-offset: -214
	files/source-ordinal: -215
]

files-poisoned?: func [files [wire-file-source!] return: [logic!]][
	all [
		files/files = (as byte-ptr! 201)
		files/file-count = -202
		files/file-record-size = -203
		files/files-offset = -204
		files/files-ordinal = -205
		files/checksum-data = (as byte-ptr! 206)
		files/checksum-data-size = -207
		files/checksum-data-offset = -208
		files/checksum-data-ordinal = -209
		files/source-present = -210
		files/sources = (as byte-ptr! 211)
		files/source-count = -212
		files/source-record-size = -213
		files/source-offset = -214
		files/source-ordinal = -215
	]
]

poison-layout: func [layout [wire-data-layout!]][
	layout/address-unit: -301
	layout/pointer-size: -302
	layout/pointer-alignment: -303
	layout/stack-alignment: -304
	layout/max-scalar-alignment: -305
	layout/max-aggregate-alignment: -306
	layout/integer-register-width: -307
	layout/flags: -308
]

layout-poisoned?: func [layout [wire-data-layout!] return: [logic!]][
	all [
		layout/address-unit = -301
		layout/pointer-size = -302
		layout/pointer-alignment = -303
		layout/stack-alignment = -304
		layout/max-scalar-alignment = -305
		layout/max-aggregate-alignment = -306
		layout/integer-register-width = -307
		layout/flags = -308
	]
]

poison-types: func [types [wire-type-layout!]][
	types/types: as byte-ptr! 401
	types/type-count: -402
	types/type-record-size: -403
	types/types-offset: -404
	types/types-ordinal: -405
	types/fields: as byte-ptr! 406
	types/field-count: -407
	types/field-record-size: -408
	types/fields-offset: -409
	types/fields-ordinal: -410
	types/signature-count: -411
	types/source-location-count: -412
]

types-poisoned?: func [types [wire-type-layout!] return: [logic!]][
	all [
		types/types = (as byte-ptr! 401)
		types/type-count = -402
		types/type-record-size = -403
		types/types-offset = -404
		types/types-ordinal = -405
		types/fields = (as byte-ptr! 406)
		types/field-count = -407
		types/field-record-size = -408
		types/fields-offset = -409
		types/fields-ordinal = -410
		types/signature-count = -411
		types/source-location-count = -412
	]
]

poison-view: func [view [wire-function-signature!]][
	view/signatures: as byte-ptr! 501
	view/signature-count: -502
	view/signature-record-size: -503
	view/signatures-offset: -504
	view/signatures-ordinal: -505
	view/parameters: as byte-ptr! 506
	view/parameter-count: -507
	view/parameter-record-size: -508
	view/parameters-offset: -509
	view/parameters-ordinal: -510
	view/symbol-count: -511
	view/functions: as byte-ptr! 512
	view/function-count: -513
	view/function-record-size: -514
	view/functions-offset: -515
	view/functions-ordinal: -516
	view/locals: as byte-ptr! 517
	view/local-count: -518
	view/local-record-size: -519
	view/locals-offset: -520
	view/locals-ordinal: -521
	view/blocks: as byte-ptr! 522
	view/block-count: -523
	view/block-record-size: -524
	view/blocks-offset: -525
	view/blocks-ordinal: -526
	view/source-location-count: -527
]

view-poisoned?: func [view [wire-function-signature!] return: [logic!]][
	all [
		view/signatures = (as byte-ptr! 501)
		view/signature-count = -502
		view/signature-record-size = -503
		view/signatures-offset = -504
		view/signatures-ordinal = -505
		view/parameters = (as byte-ptr! 506)
		view/parameter-count = -507
		view/parameter-record-size = -508
		view/parameters-offset = -509
		view/parameters-ordinal = -510
		view/symbol-count = -511
		view/functions = (as byte-ptr! 512)
		view/function-count = -513
		view/function-record-size = -514
		view/functions-offset = -515
		view/functions-ordinal = -516
		view/locals = (as byte-ptr! 517)
		view/local-count = -518
		view/local-record-size = -519
		view/locals-offset = -520
		view/locals-ordinal = -521
		view/blocks = (as byte-ptr! 522)
		view/block-count = -523
		view/block-record-size = -524
		view/blocks-offset = -525
		view/blocks-ordinal = -526
		view/source-location-count = -527
	]
]

poison-outputs: func [
	strings [wire-string-table!]
	files [wire-file-source!]
	layout [wire-data-layout!]
	types [wire-type-layout!]
	view [wire-function-signature!]
][
	poison-strings strings
	poison-files files
	poison-layout layout
	poison-types types
	poison-view view
]

outputs-poisoned?: func [
	strings [wire-string-table!]
	files [wire-file-source!]
	layout [wire-data-layout!]
	types [wire-type-layout!]
	view [wire-function-signature!]
	return: [logic!]
][
	all [
		strings-poisoned? strings
		files-poisoned? files
		layout-poisoned? layout
		types-poisoned? types
		view-poisoned? view
	]
]

test-function-signature: func [
	name [c-string!]
	data [byte-ptr!]
	size expected-error expected-container expected-string expected-file
	expected-layout expected-type expected-offset expected-section [integer!]
	return: [integer!]
	/local result [wire-function-signature-result!]
		strings [wire-string-table!] files [wire-file-source!]
		layout [wire-data-layout!] types [wire-type-layout!]
		view [wire-function-signature!] actual [integer!]
][
	result: declare wire-function-signature-result!
	strings: declare wire-string-table!
	files: declare wire-file-source!
	layout: declare wire-data-layout!
	types: declare wire-type-layout!
	view: declare wire-function-signature!
	poison-outputs strings files layout types view
	actual: wire-function-signature-reader/verify
		data size result strings files layout types view
	if actual <> expected-error [
		print ["FAIL: " name " expected=" expected-error " actual=" actual lf]
		return 1
	]
	if result/error <> expected-error [
		print ["FAIL: " name " result/error=" result/error lf]
		return 1
	]
	if result/container-error <> expected-container [
		print ["FAIL: " name " container=" result/container-error lf]
		return 1
	]
	if result/string-error <> expected-string [
		print ["FAIL: " name " string=" result/string-error lf]
		return 1
	]
	if result/file-source-error <> expected-file [
		print ["FAIL: " name " file/source=" result/file-source-error lf]
		return 1
	]
	if result/data-layout-error <> expected-layout [
		print ["FAIL: " name " data-layout=" result/data-layout-error lf]
		return 1
	]
	if result/type-layout-error <> expected-type [
		print ["FAIL: " name " type-layout=" result/type-layout-error lf]
		return 1
	]
	if any [
		result/error-offset <> expected-offset
		result/error-section <> expected-section
	][
		print [
			"FAIL: " name
			" location=" result/error-offset ":" result/error-section
			" expected=" expected-offset ":" expected-section lf
		]
		return 1
	]
	if all [
		expected-error <> WIRE_FUNCTION_SIGNATURE_ERROR_SUCCESS
		not outputs-poisoned? strings files layout types view
	][
		print ["FAIL: " name " modified output views on failure" lf]
		return 1
	]
	0
]

failures: 0
}

foreach fixture valid-function-signatures [
	append output rejoin [
		{failures: failures + (test-function-signature "} form fixture/1 {" }
		"function-valid-" word-name fixture/1 " " length? fixture/2
		" " schema/WIRE_FUNCTION_SIGNATURE_ERROR_SUCCESS
		" " schema/WIRE_CONTAINER_ERROR_SUCCESS
		" " schema/WIRE_STRING_TABLE_ERROR_SUCCESS
		" " schema/WIRE_FILE_SOURCE_ERROR_SUCCESS
		" " schema/WIRE_DATA_LAYOUT_ERROR_SUCCESS
		" " schema/WIRE_TYPE_LAYOUT_ERROR_SUCCESS
		" 0 0)" newline
	]
]

foreach fixture malformed-function-signatures [
	append output rejoin [
		{failures: failures + (test-function-signature "} form fixture/1 {" }
		"function-invalid-" word-name fixture/1 " " length? fixture/10
		" " fixture/2 " " fixture/3 " " fixture/4 " " fixture/5
		" " fixture/6 " " fixture/7 " " fixture/8 " " fixture/9 ")" newline
	]
]

verified: function-signature-verifier/verify basic-function-message
append output rejoin [{

result: declare wire-function-signature-result!
strings: declare wire-string-table!
files: declare wire-file-source!
layout: declare wire-data-layout!
types: declare wire-type-layout!
view: declare wire-function-signature!
code: wire-function-signature-reader/verify
	function-valid-basic } length? basic-function-message {
	result strings files layout types view
if code <> WIRE_FUNCTION_SIGNATURE_ERROR_SUCCESS [failures: failures + 1]
if any [
	strings/record-count <> 6
	files/file-count <> 0
	files/source-count <> 0
	layout/pointer-size <> 8
	types/type-count <> 5
	types/type-record-size <> WIRE_RSIR_TYPE_SIZE
	view/signature-count <> 1
	view/signature-record-size <> WIRE_RSIR_SIGNATURE_SIZE
	view/signatures-offset <> } verified/view/signatures-offset {
	view/signatures-ordinal <> } verified/view/signatures-ordinal {
	view/parameter-count <> 1
	view/parameter-record-size <> WIRE_RSIR_PARAMETER_SIZE
	view/parameters-offset <> } verified/view/parameters-offset {
	view/parameters-ordinal <> } verified/view/parameters-ordinal {
	view/symbol-count <> 1
	view/function-count <> 1
	view/function-record-size <> WIRE_RSIR_FUNCTION_SIZE
	view/functions-offset <> } verified/view/functions-offset {
	view/functions-ordinal <> } verified/view/functions-ordinal {
	view/local-count <> 1
	view/local-record-size <> WIRE_RSIR_LOCAL_SIZE
	view/locals-offset <> } verified/view/locals-offset {
	view/locals-ordinal <> } verified/view/locals-ordinal {
	view/block-count <> 1
	view/block-record-size <> WIRE_RSIR_BLOCK_SIZE
	view/blocks-offset <> } verified/view/blocks-offset {
	view/blocks-ordinal <> } verified/view/blocks-ordinal {
	view/source-location-count <> 0
][
	print ["FAIL: verified function/signature view changed" lf]
	failures: failures + 1
]
if any [
	(wire-container-reader/read-i31 view/signatures WIRE_RSIR_SIGNATURE_RETURN_TYPE_OFFSET) <> 2
	(wire-container-reader/read-i31 view/parameters WIRE_RSIR_PARAMETER_DEBUG_TYPE_CODE_OFFSET)
		<> WIRE_DEBUG_TYPE_CODE_INTEGER
	(wire-container-reader/read-i31 view/functions WIRE_RSIR_FUNCTION_ENTRY_BLOCK_OFFSET) <> 1
	(wire-container-reader/read-i31 view/locals WIRE_RSIR_LOCAL_KIND_OFFSET)
		<> WIRE_LOCAL_KIND_ARGUMENT
	(wire-container-reader/read-i31 view/blocks WIRE_RSIR_BLOCK_FUNCTION_OFFSET) <> 1
][failures: failures + 1]

poison-outputs strings files layout types view
code: wire-function-signature-reader/verify
	(as byte-ptr! 0) } length? basic-function-message { result strings files layout types view
if code <> WIRE_FUNCTION_SIGNATURE_ERROR_INVALID_ARGUMENTS [failures: failures + 1]
if any [
	result/error <> WIRE_FUNCTION_SIGNATURE_ERROR_INVALID_ARGUMENTS
	result/container-error <> WIRE_CONTAINER_ERROR_SUCCESS
	result/string-error <> WIRE_STRING_TABLE_ERROR_SUCCESS
	result/file-source-error <> WIRE_FILE_SOURCE_ERROR_SUCCESS
	result/data-layout-error <> WIRE_DATA_LAYOUT_ERROR_SUCCESS
	result/type-layout-error <> WIRE_TYPE_LAYOUT_ERROR_SUCCESS
	result/error-offset <> 0
	result/error-section <> 0
][failures: failures + 1]
unless outputs-poisoned? strings files layout types view [failures: failures + 1]

code: wire-function-signature-reader/verify
	function-valid-basic -1 result strings files layout types view
if code <> WIRE_FUNCTION_SIGNATURE_ERROR_INVALID_ARGUMENTS [failures: failures + 1]
unless outputs-poisoned? strings files layout types view [failures: failures + 1]

code: wire-function-signature-reader/verify function-valid-basic
	} length? basic-function-message { result (as wire-string-table! 0) files layout types view
if code <> WIRE_FUNCTION_SIGNATURE_ERROR_INVALID_ARGUMENTS [failures: failures + 1]
code: wire-function-signature-reader/verify function-valid-basic
	} length? basic-function-message { result strings (as wire-file-source! 0) layout types view
if code <> WIRE_FUNCTION_SIGNATURE_ERROR_INVALID_ARGUMENTS [failures: failures + 1]
code: wire-function-signature-reader/verify function-valid-basic
	} length? basic-function-message { result strings files (as wire-data-layout! 0) types view
if code <> WIRE_FUNCTION_SIGNATURE_ERROR_INVALID_ARGUMENTS [failures: failures + 1]
code: wire-function-signature-reader/verify function-valid-basic
	} length? basic-function-message { result strings files layout (as wire-type-layout! 0) view
if code <> WIRE_FUNCTION_SIGNATURE_ERROR_INVALID_ARGUMENTS [failures: failures + 1]
code: wire-function-signature-reader/verify function-valid-basic
	} length? basic-function-message { result strings files layout types
	(as wire-function-signature! 0)
if code <> WIRE_FUNCTION_SIGNATURE_ERROR_INVALID_ARGUMENTS [failures: failures + 1]
code: wire-function-signature-reader/verify function-valid-basic
	} length? basic-function-message { (as wire-function-signature-result! 0)
	strings files layout types view
if code <> WIRE_FUNCTION_SIGNATURE_ERROR_INVALID_ARGUMENTS [failures: failures + 1]

either failures = 0 [
	print ["PASS: Red/System RSIR function/signature semantics" lf]
][
	print ["FAIL: Red/System RSIR function/signature semantics failures=" failures lf]
]
quit failures
}]

target: %tests/wire-function-signature-reds-test.reds
write target to binary! output
print [
	"Generated" target
	"with" length? valid-function-signatures "valid and"
	length? malformed-function-signatures "malformed fixtures"
]
