Red [
	Title: "Generate Red/System RSIR explicit-stack fixture tests"
]

generating-wire-stack-fixtures?: true
do %tests/wire-stack-test.red

word-name: func [value [word!]][lowercase copy form value]

append-binary: func [output [string!] prefix [string!] name [word!] data [binary!]][
	append output rejoin [prefix word-name name ": " mold/flat data newline]
]

output: make string! 16'777'216
source-bytes: make binary! 8'388'608
foreach source-file [
	%tests/wire-stack-test.red
	%tests/wire-exception-test.red
	%tests/wire-subroutine-test.red
	%tests/wire-call-abi-test.red
	%tests/wire-control-flow-test.red
	%tests/wire-scalar-operation-test.red
	%tests/wire-constant-initializer-test.red
	%tests/wire-symbol-linkage-test.red
	%tests/wire-function-signature-test.red
	%tests/wire-module-lifecycle-test.red
	%tests/wire-type-layout-test.red
	%tests/wire-data-layout-test.red
	%tests/wire-file-source-test.red
	%tests/wire-string-table-test.red
	%tests/wire-container-test.red
	%generate-wire-subroutine-fixtures.red
	%generate-wire-exception-fixtures.red
	%generate-wire-stack-fixtures.red
][append source-bytes read source-file]
append source-bytes to binary! mold schema/WIRE_SCHEMA_FINGERPRINT
source-digest: enbase/base checksum source-bytes 'SHA256 16

append output {Red/System [
	Title: "Generated RSIR explicit-stack cross-language tests"
]

; Generated by tools/self_hosting/generate-wire-stack-fixtures.red.
; Do not edit. Error codes and locations are frozen by the Red semantic corpus.
}
append output rejoin ["; Fixture source SHA256: " source-digest newline]
append output {
#include %../../../system/codegen/wire-stack.reds

}

foreach fixture valid-stacks [
	append-binary output "stack-valid-" fixture/1 fixture/2
]
foreach fixture malformed-stacks [
	append-binary output "stack-invalid-" fixture/1 fixture/19
]

workspace-fixture: make binary! 513
append/dup workspace-fixture 0 513
append output rejoin ["stack-workspace: " mold/flat workspace-fixture newline newline]

append output {
poison-memory: func [
	memory [byte-ptr!]
	size [integer!]
	/local cursor [byte-ptr!] remaining [integer!]
][
	cursor: memory
	remaining: size
	while [remaining > 0][
		cursor/1: as byte! 165
		cursor: cursor + 1
		remaining: remaining - 1
	]
]

memory-poisoned?: func [
	memory [byte-ptr!]
	size [integer!]
	return: [logic!]
	/local cursor [byte-ptr!] remaining [integer!]
][
	cursor: memory
	remaining: size
	while [remaining > 0][
		if cursor/1 <> as byte! 165 [return false]
		cursor: cursor + 1
		remaining: remaining - 1
	]
	true
]

poison-outputs: func [
	strings [wire-string-table!]
	files [wire-file-source!]
	layout [wire-data-layout!]
	types [wire-type-layout!]
	functions [wire-function-signature!]
	modules [wire-module-lifecycle!]
	symbols [wire-symbol-linkage!]
	constants [wire-constant-initializer!]
	scalar [wire-scalar-operation!]
	control [wire-control-flow!]
	calls [wire-call-abi!]
	subroutines [wire-subroutine!]
	exceptions [wire-exception!]
][
	poison-memory as byte-ptr! strings size? wire-string-table!
	poison-memory as byte-ptr! files size? wire-file-source!
	poison-memory as byte-ptr! layout size? wire-data-layout!
	poison-memory as byte-ptr! types size? wire-type-layout!
	poison-memory as byte-ptr! functions size? wire-function-signature!
	poison-memory as byte-ptr! modules size? wire-module-lifecycle!
	poison-memory as byte-ptr! symbols size? wire-symbol-linkage!
	poison-memory as byte-ptr! constants size? wire-constant-initializer!
	poison-memory as byte-ptr! scalar size? wire-scalar-operation!
	poison-memory as byte-ptr! control size? wire-control-flow!
	poison-memory as byte-ptr! calls size? wire-call-abi!
	poison-memory as byte-ptr! subroutines size? wire-subroutine!
	poison-memory as byte-ptr! exceptions size? wire-exception!
]

outputs-poisoned?: func [
	strings [wire-string-table!]
	files [wire-file-source!]
	layout [wire-data-layout!]
	types [wire-type-layout!]
	functions [wire-function-signature!]
	modules [wire-module-lifecycle!]
	symbols [wire-symbol-linkage!]
	constants [wire-constant-initializer!]
	scalar [wire-scalar-operation!]
	control [wire-control-flow!]
	calls [wire-call-abi!]
	subroutines [wire-subroutine!]
	exceptions [wire-exception!]
	return: [logic!]
][
	all [
		memory-poisoned? as byte-ptr! strings size? wire-string-table!
		memory-poisoned? as byte-ptr! files size? wire-file-source!
		memory-poisoned? as byte-ptr! layout size? wire-data-layout!
		memory-poisoned? as byte-ptr! types size? wire-type-layout!
		memory-poisoned? as byte-ptr! functions size? wire-function-signature!
		memory-poisoned? as byte-ptr! modules size? wire-module-lifecycle!
		memory-poisoned? as byte-ptr! symbols size? wire-symbol-linkage!
		memory-poisoned? as byte-ptr! constants size? wire-constant-initializer!
		memory-poisoned? as byte-ptr! scalar size? wire-scalar-operation!
		memory-poisoned? as byte-ptr! control size? wire-control-flow!
		memory-poisoned? as byte-ptr! calls size? wire-call-abi!
		memory-poisoned? as byte-ptr! subroutines size? wire-subroutine!
		memory-poisoned? as byte-ptr! exceptions size? wire-exception!
	]
]

test-stack: func [
	name [c-string!]
	data [byte-ptr!]
	size [integer!]
	workspace [byte-ptr!]
	workspace-size [integer!]
	expected-error expected-exception expected-subroutine expected-call
	expected-control expected-scalar expected-container expected-string expected-file
	expected-layout expected-type expected-function expected-module expected-symbol
	expected-constant expected-offset expected-section expected-functions expected-blocks
	expected-instructions expected-subroutines expected-regions [integer!]
	return: [integer!]
	/local result [wire-stack-result!]
		strings [wire-string-table!]
		files [wire-file-source!]
		layout [wire-data-layout!]
		types [wire-type-layout!]
		functions [wire-function-signature!]
		modules [wire-module-lifecycle!]
		symbols [wire-symbol-linkage!]
		constants [wire-constant-initializer!]
		scalar [wire-scalar-operation!]
		control [wire-control-flow!]
		calls [wire-call-abi!]
		subroutines [wire-subroutine!]
		exceptions [wire-exception!]
		actual [integer!]
][
	result: declare wire-stack-result!
	strings: declare wire-string-table!
	files: declare wire-file-source!
	layout: declare wire-data-layout!
	types: declare wire-type-layout!
	functions: declare wire-function-signature!
	modules: declare wire-module-lifecycle!
	symbols: declare wire-symbol-linkage!
	constants: declare wire-constant-initializer!
	scalar: declare wire-scalar-operation!
	control: declare wire-control-flow!
	calls: declare wire-call-abi!
	subroutines: declare wire-subroutine!
	exceptions: declare wire-exception!
	poison-outputs strings files layout types functions modules symbols constants
		scalar control calls subroutines exceptions
	actual: wire-stack-reader/verify data size workspace workspace-size result
		strings files layout types functions modules symbols constants scalar control calls
		subroutines exceptions
	if actual <> expected-error [
		print ["FAIL: " name " expected=" expected-error " actual=" actual lf]
		return 1
	]
	if result/error <> expected-error [return 1]
	if result/exception-error <> expected-exception [
		print ["FAIL: " name " exception=" result/exception-error lf]
		return 1
	]
	if result/subroutine-error <> expected-subroutine [return 1]
	if result/call-abi-error <> expected-call [return 1]
	if result/control-flow-error <> expected-control [return 1]
	if result/scalar-operation-error <> expected-scalar [return 1]
	if result/container-error <> expected-container [return 1]
	if result/string-error <> expected-string [return 1]
	if result/file-source-error <> expected-file [return 1]
	if result/data-layout-error <> expected-layout [return 1]
	if result/type-layout-error <> expected-type [return 1]
	if result/function-signature-error <> expected-function [return 1]
	if result/module-lifecycle-error <> expected-module [return 1]
	if result/symbol-linkage-error <> expected-symbol [return 1]
	if result/constant-initializer-error <> expected-constant [return 1]
	if any [
		result/error-offset <> expected-offset
		result/error-section <> expected-section
	][
		print [
			"FAIL: " name " location=" result/error-offset ":" result/error-section
			" expected=" expected-offset ":" expected-section lf
		]
		return 1
	]
	if all [
		expected-error <> WIRE_STACK_ERROR_SUCCESS
		not outputs-poisoned? strings files layout types functions modules symbols
			constants scalar control calls subroutines exceptions
	][
		print ["FAIL: " name " modified output views on failure" lf]
		return 1
	]
	if all [
		expected-error = WIRE_STACK_ERROR_SUCCESS
		any [
			functions/function-count <> expected-functions
			functions/block-count <> expected-blocks
			scalar/instruction-count <> expected-instructions
			subroutines/subroutine-count <> expected-subroutines
			exceptions/region-count <> expected-regions
		]
	][
		print ["FAIL: " name " published view counts changed" lf]
		return 1
	]
	0
]

failures: 0
}

foreach fixture valid-stacks [
	verified: stack-verifier/verify fixture/2
	append output rejoin [
		{failures: failures + (test-stack "} form fixture/1 {" }
		"stack-valid-" word-name fixture/1 " " length? fixture/2
		" stack-workspace 513"
		" " schema/WIRE_STACK_ERROR_SUCCESS
		" " schema/WIRE_EXCEPTION_ERROR_SUCCESS
		" " schema/WIRE_SUBROUTINE_ERROR_SUCCESS
		" " schema/WIRE_CALL_ABI_ERROR_SUCCESS
		" " schema/WIRE_CONTROL_FLOW_ERROR_SUCCESS
		" " schema/WIRE_SCALAR_OPERATION_ERROR_SUCCESS
		" " schema/WIRE_CONTAINER_ERROR_SUCCESS
		" " schema/WIRE_STRING_TABLE_ERROR_SUCCESS
		" " schema/WIRE_FILE_SOURCE_ERROR_SUCCESS
		" " schema/WIRE_DATA_LAYOUT_ERROR_SUCCESS
		" " schema/WIRE_TYPE_LAYOUT_ERROR_SUCCESS
		" " schema/WIRE_FUNCTION_SIGNATURE_ERROR_SUCCESS
		" " schema/WIRE_MODULE_LIFECYCLE_ERROR_SUCCESS
		" " schema/WIRE_SYMBOL_LINKAGE_ERROR_SUCCESS
		" " schema/WIRE_CONSTANT_INITIALIZER_ERROR_SUCCESS
		" 0 0 " verified/functions/function-count
		" " verified/functions/block-count
		" " verified/scalar-view/instruction-count
		" " verified/subroutine-view/subroutine-count
		" " verified/exception-view/region-count ")" newline
	]
]

foreach fixture malformed-stacks [
	append output rejoin [
		{failures: failures + (test-stack "} form fixture/1 {" }
		"stack-invalid-" word-name fixture/1 " " length? fixture/19
		" stack-workspace 513"
		" " fixture/2 " " fixture/3 " " fixture/4 " " fixture/5
		" " fixture/6 " " fixture/7 " " fixture/8 " " fixture/9
		" " fixture/10 " " fixture/11 " " fixture/12 " " fixture/13
		" " fixture/14 " " fixture/15 " " fixture/16 " " fixture/17
		" " fixture/18 " -1 -1 -1 -1 -1)" newline
	]
]

balanced-verified: stack-verifier/verify balanced-stack-message
append output rejoin [{

; One block needs exactly 24 bytes. The byte reader/writer must also accept an
; unaligned caller-owned workspace.
failures: failures + (test-stack "EXACT-WORKSPACE" stack-valid-balanced
	} length? balanced-stack-message { stack-workspace 24
	WIRE_STACK_ERROR_SUCCESS WIRE_EXCEPTION_ERROR_SUCCESS
	WIRE_SUBROUTINE_ERROR_SUCCESS WIRE_CALL_ABI_ERROR_SUCCESS
	WIRE_CONTROL_FLOW_ERROR_SUCCESS WIRE_SCALAR_OPERATION_ERROR_SUCCESS
	WIRE_CONTAINER_ERROR_SUCCESS WIRE_STRING_TABLE_ERROR_SUCCESS
	WIRE_FILE_SOURCE_ERROR_SUCCESS WIRE_DATA_LAYOUT_ERROR_SUCCESS
	WIRE_TYPE_LAYOUT_ERROR_SUCCESS WIRE_FUNCTION_SIGNATURE_ERROR_SUCCESS
	WIRE_MODULE_LIFECYCLE_ERROR_SUCCESS WIRE_SYMBOL_LINKAGE_ERROR_SUCCESS
	WIRE_CONSTANT_INITIALIZER_ERROR_SUCCESS 0 0 }
	balanced-verified/functions/function-count " "
	balanced-verified/functions/block-count " "
	balanced-verified/scalar-view/instruction-count " "
	balanced-verified/subroutine-view/subroutine-count " "
	balanced-verified/exception-view/region-count {)
failures: failures + (test-stack "UNALIGNED-WORKSPACE" stack-valid-balanced
	} length? balanced-stack-message { (stack-workspace + 1) 24
	WIRE_STACK_ERROR_SUCCESS WIRE_EXCEPTION_ERROR_SUCCESS
	WIRE_SUBROUTINE_ERROR_SUCCESS WIRE_CALL_ABI_ERROR_SUCCESS
	WIRE_CONTROL_FLOW_ERROR_SUCCESS WIRE_SCALAR_OPERATION_ERROR_SUCCESS
	WIRE_CONTAINER_ERROR_SUCCESS WIRE_STRING_TABLE_ERROR_SUCCESS
	WIRE_FILE_SOURCE_ERROR_SUCCESS WIRE_DATA_LAYOUT_ERROR_SUCCESS
	WIRE_TYPE_LAYOUT_ERROR_SUCCESS WIRE_FUNCTION_SIGNATURE_ERROR_SUCCESS
	WIRE_MODULE_LIFECYCLE_ERROR_SUCCESS WIRE_SYMBOL_LINKAGE_ERROR_SUCCESS
	WIRE_CONSTANT_INITIALIZER_ERROR_SUCCESS 0 0 }
	balanced-verified/functions/function-count " "
	balanced-verified/functions/block-count " "
	balanced-verified/scalar-view/instruction-count " "
	balanced-verified/subroutine-view/subroutine-count " "
	balanced-verified/exception-view/region-count {)
failures: failures + (test-stack "INSUFFICIENT-WORKSPACE" stack-valid-balanced
	} length? balanced-stack-message { stack-workspace 23
	WIRE_STACK_ERROR_INSUFFICIENT_WORKSPACE WIRE_EXCEPTION_ERROR_SUCCESS
	WIRE_SUBROUTINE_ERROR_SUCCESS WIRE_CALL_ABI_ERROR_SUCCESS
	WIRE_CONTROL_FLOW_ERROR_SUCCESS WIRE_SCALAR_OPERATION_ERROR_SUCCESS
	WIRE_CONTAINER_ERROR_SUCCESS WIRE_STRING_TABLE_ERROR_SUCCESS
	WIRE_FILE_SOURCE_ERROR_SUCCESS WIRE_DATA_LAYOUT_ERROR_SUCCESS
	WIRE_TYPE_LAYOUT_ERROR_SUCCESS WIRE_FUNCTION_SIGNATURE_ERROR_SUCCESS
	WIRE_MODULE_LIFECYCLE_ERROR_SUCCESS WIRE_SYMBOL_LINKAGE_ERROR_SUCCESS
	WIRE_CONSTANT_INITIALIZER_ERROR_SUCCESS 0 0 -1 -1 -1 -1 -1)

failures: failures + (test-stack "NULL-DATA" (as byte-ptr! 0)
	} length? balanced-stack-message { stack-workspace 513
	WIRE_STACK_ERROR_INVALID_ARGUMENTS WIRE_EXCEPTION_ERROR_SUCCESS
	WIRE_SUBROUTINE_ERROR_SUCCESS WIRE_CALL_ABI_ERROR_SUCCESS
	WIRE_CONTROL_FLOW_ERROR_SUCCESS WIRE_SCALAR_OPERATION_ERROR_SUCCESS
	WIRE_CONTAINER_ERROR_SUCCESS WIRE_STRING_TABLE_ERROR_SUCCESS
	WIRE_FILE_SOURCE_ERROR_SUCCESS WIRE_DATA_LAYOUT_ERROR_SUCCESS
	WIRE_TYPE_LAYOUT_ERROR_SUCCESS WIRE_FUNCTION_SIGNATURE_ERROR_SUCCESS
	WIRE_MODULE_LIFECYCLE_ERROR_SUCCESS WIRE_SYMBOL_LINKAGE_ERROR_SUCCESS
	WIRE_CONSTANT_INITIALIZER_ERROR_SUCCESS 0 0 -1 -1 -1 -1 -1)
failures: failures + (test-stack "NEGATIVE-SIZE" stack-valid-balanced -1
	stack-workspace 513 WIRE_STACK_ERROR_INVALID_ARGUMENTS
	WIRE_EXCEPTION_ERROR_SUCCESS WIRE_SUBROUTINE_ERROR_SUCCESS
	WIRE_CALL_ABI_ERROR_SUCCESS WIRE_CONTROL_FLOW_ERROR_SUCCESS
	WIRE_SCALAR_OPERATION_ERROR_SUCCESS WIRE_CONTAINER_ERROR_SUCCESS
	WIRE_STRING_TABLE_ERROR_SUCCESS WIRE_FILE_SOURCE_ERROR_SUCCESS
	WIRE_DATA_LAYOUT_ERROR_SUCCESS WIRE_TYPE_LAYOUT_ERROR_SUCCESS
	WIRE_FUNCTION_SIGNATURE_ERROR_SUCCESS WIRE_MODULE_LIFECYCLE_ERROR_SUCCESS
	WIRE_SYMBOL_LINKAGE_ERROR_SUCCESS WIRE_CONSTANT_INITIALIZER_ERROR_SUCCESS
	0 0 -1 -1 -1 -1 -1)
failures: failures + (test-stack "NULL-WORKSPACE" stack-valid-balanced
	} length? balanced-stack-message { (as byte-ptr! 0) 513
	WIRE_STACK_ERROR_INVALID_ARGUMENTS WIRE_EXCEPTION_ERROR_SUCCESS
	WIRE_SUBROUTINE_ERROR_SUCCESS WIRE_CALL_ABI_ERROR_SUCCESS
	WIRE_CONTROL_FLOW_ERROR_SUCCESS WIRE_SCALAR_OPERATION_ERROR_SUCCESS
	WIRE_CONTAINER_ERROR_SUCCESS WIRE_STRING_TABLE_ERROR_SUCCESS
	WIRE_FILE_SOURCE_ERROR_SUCCESS WIRE_DATA_LAYOUT_ERROR_SUCCESS
	WIRE_TYPE_LAYOUT_ERROR_SUCCESS WIRE_FUNCTION_SIGNATURE_ERROR_SUCCESS
	WIRE_MODULE_LIFECYCLE_ERROR_SUCCESS WIRE_SYMBOL_LINKAGE_ERROR_SUCCESS
	WIRE_CONSTANT_INITIALIZER_ERROR_SUCCESS 0 0 -1 -1 -1 -1 -1)
failures: failures + (test-stack "NEGATIVE-WORKSPACE" stack-valid-balanced
	} length? balanced-stack-message { stack-workspace -1
	WIRE_STACK_ERROR_INVALID_ARGUMENTS WIRE_EXCEPTION_ERROR_SUCCESS
	WIRE_SUBROUTINE_ERROR_SUCCESS WIRE_CALL_ABI_ERROR_SUCCESS
	WIRE_CONTROL_FLOW_ERROR_SUCCESS WIRE_SCALAR_OPERATION_ERROR_SUCCESS
	WIRE_CONTAINER_ERROR_SUCCESS WIRE_STRING_TABLE_ERROR_SUCCESS
	WIRE_FILE_SOURCE_ERROR_SUCCESS WIRE_DATA_LAYOUT_ERROR_SUCCESS
	WIRE_TYPE_LAYOUT_ERROR_SUCCESS WIRE_FUNCTION_SIGNATURE_ERROR_SUCCESS
	WIRE_MODULE_LIFECYCLE_ERROR_SUCCESS WIRE_SYMBOL_LINKAGE_ERROR_SUCCESS
	WIRE_CONSTANT_INITIALIZER_ERROR_SUCCESS 0 0 -1 -1 -1 -1 -1)

result: declare wire-stack-result!
strings: declare wire-string-table!
files: declare wire-file-source!
layout: declare wire-data-layout!
types: declare wire-type-layout!
functions: declare wire-function-signature!
modules: declare wire-module-lifecycle!
symbols: declare wire-symbol-linkage!
constants: declare wire-constant-initializer!
scalar: declare wire-scalar-operation!
control: declare wire-control-flow!
calls: declare wire-call-abi!
subroutines: declare wire-subroutine!
exceptions: declare wire-exception!
poison-outputs strings files layout types functions modules symbols constants
	scalar control calls subroutines exceptions
code: wire-stack-reader/verify stack-valid-balanced }
	length? balanced-stack-message { stack-workspace 513
	(as wire-stack-result! 0) strings files layout types functions modules symbols
	constants scalar control calls subroutines exceptions
if code <> WIRE_STACK_ERROR_INVALID_ARGUMENTS [failures: failures + 1]
unless outputs-poisoned? strings files layout types functions modules symbols constants
	scalar control calls subroutines exceptions
[
	failures: failures + 1
]
}]

foreach [type-name before after] [
	wire-string-table! "result "
		" files layout types functions modules symbols constants scalar control calls subroutines exceptions"
	wire-file-source! "result strings "
		" layout types functions modules symbols constants scalar control calls subroutines exceptions"
	wire-data-layout! "result strings files "
		" types functions modules symbols constants scalar control calls subroutines exceptions"
	wire-type-layout! "result strings files layout "
		" functions modules symbols constants scalar control calls subroutines exceptions"
	wire-function-signature! "result strings files layout types "
		" modules symbols constants scalar control calls subroutines exceptions"
	wire-module-lifecycle! "result strings files layout types functions "
		" symbols constants scalar control calls subroutines exceptions"
	wire-symbol-linkage! "result strings files layout types functions modules "
		" constants scalar control calls subroutines exceptions"
	wire-constant-initializer! "result strings files layout types functions modules symbols "
		" scalar control calls subroutines exceptions"
	wire-scalar-operation! "result strings files layout types functions modules symbols constants "
		" control calls subroutines exceptions"
	wire-control-flow! "result strings files layout types functions modules symbols constants scalar "
		" calls subroutines exceptions"
	wire-call-abi! "result strings files layout types functions modules symbols constants scalar control "
		" subroutines exceptions"
	wire-subroutine! "result strings files layout types functions modules symbols constants scalar control calls "
		" exceptions"
	wire-exception! "result strings files layout types functions modules symbols constants scalar control calls subroutines "
		""
][
	append output rejoin [
		"code: wire-stack-reader/verify stack-valid-balanced "
		length? balanced-stack-message " stack-workspace 513 "
		before "(as " type-name " 0)" after newline
		"if code <> WIRE_STACK_ERROR_INVALID_ARGUMENTS "
		"[failures: failures + 1]" newline
	]
]

append output {

either failures = 0 [
	print ["PASS: Red/System RSIR explicit-stack semantics" lf]
][
	print ["FAIL: Red/System RSIR explicit-stack semantics failures=" failures lf]
]
quit failures
}

target: %tests/wire-stack-reds-test.reds
write target to binary! output
print [
	"Generated" target "with" length? valid-stacks "valid and"
	length? malformed-stacks "malformed fixtures"
]
