Red [
	Title: "Generate Red/System RSIR exception fixture tests"
]

generating-wire-exception-fixtures?: true
do %tests/wire-exception-test.red

word-name: func [value [word!]][lowercase copy form value]

append-binary: func [output [string!] prefix [string!] name [word!] data [binary!]][
	append output rejoin [prefix word-name name ": " mold/flat data newline]
]

output: make string! 16'777'216
source-bytes: make binary! 8'388'608
foreach source-file [
	%tests/wire-exception-test.red
	%tests/wire-call-abi-test.red
	%tests/wire-control-flow-test.red
	%tests/wire-scalar-operation-test.red
	%tests/wire-constant-initializer-test.red
	%tests/wire-symbol-linkage-test.red
	%tests/wire-function-signature-test.red
	%tests/wire-module-lifecycle-test.red
	%tests/wire-type-layout-test.red
	%tests/wire-data-layout-test.red
	%tests/wire-file-source-test.red
	%tests/wire-string-table-test.red
	%tests/wire-container-test.red
	%generate-wire-exception-fixtures.red
][append source-bytes read source-file]
append source-bytes to binary! mold schema/WIRE_SCHEMA_FINGERPRINT
source-digest: enbase/base checksum source-bytes 'SHA256 16

append output {Red/System [
	Title: "Generated RSIR exception cross-language tests"
]

; Generated by tools/self_hosting/generate-wire-exception-fixtures.red.
; Do not edit. Error codes and locations are frozen by the Red semantic corpus.
}
append output rejoin ["; Fixture source SHA256: " source-digest newline]
append output {
#include %../../../system/codegen/wire-exception.reds

}

foreach fixture valid-exceptions [
	append-binary output "exception-valid-" fixture/1 fixture/2
]
foreach fixture malformed-exceptions [
	append-binary output "exception-invalid-" fixture/1 fixture/17
]

append output {
exception-workspace: #{
	00000000000000000000000000000000
	00000000000000000000000000000000
	00000000000000000000000000000000
	00000000000000000000000000000000
}
exception-small-workspace: #{00}

poison-memory: func [
	memory [byte-ptr!]
	size [integer!]
	/local cursor [byte-ptr!] remaining [integer!]
][
	cursor: memory
	remaining: size
	while [remaining > 0][
		cursor/1: as byte! 165
		cursor: cursor + 1
		remaining: remaining - 1
	]
]

memory-poisoned?: func [
	memory [byte-ptr!]
	size [integer!]
	return: [logic!]
	/local cursor [byte-ptr!] remaining [integer!]
][
	cursor: memory
	remaining: size
	while [remaining > 0][
		if cursor/1 <> as byte! 165 [return false]
		cursor: cursor + 1
		remaining: remaining - 1
	]
	true
]

poison-outputs: func [
	strings [wire-string-table!]
	files [wire-file-source!]
	layout [wire-data-layout!]
	types [wire-type-layout!]
	functions [wire-function-signature!]
	modules [wire-module-lifecycle!]
	symbols [wire-symbol-linkage!]
	constants [wire-constant-initializer!]
	scalar [wire-scalar-operation!]
	control [wire-control-flow!]
	calls [wire-call-abi!]
	exceptions [wire-exception!]
][
	poison-memory as byte-ptr! strings size? wire-string-table!
	poison-memory as byte-ptr! files size? wire-file-source!
	poison-memory as byte-ptr! layout size? wire-data-layout!
	poison-memory as byte-ptr! types size? wire-type-layout!
	poison-memory as byte-ptr! functions size? wire-function-signature!
	poison-memory as byte-ptr! modules size? wire-module-lifecycle!
	poison-memory as byte-ptr! symbols size? wire-symbol-linkage!
	poison-memory as byte-ptr! constants size? wire-constant-initializer!
	poison-memory as byte-ptr! scalar size? wire-scalar-operation!
	poison-memory as byte-ptr! control size? wire-control-flow!
	poison-memory as byte-ptr! calls size? wire-call-abi!
	poison-memory as byte-ptr! exceptions size? wire-exception!
]

outputs-poisoned?: func [
	strings [wire-string-table!]
	files [wire-file-source!]
	layout [wire-data-layout!]
	types [wire-type-layout!]
	functions [wire-function-signature!]
	modules [wire-module-lifecycle!]
	symbols [wire-symbol-linkage!]
	constants [wire-constant-initializer!]
	scalar [wire-scalar-operation!]
	control [wire-control-flow!]
	calls [wire-call-abi!]
	exceptions [wire-exception!]
	return: [logic!]
][
	all [
		memory-poisoned? as byte-ptr! strings size? wire-string-table!
		memory-poisoned? as byte-ptr! files size? wire-file-source!
		memory-poisoned? as byte-ptr! layout size? wire-data-layout!
		memory-poisoned? as byte-ptr! types size? wire-type-layout!
		memory-poisoned? as byte-ptr! functions size? wire-function-signature!
		memory-poisoned? as byte-ptr! modules size? wire-module-lifecycle!
		memory-poisoned? as byte-ptr! symbols size? wire-symbol-linkage!
		memory-poisoned? as byte-ptr! constants size? wire-constant-initializer!
		memory-poisoned? as byte-ptr! scalar size? wire-scalar-operation!
		memory-poisoned? as byte-ptr! control size? wire-control-flow!
		memory-poisoned? as byte-ptr! calls size? wire-call-abi!
		memory-poisoned? as byte-ptr! exceptions size? wire-exception!
	]
]

test-exception: func [
	name [c-string!]
	data [byte-ptr!]
	size [integer!]
	workspace [byte-ptr!]
	workspace-size [integer!]
	expected-error expected-call expected-control expected-scalar expected-container
	expected-string expected-file expected-layout expected-type expected-function
	expected-module expected-symbol expected-constant expected-offset expected-section
	expected-region-count expected-member-count [integer!]
	return: [integer!]
	/local result [wire-exception-result!]
		strings [wire-string-table!]
		files [wire-file-source!]
		layout [wire-data-layout!]
		types [wire-type-layout!]
		functions [wire-function-signature!]
		modules [wire-module-lifecycle!]
		symbols [wire-symbol-linkage!]
		constants [wire-constant-initializer!]
		scalar [wire-scalar-operation!]
		control [wire-control-flow!]
		calls [wire-call-abi!]
		exceptions [wire-exception!]
		actual [integer!]
][
	result: declare wire-exception-result!
	strings: declare wire-string-table!
	files: declare wire-file-source!
	layout: declare wire-data-layout!
	types: declare wire-type-layout!
	functions: declare wire-function-signature!
	modules: declare wire-module-lifecycle!
	symbols: declare wire-symbol-linkage!
	constants: declare wire-constant-initializer!
	scalar: declare wire-scalar-operation!
	control: declare wire-control-flow!
	calls: declare wire-call-abi!
	exceptions: declare wire-exception!
	poison-outputs strings files layout types functions modules symbols constants
		scalar control calls exceptions
	actual: wire-exception-reader/verify data size workspace workspace-size result
		strings files layout types functions modules symbols constants scalar control
		calls exceptions
	if actual <> expected-error [
		print ["FAIL: " name " expected=" expected-error " actual=" actual lf]
		return 1
	]
	if result/error <> expected-error [
		print ["FAIL: " name " result/error=" result/error lf]
		return 1
	]
	if result/call-abi-error <> expected-call [
		print ["FAIL: " name " call=" result/call-abi-error lf]
		return 1
	]
	if result/control-flow-error <> expected-control [return 1]
	if result/scalar-operation-error <> expected-scalar [return 1]
	if result/container-error <> expected-container [return 1]
	if result/string-error <> expected-string [return 1]
	if result/file-source-error <> expected-file [return 1]
	if result/data-layout-error <> expected-layout [return 1]
	if result/type-layout-error <> expected-type [return 1]
	if result/function-signature-error <> expected-function [return 1]
	if result/module-lifecycle-error <> expected-module [return 1]
	if result/symbol-linkage-error <> expected-symbol [return 1]
	if result/constant-initializer-error <> expected-constant [return 1]
	if any [
		result/error-offset <> expected-offset
		result/error-section <> expected-section
	][
		print [
			"FAIL: " name " location=" result/error-offset ":" result/error-section
			" expected=" expected-offset ":" expected-section lf
		]
		return 1
	]
	if all [
		expected-error <> WIRE_EXCEPTION_ERROR_SUCCESS
		not outputs-poisoned? strings files layout types functions modules symbols
			constants scalar control calls exceptions
	][
		print ["FAIL: " name " modified output views on failure" lf]
		return 1
	]
	if all [
		expected-error = WIRE_EXCEPTION_ERROR_SUCCESS
		any [
			exceptions/region-count <> expected-region-count
			exceptions/block-member-count <> expected-member-count
		]
	][
		print ["FAIL: " name " exception view counts changed" lf]
		return 1
	]
	0
]

failures: 0
}

foreach fixture valid-exceptions [
	verified-fixture: exception-verifier/verify fixture/2
	append output rejoin [
		{failures: failures + (test-exception "} form fixture/1 {" }
		"exception-valid-" word-name fixture/1 " " length? fixture/2
		" exception-workspace 64"
		" " schema/WIRE_EXCEPTION_ERROR_SUCCESS
		" " schema/WIRE_CALL_ABI_ERROR_SUCCESS
		" " schema/WIRE_CONTROL_FLOW_ERROR_SUCCESS
		" " schema/WIRE_SCALAR_OPERATION_ERROR_SUCCESS
		" " schema/WIRE_CONTAINER_ERROR_SUCCESS
		" " schema/WIRE_STRING_TABLE_ERROR_SUCCESS
		" " schema/WIRE_FILE_SOURCE_ERROR_SUCCESS
		" " schema/WIRE_DATA_LAYOUT_ERROR_SUCCESS
		" " schema/WIRE_TYPE_LAYOUT_ERROR_SUCCESS
		" " schema/WIRE_FUNCTION_SIGNATURE_ERROR_SUCCESS
		" " schema/WIRE_MODULE_LIFECYCLE_ERROR_SUCCESS
		" " schema/WIRE_SYMBOL_LINKAGE_ERROR_SUCCESS
		" " schema/WIRE_CONSTANT_INITIALIZER_ERROR_SUCCESS
		" 0 0 " verified-fixture/view/region-count
		" " verified-fixture/view/block-member-count ")" newline
	]
]

foreach fixture malformed-exceptions [
	append output rejoin [
		{failures: failures + (test-exception "} form fixture/1 {" }
		"exception-invalid-" word-name fixture/1 " " length? fixture/17
		" exception-workspace 64"
		" " fixture/2 " " fixture/3 " " fixture/4 " " fixture/5
		" " fixture/6 " " fixture/7 " " fixture/8 " " fixture/9
		" " fixture/10 " " fixture/11 " " fixture/12 " " fixture/13
		" " fixture/14 " " fixture/15 " " fixture/16 " -1 -1)" newline
	]
]

verified: exception-verifier/verify rich-exception-message
append output rejoin [{

result: declare wire-exception-result!
strings: declare wire-string-table!
files: declare wire-file-source!
layout: declare wire-data-layout!
types: declare wire-type-layout!
functions: declare wire-function-signature!
modules: declare wire-module-lifecycle!
symbols: declare wire-symbol-linkage!
constants: declare wire-constant-initializer!
scalar: declare wire-scalar-operation!
control: declare wire-control-flow!
calls: declare wire-call-abi!
exceptions: declare wire-exception!
code: wire-exception-reader/verify exception-valid-rich } length? rich-exception-message {
	exception-workspace 64 result strings files layout types functions modules symbols
	constants scalar control calls exceptions
if code <> WIRE_EXCEPTION_ERROR_SUCCESS [failures: failures + 1]
if any [
	functions/function-count <> } verified/functions/function-count {
	functions/block-count <> } verified/functions/block-count {
	scalar/value-count <> } verified/scalar-view/value-count {
	scalar/instruction-count <> } verified/scalar-view/instruction-count {
	scalar/operand-count <> } verified/scalar-view/operand-count {
	control/edge-count <> } verified/control-view/edge-count {
	calls/call-count <> } verified/call-view/call-count {
	exceptions/region-count <> } verified/view/region-count {
	exceptions/region-record-size <> WIRE_RSIR_EXCEPTION_REGION_SIZE
	exceptions/regions-offset <> } verified/view/regions-offset {
	exceptions/regions-ordinal <> } verified/view/regions-ordinal {
	exceptions/block-member-count <> } verified/view/block-member-count {
	exceptions/block-member-record-size <> WIRE_RSIR_EXCEPTION_BLOCK_SIZE
	exceptions/block-members-offset <> } verified/view/block-members-offset {
	exceptions/block-members-ordinal <> } verified/view/block-members-ordinal {
][
	print ["FAIL: verified exception view changed" lf]
	failures: failures + 1
]
if any [
	(wire-container-reader/read-i31 exceptions/regions
		WIRE_RSIR_EXCEPTION_REGION_FUNCTION_OFFSET) <> 1
	(wire-container-reader/read-i31 exceptions/regions
		WIRE_RSIR_EXCEPTION_REGION_HANDLER_BLOCK_OFFSET) <> 9
	(wire-container-reader/read-i31 exceptions/block-members
		WIRE_RSIR_EXCEPTION_BLOCK_BLOCK_OFFSET) <> 2
][failures: failures + 1]

failures: failures + (test-exception "NULL-DATA" (as byte-ptr! 0)
	} length? rich-exception-message { exception-workspace 64
	WIRE_EXCEPTION_ERROR_INVALID_ARGUMENTS WIRE_CALL_ABI_ERROR_SUCCESS
	WIRE_CONTROL_FLOW_ERROR_SUCCESS WIRE_SCALAR_OPERATION_ERROR_SUCCESS
	WIRE_CONTAINER_ERROR_SUCCESS WIRE_STRING_TABLE_ERROR_SUCCESS
	WIRE_FILE_SOURCE_ERROR_SUCCESS WIRE_DATA_LAYOUT_ERROR_SUCCESS
	WIRE_TYPE_LAYOUT_ERROR_SUCCESS WIRE_FUNCTION_SIGNATURE_ERROR_SUCCESS
	WIRE_MODULE_LIFECYCLE_ERROR_SUCCESS WIRE_SYMBOL_LINKAGE_ERROR_SUCCESS
	WIRE_CONSTANT_INITIALIZER_ERROR_SUCCESS 0 0 -1 -1)
failures: failures + (test-exception "NEGATIVE-SIZE" exception-valid-rich -1
	exception-workspace 64 WIRE_EXCEPTION_ERROR_INVALID_ARGUMENTS
	WIRE_CALL_ABI_ERROR_SUCCESS WIRE_CONTROL_FLOW_ERROR_SUCCESS
	WIRE_SCALAR_OPERATION_ERROR_SUCCESS WIRE_CONTAINER_ERROR_SUCCESS
	WIRE_STRING_TABLE_ERROR_SUCCESS WIRE_FILE_SOURCE_ERROR_SUCCESS
	WIRE_DATA_LAYOUT_ERROR_SUCCESS WIRE_TYPE_LAYOUT_ERROR_SUCCESS
	WIRE_FUNCTION_SIGNATURE_ERROR_SUCCESS WIRE_MODULE_LIFECYCLE_ERROR_SUCCESS
	WIRE_SYMBOL_LINKAGE_ERROR_SUCCESS WIRE_CONSTANT_INITIALIZER_ERROR_SUCCESS
	0 0 -1 -1)
failures: failures + (test-exception "NULL-WORKSPACE" exception-valid-rich
	} length? rich-exception-message { (as byte-ptr! 0) 64
	WIRE_EXCEPTION_ERROR_INVALID_ARGUMENTS WIRE_CALL_ABI_ERROR_SUCCESS
	WIRE_CONTROL_FLOW_ERROR_SUCCESS WIRE_SCALAR_OPERATION_ERROR_SUCCESS
	WIRE_CONTAINER_ERROR_SUCCESS WIRE_STRING_TABLE_ERROR_SUCCESS
	WIRE_FILE_SOURCE_ERROR_SUCCESS WIRE_DATA_LAYOUT_ERROR_SUCCESS
	WIRE_TYPE_LAYOUT_ERROR_SUCCESS WIRE_FUNCTION_SIGNATURE_ERROR_SUCCESS
	WIRE_MODULE_LIFECYCLE_ERROR_SUCCESS WIRE_SYMBOL_LINKAGE_ERROR_SUCCESS
	WIRE_CONSTANT_INITIALIZER_ERROR_SUCCESS 0 0 -1 -1)
failures: failures + (test-exception "NEGATIVE-WORKSPACE" exception-valid-rich
	} length? rich-exception-message { exception-workspace -1
	WIRE_EXCEPTION_ERROR_INVALID_ARGUMENTS WIRE_CALL_ABI_ERROR_SUCCESS
	WIRE_CONTROL_FLOW_ERROR_SUCCESS WIRE_SCALAR_OPERATION_ERROR_SUCCESS
	WIRE_CONTAINER_ERROR_SUCCESS WIRE_STRING_TABLE_ERROR_SUCCESS
	WIRE_FILE_SOURCE_ERROR_SUCCESS WIRE_DATA_LAYOUT_ERROR_SUCCESS
	WIRE_TYPE_LAYOUT_ERROR_SUCCESS WIRE_FUNCTION_SIGNATURE_ERROR_SUCCESS
	WIRE_MODULE_LIFECYCLE_ERROR_SUCCESS WIRE_SYMBOL_LINKAGE_ERROR_SUCCESS
	WIRE_CONSTANT_INITIALIZER_ERROR_SUCCESS 0 0 -1 -1)
failures: failures + (test-exception "INSUFFICIENT-WORKSPACE" exception-valid-rich
	} length? rich-exception-message { exception-small-workspace 0
	WIRE_EXCEPTION_ERROR_INVALID_CALL_ABI WIRE_CALL_ABI_ERROR_INVALID_CONTROL_FLOW
	WIRE_CONTROL_FLOW_ERROR_INSUFFICIENT_WORKSPACE WIRE_SCALAR_OPERATION_ERROR_SUCCESS
	WIRE_CONTAINER_ERROR_SUCCESS WIRE_STRING_TABLE_ERROR_SUCCESS
	WIRE_FILE_SOURCE_ERROR_SUCCESS WIRE_DATA_LAYOUT_ERROR_SUCCESS
	WIRE_TYPE_LAYOUT_ERROR_SUCCESS WIRE_FUNCTION_SIGNATURE_ERROR_SUCCESS
	WIRE_MODULE_LIFECYCLE_ERROR_SUCCESS WIRE_SYMBOL_LINKAGE_ERROR_SUCCESS
	WIRE_CONSTANT_INITIALIZER_ERROR_SUCCESS 0 0 -1 -1)

poison-outputs strings files layout types functions modules symbols constants
	scalar control calls exceptions
code: wire-exception-reader/verify exception-valid-rich } length? rich-exception-message {
	exception-workspace 64 (as wire-exception-result! 0)
	strings files layout types functions modules symbols constants scalar control calls exceptions
if code <> WIRE_EXCEPTION_ERROR_INVALID_ARGUMENTS [failures: failures + 1]
unless outputs-poisoned? strings files layout types functions modules symbols constants
	scalar control calls exceptions
[
	failures: failures + 1
]
}]

foreach [type-name before after] [
	wire-string-table! "result "
		" files layout types functions modules symbols constants scalar control calls exceptions"
	wire-file-source! "result strings "
		" layout types functions modules symbols constants scalar control calls exceptions"
	wire-data-layout! "result strings files "
		" types functions modules symbols constants scalar control calls exceptions"
	wire-type-layout! "result strings files layout "
		" functions modules symbols constants scalar control calls exceptions"
	wire-function-signature! "result strings files layout types "
		" modules symbols constants scalar control calls exceptions"
	wire-module-lifecycle! "result strings files layout types functions "
		" symbols constants scalar control calls exceptions"
	wire-symbol-linkage! "result strings files layout types functions modules "
		" constants scalar control calls exceptions"
	wire-constant-initializer! "result strings files layout types functions modules symbols "
		" scalar control calls exceptions"
	wire-scalar-operation! "result strings files layout types functions modules symbols constants "
		" control calls exceptions"
	wire-control-flow! "result strings files layout types functions modules symbols constants scalar "
		" calls exceptions"
	wire-call-abi! "result strings files layout types functions modules symbols constants scalar control "
		" exceptions"
	wire-exception! "result strings files layout types functions modules symbols constants scalar control calls "
		""
][
	append output rejoin [
		"code: wire-exception-reader/verify exception-valid-rich "
		length? rich-exception-message " exception-workspace 64 "
		before "(as " type-name " 0)" after newline
		"if code <> WIRE_EXCEPTION_ERROR_INVALID_ARGUMENTS "
		"[failures: failures + 1]" newline
	]
]

append output {

either failures = 0 [
	print ["PASS: Red/System RSIR exception semantics" lf]
][
	print ["FAIL: Red/System RSIR exception semantics failures=" failures lf]
]
quit failures
}

target: %tests/wire-exception-reds-test.reds
write target to binary! output
print [
	"Generated" target "with" length? valid-exceptions "valid and"
	length? malformed-exceptions "malformed fixtures"
]
