Red [
	Title: "Generate Red/System RSCG metadata fixture tests"
]

generating-wire-rscg-metadata-fixtures?: true
generating-wire-rscg-relocation-fixtures?: true
do %tests/wire-rscg-metadata-test.red

word-name: func [value [word!]][lowercase copy form value]

append-binary: func [output [string!] prefix [string!] name [word!] data [binary!]][
	append output rejoin [prefix word-name name ": " mold/flat data newline]
]

output: make string! 4'194'304
source-bytes: make binary! 2'097'152
foreach source-file [
	%tests/wire-rscg-metadata-test.red
	%tests/wire-rscg-relocation-test.red
	%tests/wire-rscg-object-test.red
	%tests/wire-module-lifecycle-test.red
	%tests/wire-data-layout-test.red
	%tests/wire-file-source-test.red
	%tests/wire-string-table-test.red
	%tests/wire-container-test.red
	%generate-wire-rscg-metadata-fixtures.red
][append source-bytes read source-file]
append source-bytes to binary! mold schema/WIRE_SCHEMA_FINGERPRINT
source-digest: enbase/base checksum source-bytes 'SHA256 16

append output {Red/System [
	Title: "Generated RSCG debug, GC, and unwind metadata cross-language tests"
]

; Generated by tools/self_hosting/generate-wire-rscg-metadata-fixtures.red.
; Do not edit. Error codes and locations are frozen by the Red semantic corpus.
}
append output rejoin ["; Fixture source SHA256: " source-digest newline]
append output {
#include %../../../system/codegen/wire-rscg-metadata.reds

}

foreach fixture valid-rscg-metadata-fixtures [
	append-binary output "metadata-valid-" fixture/1 fixture/2
]
foreach fixture malformed-rscg-metadata [
	append-binary output "metadata-invalid-" fixture/1 fixture/12
]

append output {
poison-memory: func [
	memory [byte-ptr!]
	size [integer!]
	/local cursor [byte-ptr!] remaining [integer!]
][
	cursor: memory
	remaining: size
	while [remaining > 0][
		cursor/1: as byte! 165
		cursor: cursor + 1
		remaining: remaining - 1
	]
]

memory-poisoned?: func [
	memory [byte-ptr!]
	size [integer!]
	return: [logic!]
	/local cursor [byte-ptr!] remaining [integer!]
][
	cursor: memory
	remaining: size
	while [remaining > 0][
		if cursor/1 <> as byte! 165 [return false]
		cursor: cursor + 1
		remaining: remaining - 1
	]
	true
]

poison-outputs: func [
	strings [wire-string-table!]
	files [wire-file-source!]
	layout [wire-data-layout!]
	modules [wire-module-lifecycle!]
	object-view [wire-rscg-object!]
	relocation-view [wire-rscg-relocation!]
	metadata-view [wire-rscg-metadata!]
][
	poison-memory as byte-ptr! strings size? wire-string-table!
	poison-memory as byte-ptr! files size? wire-file-source!
	poison-memory as byte-ptr! layout size? wire-data-layout!
	poison-memory as byte-ptr! modules size? wire-module-lifecycle!
	poison-memory as byte-ptr! object-view size? wire-rscg-object!
	poison-memory as byte-ptr! relocation-view size? wire-rscg-relocation!
	poison-memory as byte-ptr! metadata-view size? wire-rscg-metadata!
]

outputs-poisoned?: func [
	strings [wire-string-table!]
	files [wire-file-source!]
	layout [wire-data-layout!]
	modules [wire-module-lifecycle!]
	object-view [wire-rscg-object!]
	relocation-view [wire-rscg-relocation!]
	metadata-view [wire-rscg-metadata!]
	return: [logic!]
][
	all [
		memory-poisoned? as byte-ptr! strings size? wire-string-table!
		memory-poisoned? as byte-ptr! files size? wire-file-source!
		memory-poisoned? as byte-ptr! layout size? wire-data-layout!
		memory-poisoned? as byte-ptr! modules size? wire-module-lifecycle!
		memory-poisoned? as byte-ptr! object-view size? wire-rscg-object!
		memory-poisoned? as byte-ptr! relocation-view size? wire-rscg-relocation!
		memory-poisoned? as byte-ptr! metadata-view size? wire-rscg-metadata!
	]
]

test-metadata: func [
	name [c-string!]
	data [byte-ptr!]
	size [integer!]
	expected-error expected-relocation expected-object expected-container
	expected-string expected-file expected-layout expected-module expected-offset
	expected-section expected-lines expected-parameters expected-frames [integer!]
	return: [integer!]
	/local result [wire-rscg-metadata-result!]
		strings [wire-string-table!]
		files [wire-file-source!]
		layout [wire-data-layout!]
		modules [wire-module-lifecycle!]
		object-view [wire-rscg-object!]
		relocation-view [wire-rscg-relocation!]
		metadata-view [wire-rscg-metadata!]
		actual [integer!]
][
	result: declare wire-rscg-metadata-result!
	strings: declare wire-string-table!
	files: declare wire-file-source!
	layout: declare wire-data-layout!
	modules: declare wire-module-lifecycle!
	object-view: declare wire-rscg-object!
	relocation-view: declare wire-rscg-relocation!
	metadata-view: declare wire-rscg-metadata!
	poison-outputs strings files layout modules object-view relocation-view metadata-view
	actual: wire-rscg-metadata-reader/verify data size result strings files layout
		modules object-view relocation-view metadata-view
	if actual <> expected-error [
		print ["FAIL: " name " expected=" expected-error " actual=" actual lf]
		return 1
	]
	if result/error <> expected-error [return 1]
	if result/relocation-error <> expected-relocation [
		print ["FAIL: " name " relocation=" result/relocation-error lf]
		return 1
	]
	if result/object-error <> expected-object [
		print ["FAIL: " name " object=" result/object-error lf]
		return 1
	]
	if result/container-error <> expected-container [return 1]
	if result/string-error <> expected-string [return 1]
	if result/file-source-error <> expected-file [return 1]
	if result/data-layout-error <> expected-layout [return 1]
	if result/module-lifecycle-error <> expected-module [return 1]
	if any [
		result/error-offset <> expected-offset
		result/error-section <> expected-section
	][
		print [
			"FAIL: " name " location=" result/error-offset ":" result/error-section
			" expected=" expected-offset ":" expected-section lf
		]
		return 1
	]
	if expected-error <> WIRE_RSCG_METADATA_ERROR_SUCCESS [
		unless outputs-poisoned? strings files layout modules object-view
			relocation-view metadata-view
		[
			print ["FAIL: " name " modified output views on failure" lf]
			return 1
		]
		return 0
	]
	if any [
		metadata-view/debug-line-count <> expected-lines
		metadata-view/debug-parameter-count <> expected-parameters
		metadata-view/gc-frame-count <> expected-frames
		metadata-view/unwind-function-count <> 0
		object-view/function-count <> expected-frames
	][
		print ["FAIL: " name " verified metadata view changed" lf]
		return 1
	]
	0
]

failures: 0
}

foreach fixture valid-rscg-metadata-fixtures [
	append output rejoin [
		{failures: failures + (test-metadata "} form fixture/1 {" }
		"metadata-valid-" word-name fixture/1 " " length? fixture/2
		" 0 0 0 0 0 0 0 0 0 0 "
		fixture/3 " " fixture/4 " " fixture/5 ")" newline
	]
]

foreach fixture malformed-rscg-metadata [
	append output rejoin [
		{failures: failures + (test-metadata "} form fixture/1 {" }
		"metadata-invalid-" word-name fixture/1 " " length? fixture/12
		" " fixture/2 " " fixture/3 " " fixture/4 " " fixture/5
		" " fixture/6 " " fixture/7 " " fixture/8 " " fixture/9
		" " fixture/10 " " fixture/11 " -1 -1 -1)" newline
	]
]

append output rejoin [{

failures: failures + (test-metadata "NULL-DATA" (as byte-ptr! 0)
	} length? valid-rscg-metadata {
	WIRE_RSCG_METADATA_ERROR_INVALID_ARGUMENTS WIRE_RSCG_RELOCATION_ERROR_SUCCESS
	WIRE_RSCG_OBJECT_ERROR_SUCCESS WIRE_CONTAINER_ERROR_SUCCESS
	WIRE_STRING_TABLE_ERROR_SUCCESS WIRE_FILE_SOURCE_ERROR_SUCCESS
	WIRE_DATA_LAYOUT_ERROR_SUCCESS WIRE_MODULE_LIFECYCLE_ERROR_SUCCESS
	0 0 -1 -1 -1)

failures: failures + (test-metadata "NEGATIVE-SIZE" metadata-valid-standard -1
	WIRE_RSCG_METADATA_ERROR_INVALID_ARGUMENTS WIRE_RSCG_RELOCATION_ERROR_SUCCESS
	WIRE_RSCG_OBJECT_ERROR_SUCCESS WIRE_CONTAINER_ERROR_SUCCESS
	WIRE_STRING_TABLE_ERROR_SUCCESS WIRE_FILE_SOURCE_ERROR_SUCCESS
	WIRE_DATA_LAYOUT_ERROR_SUCCESS WIRE_MODULE_LIFECYCLE_ERROR_SUCCESS
	0 0 -1 -1 -1)

result: declare wire-rscg-metadata-result!
strings: declare wire-string-table!
files: declare wire-file-source!
layout: declare wire-data-layout!
modules: declare wire-module-lifecycle!
object-view: declare wire-rscg-object!
relocation-view: declare wire-rscg-relocation!
metadata-view: declare wire-rscg-metadata!
poison-outputs strings files layout modules object-view relocation-view metadata-view
code: wire-rscg-metadata-reader/verify metadata-valid-standard }
length? valid-rscg-metadata {
	(as wire-rscg-metadata-result! 0) strings files layout modules object-view
	relocation-view metadata-view
if code <> WIRE_RSCG_METADATA_ERROR_INVALID_ARGUMENTS [failures: failures + 1]
unless outputs-poisoned? strings files layout modules object-view relocation-view
	metadata-view [failures: failures + 1]

either failures = 0 [
	print ["PASS: Red/System RSCG debug, GC, and unwind metadata semantics" lf]
][
	print ["FAIL: Red/System RSCG metadata semantics failures=" failures lf]
]
quit failures
}]

target: %tests/wire-rscg-metadata-reds-test.reds
write target to binary! output
print [
	"Generated" target "with" length? valid-rscg-metadata-fixtures "valid and"
	length? malformed-rscg-metadata "malformed fixtures"
]
