Red [
	Title: "Generate Red/System RSIR type and aggregate-layout fixture tests"
]

generating-wire-type-layout-fixtures?: true
do %tests/wire-type-layout-test.red

word-name: func [value [word!]][lowercase copy form value]

append-binary: func [output [string!] prefix [string!] name [word!] data [binary!]][
	append output rejoin [prefix word-name name ": " mold/flat data newline]
]

output: make string! 524288
source-bytes: make binary! 262144
append source-bytes read %tests/wire-type-layout-test.red
append source-bytes read %tests/wire-file-source-test.red
append source-bytes read %tests/wire-string-table-test.red
append source-bytes read %tests/wire-container-test.red
append source-bytes read %generate-wire-type-layout-fixtures.red
append source-bytes to binary! mold schema/WIRE_SCHEMA_FINGERPRINT
source-digest: enbase/base checksum source-bytes 'SHA256 16

append output {Red/System [
	Title: "Generated RSIR type and aggregate-layout cross-language tests"
]

; Generated by tools/self_hosting/generate-wire-type-layout-fixtures.red.
; Do not edit. Error codes and locations are frozen by the Red semantic corpus.
}
append output rejoin ["; Fixture source SHA256: " source-digest newline]
append output {
#include %../../../system/codegen/wire-type-layout.reds

}

foreach fixture valid-type-layouts [
	append-binary output "type-valid-" fixture/1 fixture/2
]
foreach fixture malformed-type-layouts [
	append-binary output "type-invalid-" fixture/1 fixture/9
]

append output {
poison-strings: func [strings [wire-string-table!]][
	strings/records: as byte-ptr! 101
	strings/record-count: -102
	strings/record-size: -103
	strings/records-offset: -104
	strings/records-ordinal: -105
	strings/data: as byte-ptr! 106
	strings/data-size: -107
	strings/data-offset: -108
	strings/data-ordinal: -109
]

strings-poisoned?: func [strings [wire-string-table!] return: [logic!]][
	all [
		strings/records = (as byte-ptr! 101)
		strings/record-count = -102
		strings/record-size = -103
		strings/records-offset = -104
		strings/records-ordinal = -105
		strings/data = (as byte-ptr! 106)
		strings/data-size = -107
		strings/data-offset = -108
		strings/data-ordinal = -109
	]
]

poison-files: func [files [wire-file-source!]][
	files/files: as byte-ptr! 201
	files/file-count: -202
	files/file-record-size: -203
	files/files-offset: -204
	files/files-ordinal: -205
	files/checksum-data: as byte-ptr! 206
	files/checksum-data-size: -207
	files/checksum-data-offset: -208
	files/checksum-data-ordinal: -209
	files/source-present: -210
	files/sources: as byte-ptr! 211
	files/source-count: -212
	files/source-record-size: -213
	files/source-offset: -214
	files/source-ordinal: -215
]

files-poisoned?: func [files [wire-file-source!] return: [logic!]][
	all [
		files/files = (as byte-ptr! 201)
		files/file-count = -202
		files/file-record-size = -203
		files/files-offset = -204
		files/files-ordinal = -205
		files/checksum-data = (as byte-ptr! 206)
		files/checksum-data-size = -207
		files/checksum-data-offset = -208
		files/checksum-data-ordinal = -209
		files/source-present = -210
		files/sources = (as byte-ptr! 211)
		files/source-count = -212
		files/source-record-size = -213
		files/source-offset = -214
		files/source-ordinal = -215
	]
]

poison-layout: func [layout [wire-data-layout!]][
	layout/address-unit: -301
	layout/pointer-size: -302
	layout/pointer-alignment: -303
	layout/stack-alignment: -304
	layout/max-scalar-alignment: -305
	layout/max-aggregate-alignment: -306
	layout/integer-register-width: -307
	layout/flags: -308
]

layout-poisoned?: func [layout [wire-data-layout!] return: [logic!]][
	all [
		layout/address-unit = -301
		layout/pointer-size = -302
		layout/pointer-alignment = -303
		layout/stack-alignment = -304
		layout/max-scalar-alignment = -305
		layout/max-aggregate-alignment = -306
		layout/integer-register-width = -307
		layout/flags = -308
	]
]

poison-view: func [view [wire-type-layout!]][
	view/types: as byte-ptr! 401
	view/type-count: -402
	view/type-record-size: -403
	view/types-offset: -404
	view/types-ordinal: -405
	view/fields: as byte-ptr! 406
	view/field-count: -407
	view/field-record-size: -408
	view/fields-offset: -409
	view/fields-ordinal: -410
	view/signature-count: -411
	view/source-location-count: -412
]

view-poisoned?: func [view [wire-type-layout!] return: [logic!]][
	all [
		view/types = (as byte-ptr! 401)
		view/type-count = -402
		view/type-record-size = -403
		view/types-offset = -404
		view/types-ordinal = -405
		view/fields = (as byte-ptr! 406)
		view/field-count = -407
		view/field-record-size = -408
		view/fields-offset = -409
		view/fields-ordinal = -410
		view/signature-count = -411
		view/source-location-count = -412
	]
]

poison-outputs: func [
	strings [wire-string-table!]
	files [wire-file-source!]
	layout [wire-data-layout!]
	view [wire-type-layout!]
][
	poison-strings strings
	poison-files files
	poison-layout layout
	poison-view view
]

outputs-poisoned?: func [
	strings [wire-string-table!]
	files [wire-file-source!]
	layout [wire-data-layout!]
	view [wire-type-layout!]
	return: [logic!]
][
	all [
		strings-poisoned? strings
		files-poisoned? files
		layout-poisoned? layout
		view-poisoned? view
	]
]

test-type-layout: func [
	name [c-string!]
	data [byte-ptr!]
	size expected-error expected-container expected-string expected-file expected-layout
	expected-offset expected-section [integer!]
	return: [integer!]
	/local result [wire-type-layout-result!]
		strings [wire-string-table!] files [wire-file-source!]
		layout [wire-data-layout!] view [wire-type-layout!] actual [integer!]
][
	result: declare wire-type-layout-result!
	strings: declare wire-string-table!
	files: declare wire-file-source!
	layout: declare wire-data-layout!
	view: declare wire-type-layout!
	poison-outputs strings files layout view
	actual: wire-type-layout-reader/verify
		data size result strings files layout view
	if actual <> expected-error [
		print ["FAIL: " name " expected=" expected-error " actual=" actual lf]
		return 1
	]
	if result/error <> expected-error [
		print ["FAIL: " name " result/error=" result/error lf]
		return 1
	]
	if result/container-error <> expected-container [
		print ["FAIL: " name " container=" result/container-error lf]
		return 1
	]
	if result/string-error <> expected-string [
		print ["FAIL: " name " string=" result/string-error lf]
		return 1
	]
	if result/file-source-error <> expected-file [
		print ["FAIL: " name " file/source=" result/file-source-error lf]
		return 1
	]
	if result/data-layout-error <> expected-layout [
		print ["FAIL: " name " data-layout=" result/data-layout-error lf]
		return 1
	]
	if any [
		result/error-offset <> expected-offset
		result/error-section <> expected-section
	][
		print [
			"FAIL: " name
			" location=" result/error-offset ":" result/error-section
			" expected=" expected-offset ":" expected-section lf
		]
		return 1
	]
	if all [
		expected-error <> WIRE_TYPE_LAYOUT_ERROR_SUCCESS
		not outputs-poisoned? strings files layout view
	][
		print ["FAIL: " name " modified output views on failure" lf]
		return 1
	]
	0
]

failures: 0
}

foreach fixture valid-type-layouts [
	append output rejoin [
		{failures: failures + (test-type-layout "} form fixture/1 {" }
		"type-valid-" word-name fixture/1 " " length? fixture/2
		" " schema/WIRE_TYPE_LAYOUT_ERROR_SUCCESS
		" " schema/WIRE_CONTAINER_ERROR_SUCCESS
		" " schema/WIRE_STRING_TABLE_ERROR_SUCCESS
		" " schema/WIRE_FILE_SOURCE_ERROR_SUCCESS
		" " schema/WIRE_DATA_LAYOUT_ERROR_SUCCESS
		" 0 0)" newline
	]
]

foreach fixture malformed-type-layouts [
	append output rejoin [
		{failures: failures + (test-type-layout "} form fixture/1 {" }
		"type-invalid-" word-name fixture/1 " " length? fixture/9
		" " fixture/2 " " fixture/3 " " fixture/4 " " fixture/5
		" " fixture/6 " " fixture/7 " " fixture/8 ")" newline
	]
]

verified: type-layout-verifier/verify type-layout-message
append output rejoin [{

result: declare wire-type-layout-result!
strings: declare wire-string-table!
files: declare wire-file-source!
layout: declare wire-data-layout!
view: declare wire-type-layout!
code: wire-type-layout-reader/verify
	type-valid-representations } length? type-layout-message {
	result strings files layout view
if code <> WIRE_TYPE_LAYOUT_ERROR_SUCCESS [failures: failures + 1]
if any [
	strings/record-count <> 9
	files/file-count <> 0
	files/source-count <> 0
	layout/pointer-size <> 8
	view/type-count <> 13
	view/type-record-size <> WIRE_RSIR_TYPE_SIZE
	view/types-offset <> } verified/view/types-offset {
	view/types-ordinal <> } verified/view/types-ordinal {
	view/field-count <> 9
	view/field-record-size <> WIRE_RSIR_FIELD_SIZE
	view/fields-offset <> } verified/view/fields-offset {
	view/fields-ordinal <> } verified/view/fields-ordinal {
	view/signature-count <> 1
	view/source-location-count <> 0
][
	print ["FAIL: verified type-layout view changed" lf]
	failures: failures + 1
]
if any [
	(wire-container-reader/read-i31 view/types WIRE_RSIR_TYPE_KIND_OFFSET)
		<> WIRE_TYPE_KIND_VOID
	(wire-container-reader/read-i31 view/fields WIRE_RSIR_FIELD_OWNER_TYPE_OFFSET)
		<> 10
][failures: failures + 1]

poison-outputs strings files layout view
code: wire-type-layout-reader/verify
	(as byte-ptr! 0) } length? type-layout-message { result strings files layout view
if code <> WIRE_TYPE_LAYOUT_ERROR_INVALID_ARGUMENTS [failures: failures + 1]
if any [
	result/error <> WIRE_TYPE_LAYOUT_ERROR_INVALID_ARGUMENTS
	result/container-error <> WIRE_CONTAINER_ERROR_SUCCESS
	result/string-error <> WIRE_STRING_TABLE_ERROR_SUCCESS
	result/file-source-error <> WIRE_FILE_SOURCE_ERROR_SUCCESS
	result/data-layout-error <> WIRE_DATA_LAYOUT_ERROR_SUCCESS
	result/error-offset <> 0
	result/error-section <> 0
][failures: failures + 1]
unless outputs-poisoned? strings files layout view [failures: failures + 1]

code: wire-type-layout-reader/verify
	type-valid-representations -1 result strings files layout view
if code <> WIRE_TYPE_LAYOUT_ERROR_INVALID_ARGUMENTS [failures: failures + 1]
unless outputs-poisoned? strings files layout view [failures: failures + 1]

code: wire-type-layout-reader/verify type-valid-representations
	} length? type-layout-message { result (as wire-string-table! 0) files layout view
if code <> WIRE_TYPE_LAYOUT_ERROR_INVALID_ARGUMENTS [failures: failures + 1]
code: wire-type-layout-reader/verify type-valid-representations
	} length? type-layout-message { result strings (as wire-file-source! 0) layout view
if code <> WIRE_TYPE_LAYOUT_ERROR_INVALID_ARGUMENTS [failures: failures + 1]
code: wire-type-layout-reader/verify type-valid-representations
	} length? type-layout-message { result strings files (as wire-data-layout! 0) view
if code <> WIRE_TYPE_LAYOUT_ERROR_INVALID_ARGUMENTS [failures: failures + 1]
code: wire-type-layout-reader/verify type-valid-representations
	} length? type-layout-message { result strings files layout (as wire-type-layout! 0)
if code <> WIRE_TYPE_LAYOUT_ERROR_INVALID_ARGUMENTS [failures: failures + 1]
code: wire-type-layout-reader/verify type-valid-representations
	} length? type-layout-message { (as wire-type-layout-result! 0) strings files layout view
if code <> WIRE_TYPE_LAYOUT_ERROR_INVALID_ARGUMENTS [failures: failures + 1]

either failures = 0 [
	print ["PASS: Red/System RSIR type/layout semantics" lf]
][
	print ["FAIL: Red/System RSIR type/layout semantics failures=" failures lf]
]
quit failures
}]

target: %tests/wire-type-layout-reds-test.reds
write target to binary! output
print [
	"Generated" target
	"with" length? valid-type-layouts "valid and"
	length? malformed-type-layouts "malformed fixtures"
]
