Red [
	Title: "Generate Red/System RSIR constant and initializer fixture tests"
]

generating-wire-constant-initializer-fixtures?: true
do %tests/wire-constant-initializer-test.red

word-name: func [value [word!]][lowercase copy form value]

append-binary: func [output [string!] prefix [string!] name [word!] data [binary!]][
	append output rejoin [prefix word-name name ": " mold/flat data newline]
]

output: make string! 8'388'608
source-bytes: make binary! 2'097'152
foreach source-file [
	%tests/wire-constant-initializer-test.red
	%tests/wire-symbol-linkage-test.red
	%tests/wire-function-signature-test.red
	%tests/wire-module-lifecycle-test.red
	%tests/wire-type-layout-test.red
	%tests/wire-data-layout-test.red
	%tests/wire-file-source-test.red
	%tests/wire-string-table-test.red
	%tests/wire-container-test.red
	%generate-wire-constant-initializer-fixtures.red
][append source-bytes read source-file]
append source-bytes to binary! mold schema/WIRE_SCHEMA_FINGERPRINT
source-digest: enbase/base checksum source-bytes 'SHA256 16

append output {Red/System [
	Title: "Generated RSIR constant and initializer cross-language tests"
]

; Generated by tools/self_hosting/generate-wire-constant-initializer-fixtures.red.
; Do not edit. Error codes and locations are frozen by the Red semantic corpus.
}
append output rejoin ["; Fixture source SHA256: " source-digest newline]
append output {
#include %../../../system/codegen/wire-constant-initializer.reds

}

foreach fixture valid-constant-initializers [
	append-binary output "constant-valid-" fixture/1 fixture/2
]
foreach fixture malformed-constant-initializers [
	append-binary output "constant-invalid-" fixture/1 fixture/13
]

append output {
poison-memory: func [
	memory [byte-ptr!]
	size [integer!]
	/local cursor [byte-ptr!] remaining [integer!]
][
	cursor: memory
	remaining: size
	while [remaining > 0][
		cursor/1: as byte! 165
		cursor: cursor + 1
		remaining: remaining - 1
	]
]

memory-poisoned?: func [
	memory [byte-ptr!]
	size [integer!]
	return: [logic!]
	/local cursor [byte-ptr!] remaining [integer!]
][
	cursor: memory
	remaining: size
	while [remaining > 0][
		if cursor/1 <> as byte! 165 [return false]
		cursor: cursor + 1
		remaining: remaining - 1
	]
	true
]

poison-outputs: func [
	strings [wire-string-table!]
	files [wire-file-source!]
	layout [wire-data-layout!]
	types [wire-type-layout!]
	functions [wire-function-signature!]
	modules [wire-module-lifecycle!]
	symbols [wire-symbol-linkage!]
	view [wire-constant-initializer!]
][
	poison-memory as byte-ptr! strings size? wire-string-table!
	poison-memory as byte-ptr! files size? wire-file-source!
	poison-memory as byte-ptr! layout size? wire-data-layout!
	poison-memory as byte-ptr! types size? wire-type-layout!
	poison-memory as byte-ptr! functions size? wire-function-signature!
	poison-memory as byte-ptr! modules size? wire-module-lifecycle!
	poison-memory as byte-ptr! symbols size? wire-symbol-linkage!
	poison-memory as byte-ptr! view size? wire-constant-initializer!
]

outputs-poisoned?: func [
	strings [wire-string-table!]
	files [wire-file-source!]
	layout [wire-data-layout!]
	types [wire-type-layout!]
	functions [wire-function-signature!]
	modules [wire-module-lifecycle!]
	symbols [wire-symbol-linkage!]
	view [wire-constant-initializer!]
	return: [logic!]
][
	all [
		memory-poisoned? as byte-ptr! strings size? wire-string-table!
		memory-poisoned? as byte-ptr! files size? wire-file-source!
		memory-poisoned? as byte-ptr! layout size? wire-data-layout!
		memory-poisoned? as byte-ptr! types size? wire-type-layout!
		memory-poisoned? as byte-ptr! functions size? wire-function-signature!
		memory-poisoned? as byte-ptr! modules size? wire-module-lifecycle!
		memory-poisoned? as byte-ptr! symbols size? wire-symbol-linkage!
		memory-poisoned? as byte-ptr! view size? wire-constant-initializer!
	]
]

test-constant-initializer: func [
	name [c-string!]
	data [byte-ptr!]
	size expected-error expected-container expected-string expected-file
	expected-layout expected-type expected-function expected-module expected-symbol
	expected-offset expected-section [integer!]
	return: [integer!]
	/local result [wire-constant-initializer-result!]
		strings [wire-string-table!]
		files [wire-file-source!]
		layout [wire-data-layout!]
		types [wire-type-layout!]
		functions [wire-function-signature!]
		modules [wire-module-lifecycle!]
		symbols [wire-symbol-linkage!]
		view [wire-constant-initializer!]
		actual [integer!]
][
	result: declare wire-constant-initializer-result!
	strings: declare wire-string-table!
	files: declare wire-file-source!
	layout: declare wire-data-layout!
	types: declare wire-type-layout!
	functions: declare wire-function-signature!
	modules: declare wire-module-lifecycle!
	symbols: declare wire-symbol-linkage!
	view: declare wire-constant-initializer!
	poison-outputs strings files layout types functions modules symbols view
	actual: wire-constant-initializer-reader/verify data size result
		strings files layout types functions modules symbols view
	if actual <> expected-error [
		print ["FAIL: " name " expected=" expected-error " actual=" actual lf]
		return 1
	]
	if result/error <> expected-error [
		print ["FAIL: " name " result/error=" result/error lf]
		return 1
	]
	if result/container-error <> expected-container [
		print ["FAIL: " name " container=" result/container-error lf]
		return 1
	]
	if result/string-error <> expected-string [
		print ["FAIL: " name " string=" result/string-error lf]
		return 1
	]
	if result/file-source-error <> expected-file [
		print ["FAIL: " name " file/source=" result/file-source-error lf]
		return 1
	]
	if result/data-layout-error <> expected-layout [
		print ["FAIL: " name " data-layout=" result/data-layout-error lf]
		return 1
	]
	if result/type-layout-error <> expected-type [
		print ["FAIL: " name " type-layout=" result/type-layout-error lf]
		return 1
	]
	if result/function-signature-error <> expected-function [
		print ["FAIL: " name " function/signature=" result/function-signature-error lf]
		return 1
	]
	if result/module-lifecycle-error <> expected-module [
		print ["FAIL: " name " module/lifecycle=" result/module-lifecycle-error lf]
		return 1
	]
	if result/symbol-linkage-error <> expected-symbol [
		print ["FAIL: " name " symbol/linkage=" result/symbol-linkage-error lf]
		return 1
	]
	if any [
		result/error-offset <> expected-offset
		result/error-section <> expected-section
	][
		print [
			"FAIL: " name
			" location=" result/error-offset ":" result/error-section
			" expected=" expected-offset ":" expected-section lf
		]
		return 1
	]
	if all [
		expected-error <> WIRE_CONSTANT_INITIALIZER_ERROR_SUCCESS
		not outputs-poisoned? strings files layout types functions modules symbols view
	][
		print ["FAIL: " name " modified output views on failure" lf]
		return 1
	]
	0
]

failures: 0
}

foreach fixture valid-constant-initializers [
	append output rejoin [
		{failures: failures + (test-constant-initializer "} form fixture/1 {" }
		"constant-valid-" word-name fixture/1 " " length? fixture/2
		" " schema/WIRE_CONSTANT_INITIALIZER_ERROR_SUCCESS
		" " schema/WIRE_CONTAINER_ERROR_SUCCESS
		" " schema/WIRE_STRING_TABLE_ERROR_SUCCESS
		" " schema/WIRE_FILE_SOURCE_ERROR_SUCCESS
		" " schema/WIRE_DATA_LAYOUT_ERROR_SUCCESS
		" " schema/WIRE_TYPE_LAYOUT_ERROR_SUCCESS
		" " schema/WIRE_FUNCTION_SIGNATURE_ERROR_SUCCESS
		" " schema/WIRE_MODULE_LIFECYCLE_ERROR_SUCCESS
		" " schema/WIRE_SYMBOL_LINKAGE_ERROR_SUCCESS
		" 0 0)" newline
	]
]

foreach fixture malformed-constant-initializers [
	append output rejoin [
		{failures: failures + (test-constant-initializer "} form fixture/1 {" }
		"constant-invalid-" word-name fixture/1 " " length? fixture/13
		" " fixture/2 " " fixture/3 " " fixture/4 " " fixture/5
		" " fixture/6 " " fixture/7 " " fixture/8 " " fixture/9
		" " fixture/10 " " fixture/11 " " fixture/12 ")" newline
	]
]

verified: constant-initializer-verifier/verify rich-constant-message
append output rejoin [{

result: declare wire-constant-initializer-result!
strings: declare wire-string-table!
files: declare wire-file-source!
layout: declare wire-data-layout!
types: declare wire-type-layout!
functions: declare wire-function-signature!
modules: declare wire-module-lifecycle!
symbols: declare wire-symbol-linkage!
view: declare wire-constant-initializer!
code: wire-constant-initializer-reader/verify
	constant-valid-rich } length? rich-constant-message {
	result strings files layout types functions modules symbols view
if code <> WIRE_CONSTANT_INITIALIZER_ERROR_SUCCESS [failures: failures + 1]
if any [
	strings/record-count <> 11
	files/file-count <> 0
	files/source-count <> 0
	layout/pointer-size <> 8
	types/type-count <> 12
	types/type-record-size <> WIRE_RSIR_TYPE_SIZE
	functions/signature-count <> 1
	functions/function-count <> 0
	modules/module-count <> 1
	symbols/symbol-count <> 4
	symbols/global-count <> 1
	symbols/symbols-offset <> } verified/symbols/symbols-offset {
	symbols/globals-offset <> } verified/symbols/globals-offset {
	view/constant-count <> 12
	view/constant-record-size <> WIRE_RSIR_CONSTANT_SIZE
	view/constants-offset <> } verified/view/constants-offset {
	view/constants-ordinal <> } verified/view/constants-ordinal {
	view/constant-data-size <> 80
	view/constant-data-offset <> } verified/view/constant-data-offset {
	view/constant-data-ordinal <> } verified/view/constant-data-ordinal {
	view/part-count <> 10
	view/part-record-size <> WIRE_RSIR_CONSTANT_PART_SIZE
	view/parts-offset <> } verified/view/parts-offset {
	view/parts-ordinal <> } verified/view/parts-ordinal {
	view/binding-count <> 2
	view/binding-record-size <> WIRE_RSIR_CONSTANT_BINDING_SIZE
	view/bindings-offset <> } verified/view/bindings-offset {
	view/bindings-ordinal <> } verified/view/bindings-ordinal {
	view/global-count <> 1
][
	print ["FAIL: verified constant/initializer view changed" lf]
	failures: failures + 1
]
if any [
	(wire-container-reader/read-i31 view/constants WIRE_RSIR_CONSTANT_KIND_OFFSET)
		<> WIRE_CONSTANT_KIND_SCALAR
	(wire-container-reader/read-i31 view/parts WIRE_RSIR_CONSTANT_PART_KIND_OFFSET)
		<> WIRE_CONSTANT_PART_KIND_CONSTANT_ADDRESS
	(wire-container-reader/read-i31 view/bindings WIRE_RSIR_CONSTANT_BINDING_SYMBOL_OFFSET)
		<> 1
	(wire-container-reader/read-i31 symbols/globals
		WIRE_RSIR_GLOBAL_INITIALIZER_CONSTANT_OFFSET) <> 1
][failures: failures + 1]

poison-outputs strings files layout types functions modules symbols view
code: wire-constant-initializer-reader/verify
	(as byte-ptr! 0) } length? rich-constant-message {
	result strings files layout types functions modules symbols view
if code <> WIRE_CONSTANT_INITIALIZER_ERROR_INVALID_ARGUMENTS [failures: failures + 1]
if any [
	result/error <> WIRE_CONSTANT_INITIALIZER_ERROR_INVALID_ARGUMENTS
	result/container-error <> WIRE_CONTAINER_ERROR_SUCCESS
	result/string-error <> WIRE_STRING_TABLE_ERROR_SUCCESS
	result/file-source-error <> WIRE_FILE_SOURCE_ERROR_SUCCESS
	result/data-layout-error <> WIRE_DATA_LAYOUT_ERROR_SUCCESS
	result/type-layout-error <> WIRE_TYPE_LAYOUT_ERROR_SUCCESS
	result/function-signature-error <> WIRE_FUNCTION_SIGNATURE_ERROR_SUCCESS
	result/module-lifecycle-error <> WIRE_MODULE_LIFECYCLE_ERROR_SUCCESS
	result/symbol-linkage-error <> WIRE_SYMBOL_LINKAGE_ERROR_SUCCESS
	result/error-offset <> 0
	result/error-section <> 0
][failures: failures + 1]
unless outputs-poisoned? strings files layout types functions modules symbols view [
	failures: failures + 1
]

code: wire-constant-initializer-reader/verify constant-valid-rich -1
	result strings files layout types functions modules symbols view
if code <> WIRE_CONSTANT_INITIALIZER_ERROR_INVALID_ARGUMENTS [failures: failures + 1]
unless outputs-poisoned? strings files layout types functions modules symbols view [
	failures: failures + 1
]

code: wire-constant-initializer-reader/verify constant-valid-rich } length? rich-constant-message {
	result (as wire-string-table! 0) files layout types functions modules symbols view
if code <> WIRE_CONSTANT_INITIALIZER_ERROR_INVALID_ARGUMENTS [failures: failures + 1]
code: wire-constant-initializer-reader/verify constant-valid-rich } length? rich-constant-message {
	result strings (as wire-file-source! 0) layout types functions modules symbols view
if code <> WIRE_CONSTANT_INITIALIZER_ERROR_INVALID_ARGUMENTS [failures: failures + 1]
code: wire-constant-initializer-reader/verify constant-valid-rich } length? rich-constant-message {
	result strings files (as wire-data-layout! 0) types functions modules symbols view
if code <> WIRE_CONSTANT_INITIALIZER_ERROR_INVALID_ARGUMENTS [failures: failures + 1]
code: wire-constant-initializer-reader/verify constant-valid-rich } length? rich-constant-message {
	result strings files layout (as wire-type-layout! 0) functions modules symbols view
if code <> WIRE_CONSTANT_INITIALIZER_ERROR_INVALID_ARGUMENTS [failures: failures + 1]
code: wire-constant-initializer-reader/verify constant-valid-rich } length? rich-constant-message {
	result strings files layout types (as wire-function-signature! 0) modules symbols view
if code <> WIRE_CONSTANT_INITIALIZER_ERROR_INVALID_ARGUMENTS [failures: failures + 1]
code: wire-constant-initializer-reader/verify constant-valid-rich } length? rich-constant-message {
	result strings files layout types functions (as wire-module-lifecycle! 0) symbols view
if code <> WIRE_CONSTANT_INITIALIZER_ERROR_INVALID_ARGUMENTS [failures: failures + 1]
code: wire-constant-initializer-reader/verify constant-valid-rich } length? rich-constant-message {
	result strings files layout types functions modules (as wire-symbol-linkage! 0) view
if code <> WIRE_CONSTANT_INITIALIZER_ERROR_INVALID_ARGUMENTS [failures: failures + 1]
code: wire-constant-initializer-reader/verify constant-valid-rich } length? rich-constant-message {
	result strings files layout types functions modules symbols (as wire-constant-initializer! 0)
if code <> WIRE_CONSTANT_INITIALIZER_ERROR_INVALID_ARGUMENTS [failures: failures + 1]
code: wire-constant-initializer-reader/verify constant-valid-rich } length? rich-constant-message {
	(as wire-constant-initializer-result! 0)
	strings files layout types functions modules symbols view
if code <> WIRE_CONSTANT_INITIALIZER_ERROR_INVALID_ARGUMENTS [failures: failures + 1]

either failures = 0 [
	print ["PASS: Red/System RSIR constant/initializer semantics" lf]
][
	print ["FAIL: Red/System RSIR constant/initializer semantics failures=" failures lf]
]
quit failures
}]

target: %tests/wire-constant-initializer-reds-test.reds
write target to binary! output
print [
	"Generated" target
	"with" length? valid-constant-initializers "valid and"
	length? malformed-constant-initializers "malformed fixtures"
]
