Red [
	Title: "Generate Red/System RSIR control-flow fixture tests"
]

generating-wire-control-flow-fixtures?: true
do %tests/wire-control-flow-test.red

word-name: func [value [word!]][lowercase copy form value]

append-binary: func [output [string!] prefix [string!] name [word!] data [binary!]][
	append output rejoin [prefix word-name name ": " mold/flat data newline]
]

output: make string! 12'582'912
source-bytes: make binary! 4'194'304
foreach source-file [
	%tests/wire-control-flow-test.red
	%tests/wire-scalar-operation-test.red
	%tests/wire-constant-initializer-test.red
	%tests/wire-symbol-linkage-test.red
	%tests/wire-function-signature-test.red
	%tests/wire-module-lifecycle-test.red
	%tests/wire-type-layout-test.red
	%tests/wire-data-layout-test.red
	%tests/wire-file-source-test.red
	%tests/wire-string-table-test.red
	%tests/wire-container-test.red
	%generate-wire-control-flow-fixtures.red
][append source-bytes read source-file]
append source-bytes to binary! mold schema/WIRE_SCHEMA_FINGERPRINT
source-digest: enbase/base checksum source-bytes 'SHA256 16

append output {Red/System [
	Title: "Generated RSIR control-flow cross-language tests"
]

; Generated by tools/self_hosting/generate-wire-control-flow-fixtures.red.
; Do not edit. Error codes and locations are frozen by the Red semantic corpus.
}
append output rejoin ["; Fixture source SHA256: " source-digest newline]
append output {
#include %../../../system/codegen/wire-control-flow.reds

}

foreach fixture valid-control-flows [
	append-binary output "control-valid-" fixture/1 fixture/2
]
foreach fixture malformed-control-flows [
	append-binary output "control-invalid-" fixture/1 fixture/15
]

append output {
; One byte per block is sufficient for graph closure and dominance marks.
control-workspace: #{
	00000000000000000000000000000000
	00000000000000000000000000000000
	00000000000000000000000000000000
	00000000000000000000000000000000
}
control-small-workspace: #{00}

poison-memory: func [
	memory [byte-ptr!]
	size [integer!]
	/local cursor [byte-ptr!] remaining [integer!]
][
	cursor: memory
	remaining: size
	while [remaining > 0][
		cursor/1: as byte! 165
		cursor: cursor + 1
		remaining: remaining - 1
	]
]

memory-poisoned?: func [
	memory [byte-ptr!]
	size [integer!]
	return: [logic!]
	/local cursor [byte-ptr!] remaining [integer!]
][
	cursor: memory
	remaining: size
	while [remaining > 0][
		if cursor/1 <> as byte! 165 [return false]
		cursor: cursor + 1
		remaining: remaining - 1
	]
	true
]

poison-outputs: func [
	strings [wire-string-table!]
	files [wire-file-source!]
	layout [wire-data-layout!]
	types [wire-type-layout!]
	functions [wire-function-signature!]
	modules [wire-module-lifecycle!]
	symbols [wire-symbol-linkage!]
	constants [wire-constant-initializer!]
	scalar [wire-scalar-operation!]
	control [wire-control-flow!]
][
	poison-memory as byte-ptr! strings size? wire-string-table!
	poison-memory as byte-ptr! files size? wire-file-source!
	poison-memory as byte-ptr! layout size? wire-data-layout!
	poison-memory as byte-ptr! types size? wire-type-layout!
	poison-memory as byte-ptr! functions size? wire-function-signature!
	poison-memory as byte-ptr! modules size? wire-module-lifecycle!
	poison-memory as byte-ptr! symbols size? wire-symbol-linkage!
	poison-memory as byte-ptr! constants size? wire-constant-initializer!
	poison-memory as byte-ptr! scalar size? wire-scalar-operation!
	poison-memory as byte-ptr! control size? wire-control-flow!
]

outputs-poisoned?: func [
	strings [wire-string-table!]
	files [wire-file-source!]
	layout [wire-data-layout!]
	types [wire-type-layout!]
	functions [wire-function-signature!]
	modules [wire-module-lifecycle!]
	symbols [wire-symbol-linkage!]
	constants [wire-constant-initializer!]
	scalar [wire-scalar-operation!]
	control [wire-control-flow!]
	return: [logic!]
][
	all [
		memory-poisoned? as byte-ptr! strings size? wire-string-table!
		memory-poisoned? as byte-ptr! files size? wire-file-source!
		memory-poisoned? as byte-ptr! layout size? wire-data-layout!
		memory-poisoned? as byte-ptr! types size? wire-type-layout!
		memory-poisoned? as byte-ptr! functions size? wire-function-signature!
		memory-poisoned? as byte-ptr! modules size? wire-module-lifecycle!
		memory-poisoned? as byte-ptr! symbols size? wire-symbol-linkage!
		memory-poisoned? as byte-ptr! constants size? wire-constant-initializer!
		memory-poisoned? as byte-ptr! scalar size? wire-scalar-operation!
		memory-poisoned? as byte-ptr! control size? wire-control-flow!
	]
]

test-control-flow: func [
	name [c-string!]
	data [byte-ptr!]
	size [integer!]
	workspace [byte-ptr!]
	workspace-size [integer!]
	expected-error expected-scalar expected-container expected-string
	expected-file expected-layout expected-type expected-function expected-module
	expected-symbol expected-constant expected-offset expected-section [integer!]
	return: [integer!]
	/local result [wire-control-flow-result!]
		strings [wire-string-table!]
		files [wire-file-source!]
		layout [wire-data-layout!]
		types [wire-type-layout!]
		functions [wire-function-signature!]
		modules [wire-module-lifecycle!]
		symbols [wire-symbol-linkage!]
		constants [wire-constant-initializer!]
		scalar [wire-scalar-operation!]
		control [wire-control-flow!]
		actual [integer!]
][
	result: declare wire-control-flow-result!
	strings: declare wire-string-table!
	files: declare wire-file-source!
	layout: declare wire-data-layout!
	types: declare wire-type-layout!
	functions: declare wire-function-signature!
	modules: declare wire-module-lifecycle!
	symbols: declare wire-symbol-linkage!
	constants: declare wire-constant-initializer!
	scalar: declare wire-scalar-operation!
	control: declare wire-control-flow!
	poison-outputs strings files layout types functions modules symbols constants
		scalar control
	actual: wire-control-flow-reader/verify data size workspace workspace-size result
		strings files layout types functions modules symbols constants scalar control
	if actual <> expected-error [
		print ["FAIL: " name " expected=" expected-error " actual=" actual lf]
		return 1
	]
	if result/error <> expected-error [
		print ["FAIL: " name " result/error=" result/error lf]
		return 1
	]
	if result/scalar-operation-error <> expected-scalar [
		print ["FAIL: " name " scalar=" result/scalar-operation-error lf]
		return 1
	]
	if result/container-error <> expected-container [
		print ["FAIL: " name " container=" result/container-error lf]
		return 1
	]
	if result/string-error <> expected-string [
		print ["FAIL: " name " strings=" result/string-error lf]
		return 1
	]
	if result/file-source-error <> expected-file [
		print ["FAIL: " name " file/source=" result/file-source-error lf]
		return 1
	]
	if result/data-layout-error <> expected-layout [
		print ["FAIL: " name " data-layout=" result/data-layout-error lf]
		return 1
	]
	if result/type-layout-error <> expected-type [
		print ["FAIL: " name " type-layout=" result/type-layout-error lf]
		return 1
	]
	if result/function-signature-error <> expected-function [
		print ["FAIL: " name " function/signature="
			result/function-signature-error lf]
		return 1
	]
	if result/module-lifecycle-error <> expected-module [
		print ["FAIL: " name " module/lifecycle=" result/module-lifecycle-error lf]
		return 1
	]
	if result/symbol-linkage-error <> expected-symbol [
		print ["FAIL: " name " symbol/linkage=" result/symbol-linkage-error lf]
		return 1
	]
	if result/constant-initializer-error <> expected-constant [
		print ["FAIL: " name " constant/initializer="
			result/constant-initializer-error lf]
		return 1
	]
	if any [
		result/error-offset <> expected-offset
		result/error-section <> expected-section
	][
		print [
			"FAIL: " name " location=" result/error-offset ":" result/error-section
			" expected=" expected-offset ":" expected-section lf
		]
		return 1
	]
	if all [
		expected-error <> WIRE_CONTROL_FLOW_ERROR_SUCCESS
		not outputs-poisoned? strings files layout types functions modules symbols
			constants scalar control
	][
		print ["FAIL: " name " modified output views on failure" lf]
		return 1
	]
	0
]

failures: 0
}

foreach fixture valid-control-flows [
	append output rejoin [
		{failures: failures + (test-control-flow "} form fixture/1 {" }
		"control-valid-" word-name fixture/1 " " length? fixture/2
		" control-workspace 64"
		" " schema/WIRE_CONTROL_FLOW_ERROR_SUCCESS
		" " schema/WIRE_SCALAR_OPERATION_ERROR_SUCCESS
		" " schema/WIRE_CONTAINER_ERROR_SUCCESS
		" " schema/WIRE_STRING_TABLE_ERROR_SUCCESS
		" " schema/WIRE_FILE_SOURCE_ERROR_SUCCESS
		" " schema/WIRE_DATA_LAYOUT_ERROR_SUCCESS
		" " schema/WIRE_TYPE_LAYOUT_ERROR_SUCCESS
		" " schema/WIRE_FUNCTION_SIGNATURE_ERROR_SUCCESS
		" " schema/WIRE_MODULE_LIFECYCLE_ERROR_SUCCESS
		" " schema/WIRE_SYMBOL_LINKAGE_ERROR_SUCCESS
		" " schema/WIRE_CONSTANT_INITIALIZER_ERROR_SUCCESS
		" 0 0)" newline
	]
]

foreach fixture malformed-control-flows [
	append output rejoin [
		{failures: failures + (test-control-flow "} form fixture/1 {" }
		"control-invalid-" word-name fixture/1 " " length? fixture/15
		" control-workspace 64"
		" " fixture/2 " " fixture/3 " " fixture/4 " " fixture/5
		" " fixture/6 " " fixture/7 " " fixture/8 " " fixture/9
		" " fixture/10 " " fixture/11 " " fixture/12 " " fixture/13
		" " fixture/14 ")" newline
	]
]

verified: control-flow-verifier/verify rich-control-flow-message
append output rejoin [{

result: declare wire-control-flow-result!
strings: declare wire-string-table!
files: declare wire-file-source!
layout: declare wire-data-layout!
types: declare wire-type-layout!
functions: declare wire-function-signature!
modules: declare wire-module-lifecycle!
symbols: declare wire-symbol-linkage!
constants: declare wire-constant-initializer!
scalar: declare wire-scalar-operation!
control: declare wire-control-flow!
code: wire-control-flow-reader/verify control-valid-rich } length? rich-control-flow-message {
	control-workspace 64 result
	strings files layout types functions modules symbols constants scalar control
if code <> WIRE_CONTROL_FLOW_ERROR_SUCCESS [failures: failures + 1]
if any [
	functions/function-count <> } verified/functions/function-count {
	functions/block-count <> } verified/functions/block-count {
	functions/blocks-offset <> } verified/functions/blocks-offset {
	scalar/value-count <> } verified/scalar-view/value-count {
	scalar/instruction-count <> } verified/scalar-view/instruction-count {
	scalar/operand-count <> } verified/scalar-view/operand-count {
	scalar/instructions-offset <> } verified/scalar-view/instructions-offset {
	control/edge-count <> } verified/view/edge-count {
	control/edge-record-size <> WIRE_RSIR_EDGE_SIZE
	control/edges-offset <> } verified/view/edges-offset {
	control/edges-ordinal <> } verified/view/edges-ordinal {
][
	print ["FAIL: verified control-flow view changed" lf]
	failures: failures + 1
]
if any [
	(wire-container-reader/read-i31 control/edges WIRE_RSIR_EDGE_SOURCE_BLOCK_OFFSET) <> 1
	(wire-container-reader/read-i31 control/edges WIRE_RSIR_EDGE_TARGET_BLOCK_OFFSET) <> 2
	(wire-container-reader/read-i31 control/edges WIRE_RSIR_EDGE_KIND_OFFSET)
		<> WIRE_EDGE_KIND_TRUE
][failures: failures + 1]

failures: failures + (test-control-flow "NULL-DATA" (as byte-ptr! 0)
	} length? rich-control-flow-message { control-workspace 64
	WIRE_CONTROL_FLOW_ERROR_INVALID_ARGUMENTS
	WIRE_SCALAR_OPERATION_ERROR_SUCCESS WIRE_CONTAINER_ERROR_SUCCESS
	WIRE_STRING_TABLE_ERROR_SUCCESS WIRE_FILE_SOURCE_ERROR_SUCCESS
	WIRE_DATA_LAYOUT_ERROR_SUCCESS WIRE_TYPE_LAYOUT_ERROR_SUCCESS
	WIRE_FUNCTION_SIGNATURE_ERROR_SUCCESS WIRE_MODULE_LIFECYCLE_ERROR_SUCCESS
	WIRE_SYMBOL_LINKAGE_ERROR_SUCCESS WIRE_CONSTANT_INITIALIZER_ERROR_SUCCESS 0 0)
failures: failures + (test-control-flow "NEGATIVE-SIZE" control-valid-rich -1
	control-workspace 64 WIRE_CONTROL_FLOW_ERROR_INVALID_ARGUMENTS
	WIRE_SCALAR_OPERATION_ERROR_SUCCESS WIRE_CONTAINER_ERROR_SUCCESS
	WIRE_STRING_TABLE_ERROR_SUCCESS WIRE_FILE_SOURCE_ERROR_SUCCESS
	WIRE_DATA_LAYOUT_ERROR_SUCCESS WIRE_TYPE_LAYOUT_ERROR_SUCCESS
	WIRE_FUNCTION_SIGNATURE_ERROR_SUCCESS WIRE_MODULE_LIFECYCLE_ERROR_SUCCESS
	WIRE_SYMBOL_LINKAGE_ERROR_SUCCESS WIRE_CONSTANT_INITIALIZER_ERROR_SUCCESS 0 0)
failures: failures + (test-control-flow "NULL-WORKSPACE" control-valid-rich
	} length? rich-control-flow-message { (as byte-ptr! 0) 64
	WIRE_CONTROL_FLOW_ERROR_INVALID_ARGUMENTS
	WIRE_SCALAR_OPERATION_ERROR_SUCCESS WIRE_CONTAINER_ERROR_SUCCESS
	WIRE_STRING_TABLE_ERROR_SUCCESS WIRE_FILE_SOURCE_ERROR_SUCCESS
	WIRE_DATA_LAYOUT_ERROR_SUCCESS WIRE_TYPE_LAYOUT_ERROR_SUCCESS
	WIRE_FUNCTION_SIGNATURE_ERROR_SUCCESS WIRE_MODULE_LIFECYCLE_ERROR_SUCCESS
	WIRE_SYMBOL_LINKAGE_ERROR_SUCCESS WIRE_CONSTANT_INITIALIZER_ERROR_SUCCESS 0 0)
failures: failures + (test-control-flow "NEGATIVE-WORKSPACE" control-valid-rich
	} length? rich-control-flow-message { control-workspace -1
	WIRE_CONTROL_FLOW_ERROR_INVALID_ARGUMENTS
	WIRE_SCALAR_OPERATION_ERROR_SUCCESS WIRE_CONTAINER_ERROR_SUCCESS
	WIRE_STRING_TABLE_ERROR_SUCCESS WIRE_FILE_SOURCE_ERROR_SUCCESS
	WIRE_DATA_LAYOUT_ERROR_SUCCESS WIRE_TYPE_LAYOUT_ERROR_SUCCESS
	WIRE_FUNCTION_SIGNATURE_ERROR_SUCCESS WIRE_MODULE_LIFECYCLE_ERROR_SUCCESS
	WIRE_SYMBOL_LINKAGE_ERROR_SUCCESS WIRE_CONSTANT_INITIALIZER_ERROR_SUCCESS 0 0)
failures: failures + (test-control-flow "INSUFFICIENT-WORKSPACE" control-valid-rich
	} length? rich-control-flow-message { control-small-workspace 1
	WIRE_CONTROL_FLOW_ERROR_INSUFFICIENT_WORKSPACE
	WIRE_SCALAR_OPERATION_ERROR_SUCCESS WIRE_CONTAINER_ERROR_SUCCESS
	WIRE_STRING_TABLE_ERROR_SUCCESS WIRE_FILE_SOURCE_ERROR_SUCCESS
	WIRE_DATA_LAYOUT_ERROR_SUCCESS WIRE_TYPE_LAYOUT_ERROR_SUCCESS
	WIRE_FUNCTION_SIGNATURE_ERROR_SUCCESS WIRE_MODULE_LIFECYCLE_ERROR_SUCCESS
	WIRE_SYMBOL_LINKAGE_ERROR_SUCCESS WIRE_CONSTANT_INITIALIZER_ERROR_SUCCESS 0 0)

poison-outputs strings files layout types functions modules symbols constants
	scalar control
code: wire-control-flow-reader/verify control-valid-rich } length? rich-control-flow-message {
	control-workspace 64 (as wire-control-flow-result! 0)
	strings files layout types functions modules symbols constants scalar control
if code <> WIRE_CONTROL_FLOW_ERROR_INVALID_ARGUMENTS [failures: failures + 1]
unless outputs-poisoned? strings files layout types functions modules symbols constants
	scalar control
[
	failures: failures + 1
]
}]

foreach [type-name before after] [
	wire-string-table! "result "
		" files layout types functions modules symbols constants scalar control"
	wire-file-source! "result strings "
		" layout types functions modules symbols constants scalar control"
	wire-data-layout! "result strings files "
		" types functions modules symbols constants scalar control"
	wire-type-layout! "result strings files layout "
		" functions modules symbols constants scalar control"
	wire-function-signature! "result strings files layout types "
		" modules symbols constants scalar control"
	wire-module-lifecycle! "result strings files layout types functions "
		" symbols constants scalar control"
	wire-symbol-linkage! "result strings files layout types functions modules "
		" constants scalar control"
	wire-constant-initializer! "result strings files layout types functions modules symbols "
		" scalar control"
	wire-scalar-operation! "result strings files layout types functions modules symbols constants "
		" control"
	wire-control-flow! "result strings files layout types functions modules symbols constants scalar "
		""
][
	append output rejoin [
		"code: wire-control-flow-reader/verify control-valid-rich "
		length? rich-control-flow-message
		" control-workspace 64 " before "(as " type-name " 0)"
		after newline
		"if code <> WIRE_CONTROL_FLOW_ERROR_INVALID_ARGUMENTS "
		"[failures: failures + 1]" newline
	]
]

append output {

either failures = 0 [
	print ["PASS: Red/System RSIR control-flow semantics" lf]
][
	print ["FAIL: Red/System RSIR control-flow semantics failures=" failures lf]
]
quit failures
}

target: %tests/wire-control-flow-reds-test.reds
write target to binary! output
print [
	"Generated" target "with" length? valid-control-flows "valid and"
	length? malformed-control-flows "malformed fixtures"
]
