Red [
	Title: "Generate Red/System RSCG object-layout fixture tests"
]

generating-wire-rscg-object-fixtures?: true
do %tests/wire-rscg-object-test.red

word-name: func [value [word!]][lowercase copy form value]

append-binary: func [output [string!] prefix [string!] name [word!] data [binary!]][
	append output rejoin [prefix word-name name ": " mold/flat data newline]
]

output: make string! 2'097'152
source-bytes: make binary! 1'048'576
foreach source-file [
	%tests/wire-rscg-object-test.red
	%tests/wire-module-lifecycle-test.red
	%tests/wire-data-layout-test.red
	%tests/wire-file-source-test.red
	%tests/wire-string-table-test.red
	%tests/wire-container-test.red
	%generate-wire-rscg-object-fixtures.red
][append source-bytes read source-file]
append source-bytes to binary! mold schema/WIRE_SCHEMA_FINGERPRINT
source-digest: enbase/base checksum source-bytes 'SHA256 16

append output {Red/System [
	Title: "Generated RSCG object-layout cross-language tests"
]

; Generated by tools/self_hosting/generate-wire-rscg-object-fixtures.red.
; Do not edit. Error codes and locations are frozen by the Red semantic corpus.
}
append output rejoin ["; Fixture source SHA256: " source-digest newline]
append output {
#include %../../../system/codegen/wire-rscg-object.reds

}

append-binary output "object-valid-" 'BASE valid-rscg-object
append-binary output "object-valid-" 'DLL valid-rscg-dll-object
foreach fixture malformed-rscg-objects [
	append-binary output "object-invalid-" fixture/1 fixture/10
]

append output {
poison-memory: func [
	memory [byte-ptr!]
	size [integer!]
	/local cursor [byte-ptr!] remaining [integer!]
][
	cursor: memory
	remaining: size
	while [remaining > 0][
		cursor/1: as byte! 165
		cursor: cursor + 1
		remaining: remaining - 1
	]
]

memory-poisoned?: func [
	memory [byte-ptr!]
	size [integer!]
	return: [logic!]
	/local cursor [byte-ptr!] remaining [integer!]
][
	cursor: memory
	remaining: size
	while [remaining > 0][
		if cursor/1 <> as byte! 165 [return false]
		cursor: cursor + 1
		remaining: remaining - 1
	]
	true
]

poison-outputs: func [
	strings [wire-string-table!]
	files [wire-file-source!]
	layout [wire-data-layout!]
	modules [wire-module-lifecycle!]
	view [wire-rscg-object!]
][
	poison-memory as byte-ptr! strings size? wire-string-table!
	poison-memory as byte-ptr! files size? wire-file-source!
	poison-memory as byte-ptr! layout size? wire-data-layout!
	poison-memory as byte-ptr! modules size? wire-module-lifecycle!
	poison-memory as byte-ptr! view size? wire-rscg-object!
]

outputs-poisoned?: func [
	strings [wire-string-table!]
	files [wire-file-source!]
	layout [wire-data-layout!]
	modules [wire-module-lifecycle!]
	view [wire-rscg-object!]
	return: [logic!]
][
	all [
		memory-poisoned? as byte-ptr! strings size? wire-string-table!
		memory-poisoned? as byte-ptr! files size? wire-file-source!
		memory-poisoned? as byte-ptr! layout size? wire-data-layout!
		memory-poisoned? as byte-ptr! modules size? wire-module-lifecycle!
		memory-poisoned? as byte-ptr! view size? wire-rscg-object!
	]
]

test-object: func [
	name [c-string!]
	data [byte-ptr!]
	size [integer!]
	expected-error expected-container expected-string expected-file expected-layout
	expected-module expected-offset expected-section expected-output-count
	expected-output-size expected-symbol-count expected-function-count expected-runtime
	expected-exec expected-bitmap expected-lib [integer!]
	return: [integer!]
	/local result [wire-rscg-object-result!]
		strings [wire-string-table!]
		files [wire-file-source!]
		layout [wire-data-layout!]
		modules [wire-module-lifecycle!]
		view [wire-rscg-object!]
		actual [integer!]
][
	result: declare wire-rscg-object-result!
	strings: declare wire-string-table!
	files: declare wire-file-source!
	layout: declare wire-data-layout!
	modules: declare wire-module-lifecycle!
	view: declare wire-rscg-object!
	poison-outputs strings files layout modules view
	actual: wire-rscg-object-reader/verify data size result strings files layout modules view
	if actual <> expected-error [
		print ["FAIL: " name " expected=" expected-error " actual=" actual lf]
		return 1
	]
	if result/error <> expected-error [return 1]
	if result/container-error <> expected-container [
		print ["FAIL: " name " container=" result/container-error lf]
		return 1
	]
	if result/string-error <> expected-string [return 1]
	if result/file-source-error <> expected-file [return 1]
	if result/data-layout-error <> expected-layout [return 1]
	if result/module-lifecycle-error <> expected-module [
		print ["FAIL: " name " module=" result/module-lifecycle-error lf]
		return 1
	]
	if any [
		result/error-offset <> expected-offset
		result/error-section <> expected-section
	][
		print [
			"FAIL: " name " location=" result/error-offset ":" result/error-section
			" expected=" expected-offset ":" expected-section lf
		]
		return 1
	]
	if expected-error <> WIRE_RSCG_OBJECT_ERROR_SUCCESS [
		unless outputs-poisoned? strings files layout modules view [
			print ["FAIL: " name " modified output views on failure" lf]
			return 1
		]
		return 0
	]
	if any [
		view/output-section-count <> expected-output-count
		view/output-data-size <> expected-output-size
		view/symbol-count <> expected-symbol-count
		view/function-count <> expected-function-count
		view/runtime-module <> expected-runtime
		view/exec-image-symbol <> expected-exec
		view/bitmap-symbol <> expected-bitmap
		view/lib-image-symbol <> expected-lib
		view/output-section-size <> WIRE_RSCG_OUTPUT_SECTION_SIZE
		view/symbol-size <> WIRE_RSCG_SYMBOL_SIZE
		view/function-size <> WIRE_RSCG_FUNCTION_SIZE
	][
		print ["FAIL: " name " verified object view changed" lf]
		return 1
	]
	0
]

failures: 0
}

verified: rscg-object-verifier/verify valid-rscg-object
append output rejoin [
	{failures: failures + (test-object "BASE" object-valid-base }
	length? valid-rscg-object
	" 0 0 0 0 0 0 0 0 "
	verified/view/output-section-count " " verified/view/output-data-size " "
	verified/view/symbol-count " " verified/view/function-count " "
	verified/view/runtime-module " " verified/view/exec-image-symbol " "
	verified/view/bitmap-symbol " " verified/view/lib-image-symbol ")" newline
]

verified: rscg-object-verifier/verify valid-rscg-dll-object
append output rejoin [
	{failures: failures + (test-object "DLL" object-valid-dll }
	length? valid-rscg-dll-object
	" 0 0 0 0 0 0 0 0 "
	verified/view/output-section-count " " verified/view/output-data-size " "
	verified/view/symbol-count " " verified/view/function-count " "
	verified/view/runtime-module " " verified/view/exec-image-symbol " "
	verified/view/bitmap-symbol " " verified/view/lib-image-symbol ")" newline
]

foreach fixture malformed-rscg-objects [
	append output rejoin [
		{failures: failures + (test-object "} form fixture/1 {" }
		"object-invalid-" word-name fixture/1 " " length? fixture/10
		" " fixture/2 " " fixture/3 " " fixture/4 " " fixture/5
		" " fixture/6 " " fixture/7 " " fixture/8 " " fixture/9
		" -1 -1 -1 -1 -1 -1 -1 -1)" newline
	]
]

append output rejoin [{

failures: failures + (test-object "NULL-DATA" (as byte-ptr! 0)
	} length? valid-rscg-object {
	WIRE_RSCG_OBJECT_ERROR_INVALID_ARGUMENTS WIRE_CONTAINER_ERROR_SUCCESS
	WIRE_STRING_TABLE_ERROR_SUCCESS WIRE_FILE_SOURCE_ERROR_SUCCESS
	WIRE_DATA_LAYOUT_ERROR_SUCCESS WIRE_MODULE_LIFECYCLE_ERROR_SUCCESS
	0 0 -1 -1 -1 -1 -1 -1 -1 -1)

failures: failures + (test-object "NEGATIVE-SIZE" object-valid-base -1
	WIRE_RSCG_OBJECT_ERROR_INVALID_ARGUMENTS WIRE_CONTAINER_ERROR_SUCCESS
	WIRE_STRING_TABLE_ERROR_SUCCESS WIRE_FILE_SOURCE_ERROR_SUCCESS
	WIRE_DATA_LAYOUT_ERROR_SUCCESS WIRE_MODULE_LIFECYCLE_ERROR_SUCCESS
	0 0 -1 -1 -1 -1 -1 -1 -1 -1)

result: declare wire-rscg-object-result!
strings: declare wire-string-table!
files: declare wire-file-source!
layout: declare wire-data-layout!
modules: declare wire-module-lifecycle!
view: declare wire-rscg-object!
poison-outputs strings files layout modules view
code: wire-rscg-object-reader/verify object-valid-base } length? valid-rscg-object {
	(as wire-rscg-object-result! 0) strings files layout modules view
if code <> WIRE_RSCG_OBJECT_ERROR_INVALID_ARGUMENTS [failures: failures + 1]
unless outputs-poisoned? strings files layout modules view [failures: failures + 1]

either failures = 0 [
	print ["PASS: Red/System RSCG object-layout semantics" lf]
][
	print ["FAIL: Red/System RSCG object-layout semantics failures=" failures lf]
]
quit failures
}]

target: %tests/wire-rscg-object-reds-test.reds
write target to binary! output
print [
	"Generated" target "with 2 valid and"
	length? malformed-rscg-objects "malformed fixtures"
]
