Red [
	Title: "Generate Red/System target data-layout semantic fixture tests"
]

generating-wire-data-layout-fixtures?: true
do %tests/wire-data-layout-test.red

word-name: func [value [word!]][lowercase copy form value]

append-binary: func [output [string!] prefix [string!] name [word!] data [binary!]][
	append output rejoin [prefix word-name name ": " mold/flat data newline]
]

output: make string! 131072
source-bytes: make binary! 65536
append source-bytes read %tests/wire-data-layout-test.red
append source-bytes read %tests/wire-container-test.red
append source-bytes read %generate-wire-data-layout-fixtures.red
append source-bytes to binary! mold schema/WIRE_SCHEMA_FINGERPRINT
source-digest: enbase/base checksum source-bytes 'SHA256 16

append output {Red/System [
	Title: "Generated target data-layout cross-language tests"
]

; Generated by tools/self_hosting/generate-wire-data-layout-fixtures.red.
; Do not edit. Error codes and locations are frozen by the Red semantic corpus.
}
append output rejoin ["; Fixture source SHA256: " source-digest newline]
append output {
#include %../../../system/codegen/wire-data-layout.reds

}

foreach fixture valid-data-layouts [
	append-binary output "layout-valid-" fixture/1 fixture/3
]
foreach fixture malformed-data-layouts [
	append-binary output "layout-invalid-" fixture/1 fixture/7
]
append output rejoin ["layout-valid-rsir-size: " length? rsir newline newline]

append output {
poison-layout: func [layout [wire-data-layout!]][
	layout/address-unit: -101
	layout/pointer-size: -102
	layout/pointer-alignment: -103
	layout/stack-alignment: -104
	layout/max-scalar-alignment: -105
	layout/max-aggregate-alignment: -106
	layout/integer-register-width: -107
	layout/flags: -108
]

layout-poisoned?: func [layout [wire-data-layout!] return: [logic!]][
	all [
		layout/address-unit = -101
		layout/pointer-size = -102
		layout/pointer-alignment = -103
		layout/stack-alignment = -104
		layout/max-scalar-alignment = -105
		layout/max-aggregate-alignment = -106
		layout/integer-register-width = -107
		layout/flags = -108
	]
]

test-layout: func [
	name [c-string!]
	data [byte-ptr!]
	size magic expected-error expected-container expected-offset expected-section [integer!]
	return: [integer!]
	/local result [wire-data-layout-result!] layout [wire-data-layout!] actual [integer!]
][
	result: declare wire-data-layout-result!
	layout: declare wire-data-layout!
	poison-layout layout
	actual: wire-data-layout-reader/verify data size magic result layout
	if actual <> expected-error [
		print ["FAIL: " name " expected=" expected-error " actual=" actual lf]
		return 1
	]
	if result/error <> expected-error [
		print ["FAIL: " name " result/error=" result/error lf]
		return 1
	]
	if result/container-error <> expected-container [
		print [
			"FAIL: " name " container=" result/container-error
			" expected=" expected-container lf
		]
		return 1
	]
	if any [
		result/error-offset <> expected-offset
		result/error-section <> expected-section
	][
		print [
			"FAIL: " name
			" location=" result/error-offset ":" result/error-section
			" expected=" expected-offset ":" expected-section lf
		]
		return 1
	]
	if all [
		expected-error <> WIRE_DATA_LAYOUT_ERROR_SUCCESS
		not layout-poisoned? layout
	][
		print ["FAIL: " name " modified layout on failure" lf]
		return 1
	]
	0
]

failures: 0
}

foreach fixture valid-data-layouts [
	append output rejoin [
		{failures: failures + (test-layout "} form fixture/1 {" }
		"layout-valid-" word-name fixture/1 " " length? fixture/3 " " fixture/2 " "
		schema/WIRE_DATA_LAYOUT_ERROR_SUCCESS " " schema/WIRE_CONTAINER_ERROR_SUCCESS
		" 0 0)" newline
	]
]

foreach fixture malformed-data-layouts [
	append output rejoin [
		{failures: failures + (test-layout "} form fixture/1 {" }
		"layout-invalid-" word-name fixture/1 " " length? fixture/7 " " fixture/2 " "
		fixture/3 " " fixture/4 " " fixture/5 " " fixture/6 ")" newline
	]
]

append output {

result: declare wire-data-layout-result!
layout: declare wire-data-layout!
code: wire-data-layout-reader/verify
	layout-valid-rsir layout-valid-rsir-size WIRE_MAGIC_RSIR result layout
if code <> WIRE_DATA_LAYOUT_ERROR_SUCCESS [failures: failures + 1]
if any [
	layout/address-unit <> 1
	layout/pointer-size <> 8
	layout/pointer-alignment <> 8
	layout/stack-alignment <> 16
	layout/max-scalar-alignment <> 8
	layout/max-aggregate-alignment <> 8
	layout/integer-register-width <> 8
	layout/flags <> 0
][
	print ["FAIL: Windows x64 data-layout decode changed" lf]
	failures: failures + 1
]

poison-layout layout
code: wire-data-layout-reader/verify
	(as byte-ptr! 0) layout-valid-rsir-size WIRE_MAGIC_RSIR result layout
if code <> WIRE_DATA_LAYOUT_ERROR_INVALID_ARGUMENTS [failures: failures + 1]
if any [
	result/error <> WIRE_DATA_LAYOUT_ERROR_INVALID_ARGUMENTS
	result/container-error <> WIRE_CONTAINER_ERROR_SUCCESS
	result/error-offset <> 0
	result/error-section <> 0
][failures: failures + 1]
unless layout-poisoned? layout [failures: failures + 1]

code: wire-data-layout-reader/verify
	layout-valid-rsir -1 WIRE_MAGIC_RSIR result layout
if code <> WIRE_DATA_LAYOUT_ERROR_INVALID_ARGUMENTS [failures: failures + 1]
unless layout-poisoned? layout [failures: failures + 1]

code: wire-data-layout-reader/verify
	layout-valid-rsir layout-valid-rsir-size WIRE_MAGIC_RSIR result (as wire-data-layout! 0)
if code <> WIRE_DATA_LAYOUT_ERROR_INVALID_ARGUMENTS [failures: failures + 1]

code: wire-data-layout-reader/verify
	layout-valid-rsir layout-valid-rsir-size WIRE_MAGIC_RSIR (as wire-data-layout-result! 0) layout
if code <> WIRE_DATA_LAYOUT_ERROR_INVALID_ARGUMENTS [failures: failures + 1]

poison-layout layout
code: wire-data-layout-reader/verify
	layout-valid-rsir layout-valid-rsir-size WIRE_MAGIC_RSCF result layout
if code <> WIRE_DATA_LAYOUT_ERROR_UNSUPPORTED_MESSAGE [failures: failures + 1]
if any [
	result/container-error <> WIRE_CONTAINER_ERROR_SUCCESS
	result/error-offset <> 0
	result/error-section <> 0
][failures: failures + 1]
unless layout-poisoned? layout [failures: failures + 1]

either failures = 0 [
	print ["PASS: Red/System target data-layout semantics" lf]
][
	print ["FAIL: Red/System target data-layout semantics failures=" failures lf]
]
quit failures
}

target: %tests/wire-data-layout-reds-test.reds
write target to binary! output
print [
	"Generated" target
	"with" length? valid-data-layouts "valid and"
	length? malformed-data-layouts "malformed fixtures"
]
