Red [
	Title: "Generate Red/System wire container fixture tests"
]

generating-wire-container-fixtures?: true
do %tests/wire-container-test.red

word-name: func [value [word!]][lowercase copy form value]

append-binary: func [output [string!] name [word!] data [binary!]][
	append output rejoin [
		"wire-fixture-" word-name name ": " mold/flat data newline
	]
]

positive: reduce [
	reduce ['RSCF schema/WIRE_MAGIC_RSCF rscf 1]
	reduce ['RSIR schema/WIRE_MAGIC_RSIR rsir 32]
	reduce ['RSCG schema/WIRE_MAGIC_RSCG rscg 16]
	reduce ['RSDG schema/WIRE_MAGIC_RSDG rsdg 3]
	reduce ['RSCG-OPTIONAL schema/WIRE_MAGIC_RSCG rscg-optional 17]
	reduce ['RSCF-UNKNOWN-OPTIONAL schema/WIRE_MAGIC_RSCF rscf-unknown-optional 2]
]

output: make string! 131072
source-bytes: make binary! 65536
append source-bytes read %tests/wire-container-test.red
append source-bytes read %generate-wire-container-fixtures.red
append source-bytes to binary! mold schema/WIRE_SCHEMA_FINGERPRINT
source-digest: enbase/base checksum source-bytes 'SHA256 16

append output {Red/System [
	Title: "Generated wire container cross-language tests"
]

; Generated by tools/self_hosting/generate-wire-container-fixtures.red.
; Do not edit. The Red fixture test pins the four core SHA-256 digests.
}
append output rejoin ["; Fixture source SHA256: " source-digest newline]
append output {
#include %../../../system/codegen/wire-reader.reds

}

foreach fixture positive [append-binary output fixture/1 fixture/3]
foreach fixture-case malformed [append-binary output fixture-case/1 fixture-case/4]

append output {
test-container: func [
	name [c-string!]
	data [byte-ptr!]
	size magic expected-error expected-sections expected-offset expected-section [integer!]
	return: [integer!]
	/local result [wire-container-result!] actual [integer!]
][
	result: declare wire-container-result!
	actual: wire-container-reader/verify data size magic result
	if actual <> expected-error [
		print ["FAIL: " name " expected=" expected-error " actual=" actual lf]
		return 1
	]
	if all [
		expected-error = WIRE_CONTAINER_ERROR_SUCCESS
		result/section-count <> expected-sections
	][
		print ["FAIL: " name " section-count=" result/section-count lf]
		return 1
	]
	if any [
		result/error-offset <> expected-offset
		result/error-section <> expected-section
	][
		print [
			"FAIL: " name
			" location=" result/error-offset ":" result/error-section
			" expected=" expected-offset ":" expected-section lf
		]
		return 1
	]
	0
]

test-truncations: func [
	name [c-string!]
	data [byte-ptr!]
	size magic [integer!]
	return: [integer!]
	/local result [wire-container-result!] length code [integer!]
][
	result: declare wire-container-result!
	length: 0
	while [length < size][
		code: wire-container-reader/verify data length magic result
		if code = WIRE_CONTAINER_ERROR_SUCCESS [
			print ["FAIL: " name " accepted truncation=" length lf]
			return 1
		]
		length: length + 1
	]
	0
]

failures: 0
}

foreach fixture positive [
	append output rejoin [
		{failures: failures + (test-container "} form fixture/1 {" }
		"wire-fixture-" word-name fixture/1 " " length? fixture/3 " "
		fixture/2 " " schema/WIRE_CONTAINER_ERROR_SUCCESS " " fixture/4 " 0 0)"
		newline
	]
]

foreach fixture-case malformed [
	red-result: verifier/verify/expect fixture-case/4 fixture-case/2
	append output rejoin [
		{failures: failures + (test-container "} form fixture-case/1 {" }
		"wire-fixture-" word-name fixture-case/1 " " length? fixture-case/4 " "
		fixture-case/2 " " fixture-case/3 " 0 "
		red-result/error-offset " " red-result/error-section ")"
		newline
	]
]

foreach fixture copy/part positive 4 [
	append output rejoin [
		{failures: failures + (test-truncations "} form fixture/1 {" }
		"wire-fixture-" word-name fixture/1 " " length? fixture/3 " " fixture/2 ")"
		newline
	]
]

append output {

result: declare wire-container-result!
slice: declare wire-section-slice!
code: wire-container-reader/verify wire-fixture-rscf 160 WIRE_MAGIC_RSCF result
if code <> WIRE_CONTAINER_ERROR_SUCCESS [failures: failures + 1]
unless wire-container-reader/find-verified-section wire-fixture-rscf WIRE_RSCF_SECTION_CONFIG slice [
	failures: failures + 1
]
if any [
	slice/size <> 64
	slice/record-count <> 1
	slice/record-size <> 64
	slice/offset <> 96
	slice/ordinal <> 1
][
	failures: failures + 1
]
unless wire-container-reader/checked-slice wire-fixture-rscf 160 96 64 slice [
	failures: failures + 1
]
if any [slice/offset <> 96 slice/ordinal <> 0][failures: failures + 1]
if wire-container-reader/checked-slice wire-fixture-rscf 160 150 20 slice [
	failures: failures + 1
]
code: wire-container-reader/verify (as byte-ptr! 0) -1 WIRE_MAGIC_RSCF result
if code <> WIRE_CONTAINER_ERROR_INVALID_ARGUMENTS [failures: failures + 1]
code: wire-container-reader/verify (as byte-ptr! 0) 64 WIRE_MAGIC_RSCF result
if code <> WIRE_CONTAINER_ERROR_INVALID_ARGUMENTS [failures: failures + 1]
code: wire-container-reader/verify wire-fixture-rscf 160 WIRE_MAGIC_RSCF (as wire-container-result! 0)
if code <> WIRE_CONTAINER_ERROR_INVALID_ARGUMENTS [failures: failures + 1]
if wire-container-reader/checked-slice wire-fixture-rscf 160 0 1 (as wire-section-slice! 0) [
	failures: failures + 1
]
if wire-container-reader/checked-slice (as byte-ptr! 0) 1 0 1 slice [
	failures: failures + 1
]
if wire-container-reader/find-verified-section
	wire-fixture-rscf WIRE_RSCF_SECTION_CONFIG (as wire-section-slice! 0)
[
	failures: failures + 1
]
if wire-container-reader/find-verified-section
	(as byte-ptr! 0) WIRE_RSCF_SECTION_CONFIG slice
[
	failures: failures + 1
]

either failures = 0 [
	print ["PASS: Red/System wire containers" lf]
][
	print ["FAIL: Red/System wire containers failures=" failures lf]
]
quit failures
}

target: %tests/wire-container-reds-test.reds
write target to binary! output
print ["Generated" target "with" length? positive "positive and" length? malformed "malformed fixtures"]
