Red [
	Title: "Generate Red/System RSCG relocation/import/export fixture tests"
]

generating-wire-rscg-relocation-fixtures?: true
do %tests/wire-rscg-relocation-test.red

word-name: func [value [word!]][lowercase copy form value]

append-binary: func [output [string!] prefix [string!] name [word!] data [binary!]][
	append output rejoin [prefix word-name name ": " mold/flat data newline]
]

output: make string! 4'194'304
source-bytes: make binary! 2'097'152
foreach source-file [
	%tests/wire-rscg-relocation-test.red
	%tests/wire-rscg-object-test.red
	%tests/wire-module-lifecycle-test.red
	%tests/wire-data-layout-test.red
	%tests/wire-file-source-test.red
	%tests/wire-string-table-test.red
	%tests/wire-container-test.red
	%generate-wire-rscg-relocation-fixtures.red
][append source-bytes read source-file]
append source-bytes to binary! mold schema/WIRE_SCHEMA_FINGERPRINT
source-digest: enbase/base checksum source-bytes 'SHA256 16

append output {Red/System [
	Title: "Generated RSCG relocation/import/export cross-language tests"
]

; Generated by tools/self_hosting/generate-wire-rscg-relocation-fixtures.red.
; Do not edit. Error codes and locations are frozen by the Red semantic corpus.
}
append output rejoin ["; Fixture source SHA256: " source-digest newline]
append output {
#include %../../../system/codegen/wire-rscg-relocation.reds

}

foreach fixture valid-rscg-relocations [
	append-binary output "relocation-valid-" fixture/1 fixture/2
]
foreach fixture malformed-rscg-relocations [
	append-binary output "relocation-invalid-" fixture/1 fixture/11
]

append output {
poison-memory: func [
	memory [byte-ptr!]
	size [integer!]
	/local cursor [byte-ptr!] remaining [integer!]
][
	cursor: memory
	remaining: size
	while [remaining > 0][
		cursor/1: as byte! 165
		cursor: cursor + 1
		remaining: remaining - 1
	]
]

memory-poisoned?: func [
	memory [byte-ptr!]
	size [integer!]
	return: [logic!]
	/local cursor [byte-ptr!] remaining [integer!]
][
	cursor: memory
	remaining: size
	while [remaining > 0][
		if cursor/1 <> as byte! 165 [return false]
		cursor: cursor + 1
		remaining: remaining - 1
	]
	true
]

poison-outputs: func [
	strings [wire-string-table!]
	files [wire-file-source!]
	layout [wire-data-layout!]
	modules [wire-module-lifecycle!]
	object-view [wire-rscg-object!]
	relocation-view [wire-rscg-relocation!]
][
	poison-memory as byte-ptr! strings size? wire-string-table!
	poison-memory as byte-ptr! files size? wire-file-source!
	poison-memory as byte-ptr! layout size? wire-data-layout!
	poison-memory as byte-ptr! modules size? wire-module-lifecycle!
	poison-memory as byte-ptr! object-view size? wire-rscg-object!
	poison-memory as byte-ptr! relocation-view size? wire-rscg-relocation!
]

outputs-poisoned?: func [
	strings [wire-string-table!]
	files [wire-file-source!]
	layout [wire-data-layout!]
	modules [wire-module-lifecycle!]
	object-view [wire-rscg-object!]
	relocation-view [wire-rscg-relocation!]
	return: [logic!]
][
	all [
		memory-poisoned? as byte-ptr! strings size? wire-string-table!
		memory-poisoned? as byte-ptr! files size? wire-file-source!
		memory-poisoned? as byte-ptr! layout size? wire-data-layout!
		memory-poisoned? as byte-ptr! modules size? wire-module-lifecycle!
		memory-poisoned? as byte-ptr! object-view size? wire-rscg-object!
		memory-poisoned? as byte-ptr! relocation-view size? wire-rscg-relocation!
	]
]

test-relocation: func [
	name [c-string!]
	data [byte-ptr!]
	size [integer!]
	expected-error expected-object expected-container expected-string expected-file
	expected-layout expected-module expected-offset expected-section expected-relocations
	expected-imports expected-exports expected-output-sections expected-symbols [integer!]
	return: [integer!]
	/local result [wire-rscg-relocation-result!]
		strings [wire-string-table!]
		files [wire-file-source!]
		layout [wire-data-layout!]
		modules [wire-module-lifecycle!]
		object-view [wire-rscg-object!]
		relocation-view [wire-rscg-relocation!]
		actual [integer!]
][
	result: declare wire-rscg-relocation-result!
	strings: declare wire-string-table!
	files: declare wire-file-source!
	layout: declare wire-data-layout!
	modules: declare wire-module-lifecycle!
	object-view: declare wire-rscg-object!
	relocation-view: declare wire-rscg-relocation!
	poison-outputs strings files layout modules object-view relocation-view
	actual: wire-rscg-relocation-reader/verify data size result strings files layout
		modules object-view relocation-view
	if actual <> expected-error [
		print ["FAIL: " name " expected=" expected-error " actual=" actual lf]
		return 1
	]
	if result/error <> expected-error [return 1]
	if result/object-error <> expected-object [
		print ["FAIL: " name " object=" result/object-error lf]
		return 1
	]
	if result/container-error <> expected-container [return 1]
	if result/string-error <> expected-string [return 1]
	if result/file-source-error <> expected-file [return 1]
	if result/data-layout-error <> expected-layout [return 1]
	if result/module-lifecycle-error <> expected-module [return 1]
	if any [
		result/error-offset <> expected-offset
		result/error-section <> expected-section
	][
		print [
			"FAIL: " name " location=" result/error-offset ":" result/error-section
			" expected=" expected-offset ":" expected-section lf
		]
		return 1
	]
	if expected-error <> WIRE_RSCG_RELOCATION_ERROR_SUCCESS [
		unless outputs-poisoned? strings files layout modules object-view relocation-view [
			print ["FAIL: " name " modified output views on failure" lf]
			return 1
		]
		return 0
	]
	if any [
		relocation-view/relocation-count <> expected-relocations
		relocation-view/import-count <> expected-imports
		relocation-view/export-count <> expected-exports
		relocation-view/relocation-record-size <> WIRE_RSCG_RELOCATION_SIZE
		relocation-view/import-record-size <> WIRE_IMPORT_SIZE
		relocation-view/export-record-size <> WIRE_EXPORT_SIZE
		object-view/output-section-count <> expected-output-sections
		object-view/symbol-count <> expected-symbols
	][
		print ["FAIL: " name " verified relocation view changed" lf]
		return 1
	]
	0
]

failures: 0
}

foreach fixture valid-rscg-relocations [
	verified: rscg-relocation-verifier/verify fixture/2
	append output rejoin [
		{failures: failures + (test-relocation "} form fixture/1 {" }
		"relocation-valid-" word-name fixture/1 " " length? fixture/2
		" 0 0 0 0 0 0 0 0 0 "
		verified/view/relocation-count " " verified/view/import-count " "
		verified/view/export-count " " verified/object-view/output-section-count " "
		verified/object-view/symbol-count ")" newline
	]
]

foreach fixture malformed-rscg-relocations [
	append output rejoin [
		{failures: failures + (test-relocation "} form fixture/1 {" }
		"relocation-invalid-" word-name fixture/1 " " length? fixture/11
		" " fixture/2 " " fixture/3 " " fixture/4 " " fixture/5
		" " fixture/6 " " fixture/7 " " fixture/8 " " fixture/9 " " fixture/10
		" -1 -1 -1 -1 -1)" newline
	]
]

append output rejoin [{

failures: failures + (test-relocation "NULL-DATA" (as byte-ptr! 0)
	} length? valid-rscg-relocation {
	WIRE_RSCG_RELOCATION_ERROR_INVALID_ARGUMENTS WIRE_RSCG_OBJECT_ERROR_SUCCESS
	WIRE_CONTAINER_ERROR_SUCCESS WIRE_STRING_TABLE_ERROR_SUCCESS
	WIRE_FILE_SOURCE_ERROR_SUCCESS WIRE_DATA_LAYOUT_ERROR_SUCCESS
	WIRE_MODULE_LIFECYCLE_ERROR_SUCCESS 0 0 -1 -1 -1 -1 -1)

failures: failures + (test-relocation "NEGATIVE-SIZE" relocation-valid-executable -1
	WIRE_RSCG_RELOCATION_ERROR_INVALID_ARGUMENTS WIRE_RSCG_OBJECT_ERROR_SUCCESS
	WIRE_CONTAINER_ERROR_SUCCESS WIRE_STRING_TABLE_ERROR_SUCCESS
	WIRE_FILE_SOURCE_ERROR_SUCCESS WIRE_DATA_LAYOUT_ERROR_SUCCESS
	WIRE_MODULE_LIFECYCLE_ERROR_SUCCESS 0 0 -1 -1 -1 -1 -1)

result: declare wire-rscg-relocation-result!
strings: declare wire-string-table!
files: declare wire-file-source!
layout: declare wire-data-layout!
modules: declare wire-module-lifecycle!
object-view: declare wire-rscg-object!
relocation-view: declare wire-rscg-relocation!
poison-outputs strings files layout modules object-view relocation-view
code: wire-rscg-relocation-reader/verify relocation-valid-executable }
length? valid-rscg-relocation {
	(as wire-rscg-relocation-result! 0) strings files layout modules object-view
	relocation-view
if code <> WIRE_RSCG_RELOCATION_ERROR_INVALID_ARGUMENTS [failures: failures + 1]
unless outputs-poisoned? strings files layout modules object-view relocation-view [
	failures: failures + 1
]

either failures = 0 [
	print ["PASS: Red/System RSCG relocation/import/export semantics" lf]
][
	print ["FAIL: Red/System RSCG relocation/import/export semantics failures=" failures lf]
]
quit failures
}]

target: %tests/wire-rscg-relocation-reds-test.reds
write target to binary! output
print [
	"Generated" target "with" length? valid-rscg-relocations "valid and"
	length? malformed-rscg-relocations "malformed fixtures"
]
