Red [
	Title: "Generate Red/System file and source metadata fixture tests"
]

generating-wire-file-source-fixtures?: true
do %tests/wire-file-source-test.red

word-name: func [value [word!]][lowercase copy form value]

append-binary: func [output [string!] prefix [string!] name [word!] data [binary!]][
	append output rejoin [prefix word-name name ": " mold/flat data newline]
]

output: make string! 196608
source-bytes: make binary! 131072
append source-bytes read %tests/wire-file-source-test.red
append source-bytes read %tests/wire-string-table-test.red
append source-bytes read %tests/wire-container-test.red
append source-bytes read %generate-wire-file-source-fixtures.red
append source-bytes to binary! mold schema/WIRE_SCHEMA_FINGERPRINT
source-digest: enbase/base checksum source-bytes 'SHA256 16

append output {Red/System [
	Title: "Generated file and source metadata cross-language tests"
]

; Generated by tools/self_hosting/generate-wire-file-source-fixtures.red.
; Do not edit. Error codes and locations are frozen by the Red semantic corpus.
}
append output rejoin ["; Fixture source SHA256: " source-digest newline]
append output {
#include %../../../system/codegen/wire-file-source.reds

}

foreach fixture valid-file-sources [
	append-binary output "metadata-valid-" fixture/1 fixture/3
]
foreach fixture malformed-file-sources [
	append-binary output "metadata-invalid-" fixture/1 fixture/8
]

append output {
poison-strings: func [strings [wire-string-table!]][
	strings/records: as byte-ptr! 101
	strings/record-count: -102
	strings/record-size: -103
	strings/records-offset: -104
	strings/records-ordinal: -105
	strings/data: as byte-ptr! 106
	strings/data-size: -107
	strings/data-offset: -108
	strings/data-ordinal: -109
]

strings-poisoned?: func [strings [wire-string-table!] return: [logic!]][
	all [
		strings/records = (as byte-ptr! 101)
		strings/record-count = -102
		strings/record-size = -103
		strings/records-offset = -104
		strings/records-ordinal = -105
		strings/data = (as byte-ptr! 106)
		strings/data-size = -107
		strings/data-offset = -108
		strings/data-ordinal = -109
	]
]

poison-view: func [view [wire-file-source!]][
	view/files: as byte-ptr! 201
	view/file-count: -202
	view/file-record-size: -203
	view/files-offset: -204
	view/files-ordinal: -205
	view/checksum-data: as byte-ptr! 206
	view/checksum-data-size: -207
	view/checksum-data-offset: -208
	view/checksum-data-ordinal: -209
	view/source-present: -210
	view/sources: as byte-ptr! 211
	view/source-count: -212
	view/source-record-size: -213
	view/source-offset: -214
	view/source-ordinal: -215
]

view-poisoned?: func [view [wire-file-source!] return: [logic!]][
	all [
		view/files = (as byte-ptr! 201)
		view/file-count = -202
		view/file-record-size = -203
		view/files-offset = -204
		view/files-ordinal = -205
		view/checksum-data = (as byte-ptr! 206)
		view/checksum-data-size = -207
		view/checksum-data-offset = -208
		view/checksum-data-ordinal = -209
		view/source-present = -210
		view/sources = (as byte-ptr! 211)
		view/source-count = -212
		view/source-record-size = -213
		view/source-offset = -214
		view/source-ordinal = -215
	]
]

test-file-source: func [
	name [c-string!]
	data [byte-ptr!]
	size magic expected-error expected-container expected-string
	expected-offset expected-section [integer!]
	return: [integer!]
	/local result [wire-file-source-result!] strings [wire-string-table!]
		view [wire-file-source!] actual [integer!]
][
	result: declare wire-file-source-result!
	strings: declare wire-string-table!
	view: declare wire-file-source!
	poison-strings strings
	poison-view view
	actual: wire-file-source-reader/verify data size magic result strings view
	if actual <> expected-error [
		print ["FAIL: " name " expected=" expected-error " actual=" actual lf]
		return 1
	]
	if result/error <> expected-error [
		print ["FAIL: " name " result/error=" result/error lf]
		return 1
	]
	if result/container-error <> expected-container [
		print [
			"FAIL: " name " container=" result/container-error
			" expected=" expected-container lf
		]
		return 1
	]
	if result/string-error <> expected-string [
		print [
			"FAIL: " name " string=" result/string-error
			" expected=" expected-string lf
		]
		return 1
	]
	if any [
		result/error-offset <> expected-offset
		result/error-section <> expected-section
	][
		print [
			"FAIL: " name
			" location=" result/error-offset ":" result/error-section
			" expected=" expected-offset ":" expected-section lf
		]
		return 1
	]
	if all [
		expected-error <> WIRE_FILE_SOURCE_ERROR_SUCCESS
		any [not strings-poisoned? strings not view-poisoned? view]
	][
		print ["FAIL: " name " modified output views on failure" lf]
		return 1
	]
	0
]

failures: 0
}

foreach fixture valid-file-sources [
	append output rejoin [
		{failures: failures + (test-file-source "} form fixture/1 {" }
		"metadata-valid-" word-name fixture/1 " " length? fixture/3 " " fixture/2 " "
		schema/WIRE_FILE_SOURCE_ERROR_SUCCESS " " schema/WIRE_CONTAINER_ERROR_SUCCESS
		" " schema/WIRE_STRING_TABLE_ERROR_SUCCESS " 0 0)" newline
	]
]

foreach fixture malformed-file-sources [
	append output rejoin [
		{failures: failures + (test-file-source "} form fixture/1 {" }
		"metadata-invalid-" word-name fixture/1 " " length? fixture/8 " " fixture/2 " "
		fixture/3 " " fixture/4 " " fixture/5 " " fixture/6 " " fixture/7 ")"
		newline
	]
]

rsir-view: file-source-verifier/verify metadata-rsir schema/WIRE_MAGIC_RSIR
rscg-view: file-source-verifier/verify metadata-rscg schema/WIRE_MAGIC_RSCG

append output rejoin [{
result: declare wire-file-source-result!
strings: declare wire-string-table!
view: declare wire-file-source!
code: wire-file-source-reader/verify
	metadata-valid-rsir-metadata } length? metadata-rsir {
	WIRE_MAGIC_RSIR result strings view
if code <> WIRE_FILE_SOURCE_ERROR_SUCCESS [failures: failures + 1]
if any [
	strings/record-count <> 3
	view/file-count <> 2
	view/file-record-size <> WIRE_FILE_SIZE
	view/files-offset <> } rsir-view/view/files-offset {
	view/files-ordinal <> } rsir-view/view/files-ordinal {
	view/checksum-data-size <> 32
	view/checksum-data-offset <> } rsir-view/view/checksum-data-offset {
	view/checksum-data-ordinal <> } rsir-view/view/checksum-data-ordinal {
	view/source-present <> 1
	view/source-count <> 3
	view/source-record-size <> WIRE_SOURCE_LOCATION_SIZE
	view/source-offset <> } rsir-view/view/source-offset {
	view/source-ordinal <> } rsir-view/view/source-ordinal {
][
	print ["FAIL: verified RSIR file/source view changed" lf]
	failures: failures + 1
]
if any [
	(wire-container-reader/read-i31 view/files WIRE_FILE_PATH_STRING_OFFSET) <> 2
	(as integer! view/checksum-data/1) <> 0
	(as integer! view/checksum-data/32) <> 31
	(wire-container-reader/read-i31 view/sources WIRE_SOURCE_LOCATION_FILE_OFFSET) <> 1
][failures: failures + 1]

code: wire-file-source-reader/verify
	metadata-valid-rscg-metadata } length? metadata-rscg {
	WIRE_MAGIC_RSCG result strings view
if code <> WIRE_FILE_SOURCE_ERROR_SUCCESS [failures: failures + 1]
if any [
	view/file-count <> 2
	view/source-present <> 0
	not null? view/sources
	view/source-count <> 0
	view/source-record-size <> WIRE_SOURCE_LOCATION_SIZE
	view/source-offset <> 0
	view/source-ordinal <> 0
][failures: failures + 1]

poison-strings strings
poison-view view
code: wire-file-source-reader/verify
	(as byte-ptr! 0) } length? metadata-rsir { WIRE_MAGIC_RSIR result strings view
if code <> WIRE_FILE_SOURCE_ERROR_INVALID_ARGUMENTS [failures: failures + 1]
if any [
	result/error <> WIRE_FILE_SOURCE_ERROR_INVALID_ARGUMENTS
	result/container-error <> WIRE_CONTAINER_ERROR_SUCCESS
	result/string-error <> WIRE_STRING_TABLE_ERROR_SUCCESS
	result/error-offset <> 0
	result/error-section <> 0
][failures: failures + 1]
unless strings-poisoned? strings [failures: failures + 1]
unless view-poisoned? view [failures: failures + 1]

code: wire-file-source-reader/verify
	metadata-valid-rsir-metadata -1 WIRE_MAGIC_RSIR result strings view
if code <> WIRE_FILE_SOURCE_ERROR_INVALID_ARGUMENTS [failures: failures + 1]
unless strings-poisoned? strings [failures: failures + 1]
unless view-poisoned? view [failures: failures + 1]

code: wire-file-source-reader/verify
	metadata-valid-rsir-metadata } length? metadata-rsir {
	WIRE_MAGIC_RSIR result (as wire-string-table! 0) view
if code <> WIRE_FILE_SOURCE_ERROR_INVALID_ARGUMENTS [failures: failures + 1]

code: wire-file-source-reader/verify
	metadata-valid-rsir-metadata } length? metadata-rsir {
	WIRE_MAGIC_RSIR result strings (as wire-file-source! 0)
if code <> WIRE_FILE_SOURCE_ERROR_INVALID_ARGUMENTS [failures: failures + 1]

code: wire-file-source-reader/verify
	metadata-valid-rsir-metadata } length? metadata-rsir { WIRE_MAGIC_RSIR
	(as wire-file-source-result! 0) strings view
if code <> WIRE_FILE_SOURCE_ERROR_INVALID_ARGUMENTS [failures: failures + 1]

poison-strings strings
poison-view view
code: wire-file-source-reader/verify
	metadata-valid-rsir-metadata } length? metadata-rsir { WIRE_MAGIC_RSDG result strings view
if code <> WIRE_FILE_SOURCE_ERROR_UNSUPPORTED_MESSAGE [failures: failures + 1]
if any [
	result/container-error <> WIRE_CONTAINER_ERROR_SUCCESS
	result/string-error <> WIRE_STRING_TABLE_ERROR_SUCCESS
	result/error-offset <> 0
	result/error-section <> 0
][failures: failures + 1]
unless strings-poisoned? strings [failures: failures + 1]
unless view-poisoned? view [failures: failures + 1]

either failures = 0 [
	print ["PASS: Red/System file/source metadata semantics" lf]
][
	print ["FAIL: Red/System file/source metadata semantics failures=" failures lf]
]
quit failures
}]

target: %tests/wire-file-source-reds-test.reds
write target to binary! output
print [
	"Generated" target
	"with" length? valid-file-sources "valid and"
	length? malformed-file-sources "malformed fixtures"
]
