Red [
	Title: "Generate the embedded red-toolchain resource archive"
	File:  %generate-toolchain-resources.red
]

fail: func [message [string! block!]][
	print ["*** Resource generation error:" form message]
	quit/return 1
]

join-file: func [base [file!] relative [file!] /local out][
	out: append copy base relative
	out
]

args: any [system/options/args copy []]
unless (length? args) = 2 [
	print "Usage: generate-toolchain-resources repo-root output.red"
	quit/return 2
]

repo-root: clean-path to file! args/1
unless (last repo-root) = #"/" [append repo-root #"/"]
output-file: clean-path to file! args/2
unless exists? join-file repo-root %compiler/bootstrap-boot.red [
	fail ["not a Red repository root: " repo-root]
]

resource-files: make block! 512
source-suffixes: [%.red %.reds %.r]
binary-suffixes: [%.ico %.icns %.plist]

include-resource?: func [path [file!] /local suffix][
	suffix: suffix? path
	to logic! any [find source-suffixes suffix find binary-suffixes suffix]
]

collect-directory: func [relative [file!] /local directory entries entry child absolute][
	directory: join-file repo-root relative
	unless dir? directory [fail ["resource directory not found: " relative]]
	entries: sort read directory
	foreach entry entries [
		child: join-file relative entry
		absolute: join-file repo-root child
		either dir? absolute [
			collect-directory child
		][
			if include-resource? child [append resource-files child]
		]
	]
]

foreach directory [
	%environment/
	%runtime/
	%system/runtime/
	%modules/
	%system/assets/
][collect-directory directory]

foreach file [
	%compiler/bootstrap-boot.red
	%utils/preprocessor.r
	%system/utils/libRedRT-exports.red
][
	unless exists? join-file repo-root file [fail ["resource file not found: " file]]
	append resource-files file
]

sort resource-files
resource-files: unique resource-files
records: make block! length? resource-files
archive: make binary! 2'000'000
canonical: make binary! 32'000
offset: 1
raw-total: 0

foreach file resource-files [
	data: read/binary join-file repo-root file
	raw-total: raw-total + length? data
	sha: lowercase enbase/base checksum data 'SHA256 16
	set/any 'compressed try [compress data 'crush]
	either all [
		binary? :compressed
		(length? compressed) < length? data
	][
		stored: compressed
		method: 'crush
	][
		stored: data
		method: 'raw
	]
	record: reduce [
		to string! file
		offset
		length? stored
		length? data
		method
		sha
	]
	append/only records record
	append archive stored
	repend canonical [
		to string! file #"^@" sha #"^@" form length? data #"^/"
	]
	offset: offset + length? stored
]

manifest-sha: lowercase enbase/base checksum canonical 'SHA256 16
generated: make string! ((length? archive) * 2) + 100'000
append generated {Red [
	Title: "Generated red-toolchain embedded resources"
	File:  %red-toolchain-resources.generated.red
]

; Generated by tools/self_hosting/generate-toolchain-resources.red.
; Do not edit by hand.
toolchain-resource-index: }
append generated mold records
append generated "^/^/toolchain-resource-manifest-sha256: "
append generated mold manifest-sha
append generated "^/^/toolchain-resource-data: "
append generated mold archive
append generated "^/"

output-dir: first split-path output-file
unless empty? output-dir [make-dir/deep output-dir]
write output-file generated
print [
	"Generated" output-file
	"resources:" length? records
	"raw bytes:" raw-total
	"archive bytes:" length? archive
	"manifest:" manifest-sha
]
quit/return 0
