Red [
	Title: "Generate Red/System RSIR symbol, import, and export fixture tests"
]

generating-wire-symbol-linkage-fixtures?: true
do %tests/wire-symbol-linkage-test.red

word-name: func [value [word!]][lowercase copy form value]

append-binary: func [output [string!] prefix [string!] name [word!] data [binary!]][
	append output rejoin [prefix word-name name ": " mold/flat data newline]
]

output: make string! 4'194'304
source-bytes: make binary! 1'048'576
foreach source-file [
	%tests/wire-symbol-linkage-test.red
	%tests/wire-function-signature-test.red
	%tests/wire-type-layout-test.red
	%tests/wire-file-source-test.red
	%tests/wire-string-table-test.red
	%tests/wire-container-test.red
	%generate-wire-symbol-linkage-fixtures.red
][append source-bytes read source-file]
append source-bytes to binary! mold schema/WIRE_SCHEMA_FINGERPRINT
source-digest: enbase/base checksum source-bytes 'SHA256 16

append output {Red/System [
	Title: "Generated RSIR symbol, import, and export cross-language tests"
]

; Generated by tools/self_hosting/generate-wire-symbol-linkage-fixtures.red.
; Do not edit. Error codes and locations are frozen by the Red semantic corpus.
}
append output rejoin ["; Fixture source SHA256: " source-digest newline]
append output {
#include %../../../system/codegen/wire-symbol-linkage.reds

}

foreach fixture valid-symbol-linkages [
	append-binary output "symbol-valid-" fixture/1 fixture/2
]
foreach fixture malformed-symbol-linkages [
	append-binary output "symbol-invalid-" fixture/1 fixture/12
]

append output {
poison-memory: func [
	memory [byte-ptr!]
	size [integer!]
	/local cursor [byte-ptr!] remaining [integer!]
][
	cursor: memory
	remaining: size
	while [remaining > 0][
		cursor/1: as byte! 165
		cursor: cursor + 1
		remaining: remaining - 1
	]
]

memory-poisoned?: func [
	memory [byte-ptr!]
	size [integer!]
	return: [logic!]
	/local cursor [byte-ptr!] remaining [integer!]
][
	cursor: memory
	remaining: size
	while [remaining > 0][
		if cursor/1 <> as byte! 165 [return false]
		cursor: cursor + 1
		remaining: remaining - 1
	]
	true
]

poison-outputs: func [
	strings [wire-string-table!]
	files [wire-file-source!]
	layout [wire-data-layout!]
	types [wire-type-layout!]
	functions [wire-function-signature!]
	modules [wire-module-lifecycle!]
	view [wire-symbol-linkage!]
][
	poison-memory as byte-ptr! strings size? wire-string-table!
	poison-memory as byte-ptr! files size? wire-file-source!
	poison-memory as byte-ptr! layout size? wire-data-layout!
	poison-memory as byte-ptr! types size? wire-type-layout!
	poison-memory as byte-ptr! functions size? wire-function-signature!
	poison-memory as byte-ptr! modules size? wire-module-lifecycle!
	poison-memory as byte-ptr! view size? wire-symbol-linkage!
]

outputs-poisoned?: func [
	strings [wire-string-table!]
	files [wire-file-source!]
	layout [wire-data-layout!]
	types [wire-type-layout!]
	functions [wire-function-signature!]
	modules [wire-module-lifecycle!]
	view [wire-symbol-linkage!]
	return: [logic!]
][
	all [
		memory-poisoned? as byte-ptr! strings size? wire-string-table!
		memory-poisoned? as byte-ptr! files size? wire-file-source!
		memory-poisoned? as byte-ptr! layout size? wire-data-layout!
		memory-poisoned? as byte-ptr! types size? wire-type-layout!
		memory-poisoned? as byte-ptr! functions size? wire-function-signature!
		memory-poisoned? as byte-ptr! modules size? wire-module-lifecycle!
		memory-poisoned? as byte-ptr! view size? wire-symbol-linkage!
	]
]

test-symbol-linkage: func [
	name [c-string!]
	data [byte-ptr!]
	size expected-error expected-container expected-string expected-file
	expected-layout expected-type expected-function expected-module
	expected-offset expected-section [integer!]
	return: [integer!]
	/local result [wire-symbol-linkage-result!]
		strings [wire-string-table!]
		files [wire-file-source!]
		layout [wire-data-layout!]
		types [wire-type-layout!]
		functions [wire-function-signature!]
		modules [wire-module-lifecycle!]
		view [wire-symbol-linkage!]
		actual [integer!]
][
	result: declare wire-symbol-linkage-result!
	strings: declare wire-string-table!
	files: declare wire-file-source!
	layout: declare wire-data-layout!
	types: declare wire-type-layout!
	functions: declare wire-function-signature!
	modules: declare wire-module-lifecycle!
	view: declare wire-symbol-linkage!
	poison-outputs strings files layout types functions modules view
	actual: wire-symbol-linkage-reader/verify data size result
		strings files layout types functions modules view
	if actual <> expected-error [
		print ["FAIL: " name " expected=" expected-error " actual=" actual lf]
		return 1
	]
	if result/error <> expected-error [
		print ["FAIL: " name " result/error=" result/error lf]
		return 1
	]
	if result/container-error <> expected-container [
		print ["FAIL: " name " container=" result/container-error lf]
		return 1
	]
	if result/string-error <> expected-string [
		print ["FAIL: " name " string=" result/string-error lf]
		return 1
	]
	if result/file-source-error <> expected-file [
		print ["FAIL: " name " file/source=" result/file-source-error lf]
		return 1
	]
	if result/data-layout-error <> expected-layout [
		print ["FAIL: " name " data-layout=" result/data-layout-error lf]
		return 1
	]
	if result/type-layout-error <> expected-type [
		print ["FAIL: " name " type-layout=" result/type-layout-error lf]
		return 1
	]
	if result/function-signature-error <> expected-function [
		print ["FAIL: " name " function/signature=" result/function-signature-error lf]
		return 1
	]
	if result/module-lifecycle-error <> expected-module [
		print ["FAIL: " name " module/lifecycle=" result/module-lifecycle-error lf]
		return 1
	]
	if any [
		result/error-offset <> expected-offset
		result/error-section <> expected-section
	][
		print [
			"FAIL: " name
			" location=" result/error-offset ":" result/error-section
			" expected=" expected-offset ":" expected-section lf
		]
		return 1
	]
	if all [
		expected-error <> WIRE_SYMBOL_LINKAGE_ERROR_SUCCESS
		not outputs-poisoned? strings files layout types functions modules view
	][
		print ["FAIL: " name " modified output views on failure" lf]
		return 1
	]
	0
]

failures: 0
}

foreach fixture valid-symbol-linkages [
	append output rejoin [
		{failures: failures + (test-symbol-linkage "} form fixture/1 {" }
		"symbol-valid-" word-name fixture/1 " " length? fixture/2
		" " schema/WIRE_SYMBOL_LINKAGE_ERROR_SUCCESS
		" " schema/WIRE_CONTAINER_ERROR_SUCCESS
		" " schema/WIRE_STRING_TABLE_ERROR_SUCCESS
		" " schema/WIRE_FILE_SOURCE_ERROR_SUCCESS
		" " schema/WIRE_DATA_LAYOUT_ERROR_SUCCESS
		" " schema/WIRE_TYPE_LAYOUT_ERROR_SUCCESS
		" " schema/WIRE_FUNCTION_SIGNATURE_ERROR_SUCCESS
		" " schema/WIRE_MODULE_LIFECYCLE_ERROR_SUCCESS
		" 0 0)" newline
	]
]

foreach fixture malformed-symbol-linkages [
	append output rejoin [
		{failures: failures + (test-symbol-linkage "} form fixture/1 {" }
		"symbol-invalid-" word-name fixture/1 " " length? fixture/12
		" " fixture/2 " " fixture/3 " " fixture/4 " " fixture/5
		" " fixture/6 " " fixture/7 " " fixture/8 " " fixture/9
		" " fixture/10 " " fixture/11 ")" newline
	]
]

verified: symbol-linkage-verifier/verify rich-symbol-message
append output rejoin [{

result: declare wire-symbol-linkage-result!
strings: declare wire-string-table!
files: declare wire-file-source!
layout: declare wire-data-layout!
types: declare wire-type-layout!
functions: declare wire-function-signature!
modules: declare wire-module-lifecycle!
view: declare wire-symbol-linkage!
code: wire-symbol-linkage-reader/verify
	symbol-valid-rich } length? rich-symbol-message {
	result strings files layout types functions modules view
if code <> WIRE_SYMBOL_LINKAGE_ERROR_SUCCESS [failures: failures + 1]
if any [
	strings/record-count <> 16
	files/file-count <> 0
	files/source-count <> 0
	layout/pointer-size <> 8
	types/type-count <> 2
	types/type-record-size <> WIRE_RSIR_TYPE_SIZE
	functions/signature-count <> 5
	functions/function-count <> 3
	functions/functions-offset <> } verified/functions/functions-offset {
	functions/functions-ordinal <> } verified/functions/functions-ordinal {
	modules/module-count <> 1
	modules/reference-count <> 3
	modules/image-kind <> WIRE_IMAGE_KIND_DYNAMIC_LIBRARY
	view/symbol-count <> 11
	view/symbol-record-size <> WIRE_RSIR_SYMBOL_SIZE
	view/symbols-offset <> } verified/view/symbols-offset {
	view/symbols-ordinal <> } verified/view/symbols-ordinal {
	view/global-count <> 1
	view/global-record-size <> WIRE_RSIR_GLOBAL_SIZE
	view/globals-offset <> } verified/view/globals-offset {
	view/globals-ordinal <> } verified/view/globals-ordinal {
	view/import-count <> 3
	view/import-record-size <> WIRE_IMPORT_SIZE
	view/imports-offset <> } verified/view/imports-offset {
	view/imports-ordinal <> } verified/view/imports-ordinal {
	view/export-count <> 2
	view/export-record-size <> WIRE_EXPORT_SIZE
	view/exports-offset <> } verified/view/exports-offset {
	view/exports-ordinal <> } verified/view/exports-ordinal {
	view/function-count <> 3
	view/module-kind <> WIRE_MODULE_KIND_USER
	view/image-kind <> WIRE_IMAGE_KIND_DYNAMIC_LIBRARY
][
	print ["FAIL: verified symbol/linkage view changed" lf]
	failures: failures + 1
]
if any [
	(wire-container-reader/read-i31 view/symbols WIRE_RSIR_SYMBOL_KIND_OFFSET)
		<> WIRE_SYMBOL_KIND_TYPE
	(wire-container-reader/read-i31 view/globals WIRE_RSIR_GLOBAL_SYMBOL_OFFSET) <> 10
	(wire-container-reader/read-i31 view/imports WIRE_IMPORT_SYMBOL_OFFSET) <> 5
	(wire-container-reader/read-i31 view/exports WIRE_EXPORT_SYMBOL_OFFSET) <> 2
][failures: failures + 1]

poison-outputs strings files layout types functions modules view
code: wire-symbol-linkage-reader/verify
	(as byte-ptr! 0) } length? rich-symbol-message {
	result strings files layout types functions modules view
if code <> WIRE_SYMBOL_LINKAGE_ERROR_INVALID_ARGUMENTS [failures: failures + 1]
if any [
	result/error <> WIRE_SYMBOL_LINKAGE_ERROR_INVALID_ARGUMENTS
	result/container-error <> WIRE_CONTAINER_ERROR_SUCCESS
	result/string-error <> WIRE_STRING_TABLE_ERROR_SUCCESS
	result/file-source-error <> WIRE_FILE_SOURCE_ERROR_SUCCESS
	result/data-layout-error <> WIRE_DATA_LAYOUT_ERROR_SUCCESS
	result/type-layout-error <> WIRE_TYPE_LAYOUT_ERROR_SUCCESS
	result/function-signature-error <> WIRE_FUNCTION_SIGNATURE_ERROR_SUCCESS
	result/module-lifecycle-error <> WIRE_MODULE_LIFECYCLE_ERROR_SUCCESS
	result/error-offset <> 0
	result/error-section <> 0
][failures: failures + 1]
unless outputs-poisoned? strings files layout types functions modules view [
	failures: failures + 1
]

code: wire-symbol-linkage-reader/verify symbol-valid-rich -1
	result strings files layout types functions modules view
if code <> WIRE_SYMBOL_LINKAGE_ERROR_INVALID_ARGUMENTS [failures: failures + 1]
unless outputs-poisoned? strings files layout types functions modules view [
	failures: failures + 1
]

code: wire-symbol-linkage-reader/verify symbol-valid-rich } length? rich-symbol-message {
	result (as wire-string-table! 0) files layout types functions modules view
if code <> WIRE_SYMBOL_LINKAGE_ERROR_INVALID_ARGUMENTS [failures: failures + 1]
code: wire-symbol-linkage-reader/verify symbol-valid-rich } length? rich-symbol-message {
	result strings (as wire-file-source! 0) layout types functions modules view
if code <> WIRE_SYMBOL_LINKAGE_ERROR_INVALID_ARGUMENTS [failures: failures + 1]
code: wire-symbol-linkage-reader/verify symbol-valid-rich } length? rich-symbol-message {
	result strings files (as wire-data-layout! 0) types functions modules view
if code <> WIRE_SYMBOL_LINKAGE_ERROR_INVALID_ARGUMENTS [failures: failures + 1]
code: wire-symbol-linkage-reader/verify symbol-valid-rich } length? rich-symbol-message {
	result strings files layout (as wire-type-layout! 0) functions modules view
if code <> WIRE_SYMBOL_LINKAGE_ERROR_INVALID_ARGUMENTS [failures: failures + 1]
code: wire-symbol-linkage-reader/verify symbol-valid-rich } length? rich-symbol-message {
	result strings files layout types (as wire-function-signature! 0) modules view
if code <> WIRE_SYMBOL_LINKAGE_ERROR_INVALID_ARGUMENTS [failures: failures + 1]
code: wire-symbol-linkage-reader/verify symbol-valid-rich } length? rich-symbol-message {
	result strings files layout types functions (as wire-module-lifecycle! 0) view
if code <> WIRE_SYMBOL_LINKAGE_ERROR_INVALID_ARGUMENTS [failures: failures + 1]
code: wire-symbol-linkage-reader/verify symbol-valid-rich } length? rich-symbol-message {
	result strings files layout types functions modules (as wire-symbol-linkage! 0)
if code <> WIRE_SYMBOL_LINKAGE_ERROR_INVALID_ARGUMENTS [failures: failures + 1]
code: wire-symbol-linkage-reader/verify symbol-valid-rich } length? rich-symbol-message {
	(as wire-symbol-linkage-result! 0) strings files layout types functions modules view
if code <> WIRE_SYMBOL_LINKAGE_ERROR_INVALID_ARGUMENTS [failures: failures + 1]

either failures = 0 [
	print ["PASS: Red/System RSIR symbol/linkage semantics" lf]
][
	print ["FAIL: Red/System RSIR symbol/linkage semantics failures=" failures lf]
]
quit failures
}]

target: %tests/wire-symbol-linkage-reds-test.reds
write target to binary! output
print [
	"Generated" target
	"with" length? valid-symbol-linkages "valid and"
	length? malformed-symbol-linkages "malformed fixtures"
]
