Red [
	Title: "Generate Red/System diagnostic semantic fixture tests"
]

generating-wire-diagnostic-fixtures?: true
do %tests/wire-diagnostics-test.red

word-name: func [value [word!]][lowercase copy form value]

append-binary: func [output [string!] prefix [string!] name [word!] data [binary!]][
	append output rejoin [prefix word-name name ": " mold/flat data newline]
]

output: make string! 262144
source-bytes: make binary! 131072
append source-bytes read %tests/wire-diagnostics-test.red
append source-bytes read %tests/wire-string-table-test.red
append source-bytes read %tests/wire-container-test.red
append source-bytes read %generate-wire-diagnostic-fixtures.red
append source-bytes to binary! mold schema/WIRE_SCHEMA_FINGERPRINT
source-digest: enbase/base checksum source-bytes 'SHA256 16

append output {Red/System [
	Title: "Generated diagnostic cross-language tests"
]

; Generated by tools/self_hosting/generate-wire-diagnostic-fixtures.red.
; Do not edit. Error codes and locations are frozen by the Red semantic corpus.
}
append output rejoin ["; Fixture source SHA256: " source-digest newline]
append output {
#include %../../../system/codegen/wire-diagnostics.reds

}

foreach fixture valid-diagnostics [
	append-binary output "diagnostic-valid-" fixture/1 fixture/3
]
foreach fixture malformed-diagnostics [
	append-binary output "diagnostic-invalid-" fixture/1 fixture/7
]

append output {
poison-strings: func [strings [wire-string-table!]][
	strings/records: as byte-ptr! 101
	strings/record-count: -102
	strings/record-size: -103
	strings/records-offset: -104
	strings/records-ordinal: -105
	strings/data: as byte-ptr! 106
	strings/data-size: -107
	strings/data-offset: -108
	strings/data-ordinal: -109
]

strings-poisoned?: func [strings [wire-string-table!] return: [logic!]][
	all [
		strings/records = (as byte-ptr! 101)
		strings/record-count = -102
		strings/record-size = -103
		strings/records-offset = -104
		strings/records-ordinal = -105
		strings/data = (as byte-ptr! 106)
		strings/data-size = -107
		strings/data-offset = -108
		strings/data-ordinal = -109
	]
]

poison-view: func [view [wire-diagnostics!]][
	view/status: -201
	view/records: as byte-ptr! 202
	view/record-count: -203
	view/record-size: -204
	view/records-offset: -205
	view/records-ordinal: -206
]

view-poisoned?: func [view [wire-diagnostics!] return: [logic!]][
	all [
		view/status = -201
		view/records = (as byte-ptr! 202)
		view/record-count = -203
		view/record-size = -204
		view/records-offset = -205
		view/records-ordinal = -206
	]
]

test-diagnostic: func [
	name [c-string!]
	data [byte-ptr!]
	size expected-status expected-error expected-container expected-string
	expected-offset expected-section [integer!]
	return: [integer!]
	/local result [wire-diagnostic-result!] strings [wire-string-table!]
		view [wire-diagnostics!] actual [integer!]
][
	result: declare wire-diagnostic-result!
	strings: declare wire-string-table!
	view: declare wire-diagnostics!
	poison-strings strings
	poison-view view
	actual: wire-diagnostic-reader/verify
		data size WIRE_MAGIC_RSDG result strings view
	if actual <> expected-error [
		print ["FAIL: " name " expected=" expected-error " actual=" actual lf]
		return 1
	]
	if result/error <> expected-error [
		print ["FAIL: " name " result/error=" result/error lf]
		return 1
	]
	if result/container-error <> expected-container [
		print [
			"FAIL: " name " container=" result/container-error
			" expected=" expected-container lf
		]
		return 1
	]
	if result/string-error <> expected-string [
		print [
			"FAIL: " name " string=" result/string-error
			" expected=" expected-string lf
		]
		return 1
	]
	if any [
		result/error-offset <> expected-offset
		result/error-section <> expected-section
	][
		print [
			"FAIL: " name
			" location=" result/error-offset ":" result/error-section
			" expected=" expected-offset ":" expected-section lf
		]
		return 1
	]
	either expected-error = WIRE_DIAGNOSTIC_ERROR_SUCCESS [
		if view/status <> expected-status [
			print [
				"FAIL: " name " status=" view/status
				" expected=" expected-status lf
			]
			return 1
		]
	][
		if any [not strings-poisoned? strings not view-poisoned? view][
			print ["FAIL: " name " modified output views on failure" lf]
			return 1
		]
	]
	0
]

failures: 0
}

foreach fixture valid-diagnostics [
	append output rejoin [
		{failures: failures + (test-diagnostic "} form fixture/1 {" }
		"diagnostic-valid-" word-name fixture/1 " " length? fixture/3 " "
		fixture/2 " " schema/WIRE_DIAGNOSTIC_ERROR_SUCCESS " "
		schema/WIRE_CONTAINER_ERROR_SUCCESS " "
		schema/WIRE_STRING_TABLE_ERROR_SUCCESS " 0 0)" newline
	]
]

foreach fixture malformed-diagnostics [
	append output rejoin [
		{failures: failures + (test-diagnostic "} form fixture/1 {" }
		"diagnostic-invalid-" word-name fixture/1 " " length? fixture/7 " 0 "
		fixture/2 " " fixture/3 " " fixture/4 " " fixture/5 " " fixture/6 ")"
		newline
	]
]

base-view: diagnostic-verifier/verify
	invalid-arguments-diagnostic schema/WIRE_MAGIC_RSDG
order-view: diagnostic-verifier/verify ordered-diagnostic schema/WIRE_MAGIC_RSDG

append output rejoin [{
result: declare wire-diagnostic-result!
strings: declare wire-string-table!
view: declare wire-diagnostics!
slice: declare wire-string-slice!
code: wire-diagnostic-reader/verify
	diagnostic-valid-invalid-arguments } length? invalid-arguments-diagnostic {
	WIRE_MAGIC_RSDG result strings view
if code <> WIRE_DIAGNOSTIC_ERROR_SUCCESS [failures: failures + 1]
if any [
	view/status <> WIRE_STATUS_INVALID_ARGUMENTS
	view/record-count <> 1
	view/record-size <> WIRE_RSDG_DIAGNOSTIC_SIZE
	view/records-offset <> } base-view/view/records-offset {
	view/records-ordinal <> } base-view/view/records-ordinal {
	strings/record-count <> 3
][
	print ["FAIL: verified diagnostic view changed" lf]
	failures: failures + 1
]
if (wire-container-reader/read-i31
	view/records WIRE_RSDG_DIAGNOSTIC_STATUS_OFFSET) <> WIRE_STATUS_INVALID_ARGUMENTS
[
	failures: failures + 1
]
unless wire-string-table-reader/get-slice strings 2 slice [failures: failures + 1]
if any [
	slice/size <> 5
	slice/data/1 <> as byte! 101
	slice/data/5 <> as byte! 114
][failures: failures + 1]

code: wire-diagnostic-reader/verify
	diagnostic-valid-producer-order } length? ordered-diagnostic {
	WIRE_MAGIC_RSDG result strings view
if code <> WIRE_DIAGNOSTIC_ERROR_SUCCESS [failures: failures + 1]
if view/record-count <> 3 [failures: failures + 1]
if (wire-container-reader/read-i31
	view/records WIRE_RSDG_DIAGNOSTIC_MESSAGE_STRING_OFFSET) <> 3
[
	failures: failures + 1
]
if (wire-container-reader/read-i31
	(view/records + WIRE_RSDG_DIAGNOSTIC_SIZE)
	WIRE_RSDG_DIAGNOSTIC_MESSAGE_STRING_OFFSET) <> 2
[
	failures: failures + 1
]
if (wire-container-reader/read-i31
	(view/records + (WIRE_RSDG_DIAGNOSTIC_SIZE * 2))
	WIRE_RSDG_DIAGNOSTIC_MESSAGE_STRING_OFFSET) <> 3
[
	failures: failures + 1
]

poison-strings strings
poison-view view
code: wire-diagnostic-reader/verify
	(as byte-ptr! 0) } length? invalid-arguments-diagnostic {
	WIRE_MAGIC_RSDG result strings view
if code <> WIRE_DIAGNOSTIC_ERROR_INVALID_ARGUMENTS [failures: failures + 1]
unless strings-poisoned? strings [failures: failures + 1]
unless view-poisoned? view [failures: failures + 1]

code: wire-diagnostic-reader/verify
	diagnostic-valid-invalid-arguments -1
	WIRE_MAGIC_RSDG result strings view
if code <> WIRE_DIAGNOSTIC_ERROR_INVALID_ARGUMENTS [failures: failures + 1]
unless strings-poisoned? strings [failures: failures + 1]
unless view-poisoned? view [failures: failures + 1]

code: wire-diagnostic-reader/verify
	diagnostic-valid-invalid-arguments } length? invalid-arguments-diagnostic {
	WIRE_MAGIC_RSDG result (as wire-string-table! 0) view
if code <> WIRE_DIAGNOSTIC_ERROR_INVALID_ARGUMENTS [failures: failures + 1]

code: wire-diagnostic-reader/verify
	diagnostic-valid-invalid-arguments } length? invalid-arguments-diagnostic {
	WIRE_MAGIC_RSDG result strings (as wire-diagnostics! 0)
if code <> WIRE_DIAGNOSTIC_ERROR_INVALID_ARGUMENTS [failures: failures + 1]

code: wire-diagnostic-reader/verify
	diagnostic-valid-invalid-arguments } length? invalid-arguments-diagnostic {
	WIRE_MAGIC_RSDG (as wire-diagnostic-result! 0) strings view
if code <> WIRE_DIAGNOSTIC_ERROR_INVALID_ARGUMENTS [failures: failures + 1]

poison-strings strings
poison-view view
code: wire-diagnostic-reader/verify
	diagnostic-valid-invalid-arguments } length? invalid-arguments-diagnostic {
	WIRE_MAGIC_RSIR result strings view
if code <> WIRE_DIAGNOSTIC_ERROR_UNSUPPORTED_MESSAGE [failures: failures + 1]
if any [
	result/container-error <> WIRE_CONTAINER_ERROR_SUCCESS
	result/string-error <> WIRE_STRING_TABLE_ERROR_SUCCESS
	result/error-offset <> 0
	result/error-section <> 0
][failures: failures + 1]
unless strings-poisoned? strings [failures: failures + 1]
unless view-poisoned? view [failures: failures + 1]

either failures = 0 [
	print ["PASS: Red/System diagnostic semantics" lf]
][
	print ["FAIL: Red/System diagnostic semantics failures=" failures lf]
]
quit failures
}]

target: %tests/wire-diagnostics-reds-test.reds
write target to binary! output
print [
	"Generated" target
	"with" length? valid-diagnostics "valid and"
	length? malformed-diagnostics "malformed fixtures"
]
