Red [
	Title: "Hybrid compiler wire schema specification"
	File:  %wire-schema-spec.red
]

; This is the single source for generated Red and Red/System wire constants.
; Numeric values may change while docs/compiler-wire-format.md is a draft.
compiler-wire-schema-spec: [
	version [
		major 1
		minor 0
	]

	magics [
		RSIR "RSIR"
		RSCF "RSCF"
		RSCG "RSCG"
		RSDG "RSDG"
	]

	enums [
		TARGET [
			NONE 0
			X86_64 1
			ARM64 2
			ARM32 3
			X86 4
		]

		ABI [
			NONE 0
			WIN64 1
			SYSV_X64 2
			AAPCS64 3
			AAPCS32 4
			WIN32 5
		]

		ENDIAN [
			NONE 0
			LITTLE 1
			BIG 2
		]

		SECTION_FLAG [
			OPTIONAL 1
			SORTED 2
			DEDUPLICATED 4
		]

		SECTION_CARDINALITY [
			ANY 0
			ONE 1
			NONEMPTY 2
		]

		RSCF_SECTION [
			CONFIG 1
		]

		RSIR_SECTION [
			MODULE 1
			DATA_LAYOUT 2
			STRINGS 3
			STRING_DATA 4
			FILES 5
			TYPES 6
			FIELDS 7
			SIGNATURES 8
			PARAMETERS 9
			SYMBOLS 10
			CONSTANTS 11
			CONSTANT_DATA 12
			CONSTANT_PARTS 13
			GLOBALS 14
			IMPORTS 15
			EXPORTS 16
			FUNCTIONS 17
			LOCALS 18
			BLOCKS 19
			EDGES 20
			VALUES 21
			INSTRUCTIONS 22
			OPERANDS 23
			CALLS 24
			TARGET_FRAGMENTS 25
			SOURCE_LOCATIONS 26
			EXCEPTION_REGIONS 27
			EXCEPTION_BLOCKS 28
		]

		RSCG_SECTION [
			DATA_LAYOUT 1
			STRINGS 2
			STRING_DATA 3
			OUTPUT_SECTIONS 4
			OUTPUT_DATA 5
			SYMBOLS 6
			RELOCATIONS 7
			IMPORTS 8
			EXPORTS 9
			FUNCTIONS 10
			FILES 11
			DEBUG_LINES 12
			DEBUG_PARAMETERS 13
			GC_FRAMES 14
			UNWIND_FUNCTIONS 15
		]

		RSDG_SECTION [
			STRINGS 1
			STRING_DATA 2
			DIAGNOSTICS 3
		]

		CONFIG_FLAG [
			DEBUG 1
			PIC 2
			DETERMINISTIC 4
			RUNTIME_MODULE 8
		]

		CODE_MODEL [
			SMALL 1
		]

		RELOCATION_MODEL [
			STATIC 1
			PIC 2
		]

		DEBUG_FORMAT [
			NONE 0
			RED 1
		]

		TYPE_KIND [
			VOID 1
			LOGIC 2
			INTEGER 3
			FLOAT 4
			POINTER 5
			FUNCTION 6
			STRUCT 7
			UNION 8
			ARRAY 9
			OPAQUE 10
			MANAGED_HANDLE 11
		]

		TYPE_FLAG [
			SIGNED 1
			VOLATILE 2
			PACKED 4
			NOMINAL 8
		]

		GC_KIND [
			NONE 0
			POINTER 1
			HANDLE 2
		]

		SYMBOL_KIND [
			FUNCTION 1
			GLOBAL 2
			CONSTANT 3
			TYPE 4
		]

		LINKAGE [
			LOCAL 1
			INTERNAL 2
			EXTERNAL 3
			IMPORT 4
			WEAK 5
		]

		VISIBILITY [
			DEFAULT 1
			HIDDEN 2
		]

		CALLING_CONVENTION [
			RED_SYSTEM 1
			CDECL 2
			STDCALL 3
			SYSCALL 4
		]

		FUNCTION_FLAG [
			VARIADIC 1
			TYPED 2
			CUSTOM 4
			CALLBACK 8
			RED_INTERNAL 16
			NO_RETURN 32
			MAY_THROW 64
		]

		LOCAL_KIND [
			ARGUMENT 1
			LOCAL 2
			TEMPORARY 3
			MERGE 4
		]

		EDGE_KIND [
			NORMAL 1
			TRUE 2
			FALSE 3
			SWITCH_CASE 4
			DEFAULT 5
			EXCEPTION 6
			UNREACHABLE 7
		]

		VALUE_DEFINITION [
			PARAMETER 1
			INSTRUCTION 2
		]

		OPERAND_KIND [
			VALUE 1
			CONSTANT 2
			SYMBOL 3
			BLOCK 4
			LOCAL 5
			TYPE 6
			FUNCTION 7
			TARGET_FRAGMENT 8
		]

		CALL_KIND [
			DIRECT 1
			INDIRECT 2
			IMPORT 3
			SYSCALL 4
			CUSTOM 5
			SUBROUTINE 6
		]

		EFFECT_FLAG [
			READ 1
			WRITE 2
			CALL 4
			VOLATILE 8
			ATOMIC 16
			MAY_TRAP 32
			THROW 64
			SAFEPOINT 128
			CONTROL 256
			STACK 512
			OPAQUE 1024
		]

		ALIAS_KIND [
			NONE 0
			UNIVERSAL 1
			LOCAL 2
			GLOBAL 3
		]

		OPCODE [
			CONSTANT 1
			COPY 2
			CONVERT 3
			BITCAST 4
			ADD 5
			SUBTRACT 6
			MULTIPLY 7
			DIVIDE 8
			REMAINDER 9
			MODULO 10
			NEGATE 11
			BIT_NOT 12
			LOGIC_NOT 13
			SHIFT_LEFT 14
			SHIFT_RIGHT 15
			SHIFT_RIGHT_LOGICAL 16
			BIT_AND 17
			BIT_OR 18
			BIT_XOR 19
			COMPARE 20
			LOAD_LOCAL 21
			STORE_LOCAL 22
			ADDRESS_LOCAL 23
			LOAD_GLOBAL 24
			STORE_GLOBAL 25
			ADDRESS_GLOBAL 26
			LOAD_INDIRECT 27
			STORE_INDIRECT 28
			ADDRESS_FIELD 29
			AGGREGATE_BUILD 30
			AGGREGATE_COPY 31
			ATOMIC_LOAD 32
			ATOMIC_STORE 33
			ATOMIC_RMW 34
			ATOMIC_CAS 35
			ATOMIC_FENCE 36
			CALL 37
			BRANCH 38
			JUMP 39
			SWITCH 40
			RETURN 41
			THROW 42
			CATCH_ENTER 43
			CATCH_LEAVE 44
			UNREACHABLE 45
			KEEPALIVE 46
			STACK_ALLOC 47
			STACK_FREE 48
			STACK_PUSH 49
			STACK_POP 50
			PUSH_ALL 51
			POP_ALL 52
			PORT_READ 53
			PORT_WRITE 54
			GET_PC 55
			TARGET_FRAGMENT 56
		]

		COMPARE_KIND [
			EQUAL 1
			NOT_EQUAL 2
			LESS 3
			GREATER 4
			LESS_EQUAL 5
			GREATER_EQUAL 6
		]

		ATOMIC_ORDER [
			RELAXED 1
			ACQUIRE 2
			RELEASE 3
			ACQUIRE_RELEASE 4
			SEQUENTIAL 5
		]

		OUTPUT_SECTION_CLASS [
			CODE 1
			RODATA 2
			DATA 3
			BSS 4
			PLATFORM 5
		]

		SYMBOL_BINDING [
			LOCAL 1
			GLOBAL 2
			WEAK 3
		]

		RELOCATION_KIND [
			X64_REL32 1
			X64_RIP_REL32 2
			ABSOLUTE32 3
			ABSOLUTE64 4
		]

		CONTAINER_ERROR [
			SUCCESS 0
			INVALID_ARGUMENTS 1
			TRUNCATED_HEADER 2
			BAD_MAGIC 3
			UNSUPPORTED_VERSION 4
			BAD_HEADER_SIZE 5
			BAD_CONTAINER_FLAGS 6
			BAD_TOTAL_SIZE 7
			SCALAR_RANGE 8
			BAD_SCHEMA_FINGERPRINT 9
			BAD_TARGET 10
			BAD_ABI 11
			BAD_ENDIAN 12
			BAD_POINTER_SIZE 13
			BAD_DIRECTORY_OFFSET 14
			BAD_DIRECTORY_RECORD_SIZE 15
			DIRECTORY_RANGE 16
			SECTION_ORDER 17
			BAD_SECTION_FLAGS 18
			UNKNOWN_REQUIRED_SECTION 19
			BAD_RECORD_SIZE 20
			SECTION_PRODUCT 21
			BAD_ALIGNMENT 22
			EMPTY_SECTION_OFFSET 23
			SECTION_RANGE 24
			PAYLOAD_ORDER 25
			NONZERO_RESERVED 26
			NONZERO_PADDING 27
			MISSING_REQUIRED_SECTION 28
			BAD_SECTION_CARDINALITY 29
		]

		STATUS [
			SUCCESS 0
			INVALID_ARGUMENTS 1
			INVALID_CONFIGURATION 2
			INVALID_RSIR 3
			UNSUPPORTED_TARGET 4
			CODEGEN_FAILURE 5
			INVALID_ARTIFACT 6
		]

		DIAGNOSTIC_SEVERITY [
			NOTE 1
			WARNING 2
			ERROR 3
			FATAL 4
		]

		DIAGNOSTIC_PHASE [
			BRIDGE 1
			CONFIGURATION 2
			DECODE 3
			VERIFY 4
			OPTIMIZE 5
			SELECT 6
			ALLOCATE 7
			ENCODE 8
			ARTIFACT 9
		]
	]

	profiles [
		RSCF [
			CONFIG RSCF_CONFIG REQUIRED ONE 4
		]

		RSIR [
			MODULE RSIR_MODULE REQUIRED ONE 4
			DATA_LAYOUT DATA_LAYOUT REQUIRED ONE 4
			STRINGS STRING REQUIRED ANY 4
			STRING_DATA BYTE REQUIRED ANY 1
			FILES FILE REQUIRED ANY 4
			TYPES RSIR_TYPE REQUIRED ANY 4
			FIELDS RSIR_FIELD REQUIRED ANY 4
			SIGNATURES RSIR_SIGNATURE REQUIRED ANY 4
			PARAMETERS RSIR_PARAMETER REQUIRED ANY 4
			SYMBOLS RSIR_SYMBOL REQUIRED ANY 4
			CONSTANTS RSIR_CONSTANT REQUIRED ANY 4
			CONSTANT_DATA BYTE REQUIRED ANY 1
			CONSTANT_PARTS RSIR_CONSTANT_PART REQUIRED ANY 4
			GLOBALS RSIR_GLOBAL REQUIRED ANY 4
			IMPORTS IMPORT REQUIRED ANY 4
			EXPORTS EXPORT REQUIRED ANY 4
			FUNCTIONS RSIR_FUNCTION REQUIRED ANY 4
			LOCALS RSIR_LOCAL REQUIRED ANY 4
			BLOCKS RSIR_BLOCK REQUIRED ANY 4
			EDGES RSIR_EDGE REQUIRED ANY 4
			VALUES RSIR_VALUE REQUIRED ANY 4
			INSTRUCTIONS RSIR_INSTRUCTION REQUIRED ANY 4
			OPERANDS RSIR_OPERAND REQUIRED ANY 4
			CALLS RSIR_CALL REQUIRED ANY 4
			TARGET_FRAGMENTS RSIR_TARGET_FRAGMENT REQUIRED ANY 4
			SOURCE_LOCATIONS SOURCE_LOCATION REQUIRED ANY 4
			EXCEPTION_REGIONS RSIR_EXCEPTION_REGION REQUIRED ANY 4
			EXCEPTION_BLOCKS RSIR_EXCEPTION_BLOCK REQUIRED ANY 4
		]

		RSCG [
			DATA_LAYOUT DATA_LAYOUT REQUIRED ONE 4
			STRINGS STRING REQUIRED ANY 4
			STRING_DATA BYTE REQUIRED ANY 1
			OUTPUT_SECTIONS RSCG_OUTPUT_SECTION REQUIRED ANY 4
			OUTPUT_DATA BYTE REQUIRED ANY 1
			SYMBOLS RSCG_SYMBOL REQUIRED ANY 4
			RELOCATIONS RSCG_RELOCATION REQUIRED ANY 4
			IMPORTS IMPORT REQUIRED ANY 4
			EXPORTS EXPORT REQUIRED ANY 4
			FUNCTIONS RSCG_FUNCTION REQUIRED ANY 4
			FILES FILE REQUIRED ANY 4
			DEBUG_LINES RSCG_DEBUG_LINE REQUIRED ANY 4
			DEBUG_PARAMETERS RSCG_DEBUG_PARAMETER REQUIRED ANY 4
			GC_FRAMES RSCG_GC_FRAME REQUIRED ANY 4
			UNWIND_FUNCTIONS RSCG_UNWIND_FUNCTION OPTIONAL ANY 4
		]

		RSDG [
			STRINGS STRING REQUIRED ANY 4
			STRING_DATA BYTE REQUIRED ANY 1
			DIAGNOSTICS RSDG_DIAGNOSTIC REQUIRED NONEMPTY 4
		]
	]

	records [
		HEADER [
			size 64
			fields [
				MAGIC 0 4
				VERSION_MAJOR 4 2
				VERSION_MINOR 6 2
				HEADER_SIZE 8 4
				CONTAINER_FLAGS 12 4
				TOTAL_SIZE 16 4
				SECTION_COUNT 20 4
				DIRECTORY_OFFSET 24 4
				DIRECTORY_RECORD_SIZE 28 4
				TARGET 32 4
				ABI 36 4
				TARGET_ENDIAN 40 4
				POINTER_SIZE 44 4
				FEATURE_MASK_LOW 48 4
				FEATURE_MASK_HIGH 52 4
				PRODUCER_BUILD 56 4
				SCHEMA_FINGERPRINT 60 4
			]
		]

		DIRECTORY [
			size 32
			fields [
				KIND 0 4
				FLAGS 4 4
				PAYLOAD_OFFSET 8 4
				PAYLOAD_SIZE 12 4
				RECORD_COUNT 16 4
				RECORD_SIZE 20 4
				ALIGNMENT 24 4
				RESERVED 28 4
			]
		]

		RSCF_CONFIG [
			size 64
			fields [
				OPTIMIZATION_LEVEL 0 4
				FLAGS 4 4
				CODE_MODEL 8 4
				RELOCATION_MODEL 12 4
				DEBUG_FORMAT 16 4
				CPU_BASELINE 20 4
				CPU_FEATURES_LOW 24 4
				CPU_FEATURES_HIGH 28 4
				MAX_OUTPUT_BYTES 32 4
				MAX_DIAGNOSTIC_BYTES 36 4
				WORKER_COUNT 40 4
				DETERMINISTIC_SEED 44 4
				RESERVED_0 48 4
				RESERVED_1 52 4
				RESERVED_2 56 4
				RESERVED_3 60 4
			]
		]

		RSDG_DIAGNOSTIC [
			size 40
			fields [
				STATUS 0 4
				SEVERITY 4 4
				PHASE 8 4
				MESSAGE_STRING 12 4
				FILE 16 4
				LINE 20 4
				COLUMN 24 4
				FUNCTION_SYMBOL 28 4
				INSTRUCTION 32 4
				FLAGS 36 4
			]
		]

		STRING [
			size 8
			fields [
				OFFSET 0 4
				SIZE 4 4
			]
		]

		FILE [
			size 16
			fields [
				PATH_STRING 0 4
				CHECKSUM_KIND 4 4
				CHECKSUM_OFFSET 8 4
				CHECKSUM_SIZE 12 4
			]
		]

		DATA_LAYOUT [
			size 32
			fields [
				ADDRESS_UNIT 0 4
				POINTER_SIZE 4 4
				POINTER_ALIGNMENT 8 4
				STACK_ALIGNMENT 12 4
				MAX_SCALAR_ALIGNMENT 16 4
				AGGREGATE_ALIGNMENT 20 4
				INTEGER_REGISTER_WIDTH 24 4
				FLAGS 28 4
			]
		]

		RSIR_MODULE [
			size 32
			fields [
				NAME_STRING 0 4
				FLAGS 4 4
				INITIALIZER_FUNCTION 8 4
				FINALIZER_FUNCTION 12 4
				ENTRY_FUNCTION 16 4
				INITIALIZATION_PRIORITY 20 4
				SOURCE_LOCATION 24 4
				RESERVED 28 4
			]
		]

		RSIR_TYPE [
			size 40
			fields [
				KIND 0 4
				FLAGS 4 4
				SIZE 8 4
				ALIGNMENT 12 4
				NAME_STRING 16 4
				ELEMENT_TYPE 20 4
				ELEMENT_COUNT 24 4
				FIRST_FIELD 28 4
				FIELD_COUNT 32 4
				GC_KIND 36 4
			]
		]

		RSIR_FIELD [
			size 32
			fields [
				OWNER_TYPE 0 4
				NAME_STRING 4 4
				TYPE 8 4
				BYTE_OFFSET 12 4
				FLAGS 16 4
				ORDINAL 20 4
				SOURCE_LOCATION 24 4
				RESERVED 28 4
			]
		]

		RSIR_SIGNATURE [
			size 32
			fields [
				CALLING_CONVENTION 0 4
				FLAGS 4 4
				RETURN_TYPE 8 4
				FIRST_PARAMETER 12 4
				PARAMETER_COUNT 16 4
				LOGICAL_ARITY 20 4
				SOURCE_LOCATION 24 4
				RESERVED 28 4
			]
		]

		RSIR_PARAMETER [
			size 32
			fields [
				SIGNATURE 0 4
				NAME_STRING 4 4
				TYPE 8 4
				FLAGS 12 4
				ORDINAL 16 4
				DEBUG_TYPE_CODE 20 4
				SOURCE_LOCATION 24 4
				RESERVED 28 4
			]
		]

		RSIR_SYMBOL [
			size 32
			fields [
				NAME_STRING 0 4
				KIND 4 4
				LINKAGE 8 4
				VISIBILITY 12 4
				TYPE_OR_SIGNATURE 16 4
				FLAGS 20 4
				OWNER_SYMBOL 24 4
				SOURCE_LOCATION 28 4
			]
		]

		RSIR_CONSTANT [
			size 32
			fields [
				TYPE 0 4
				KIND 4 4
				FLAGS 8 4
				DATA_OFFSET 12 4
				DATA_SIZE 16 4
				FIRST_PART 20 4
				PART_COUNT 24 4
				AUXILIARY 28 4
			]
		]

		RSIR_CONSTANT_PART [
			size 32
			fields [
				PARENT_CONSTANT 0 4
				BYTE_OFFSET 4 4
				TYPE 8 4
				KIND 12 4
				CHILD_CONSTANT 16 4
				TARGET_SYMBOL 20 4
				RAW_ADDEND_DATA_OFFSET 24 4
				FLAGS 28 4
			]
		]

		RSIR_GLOBAL [
			size 32
			fields [
				SYMBOL 0 4
				TYPE 4 4
				INITIALIZER_CONSTANT 8 4
				ALIGNMENT 12 4
				SECTION_CLASS 16 4
				FLAGS 20 4
				SOURCE_LOCATION 24 4
				RESERVED 28 4
			]
		]

		IMPORT [
			size 24
			fields [
				LIBRARY_STRING 0 4
				EXTERNAL_NAME_STRING 4 4
				SYMBOL 8 4
				CALLING_CONVENTION 12 4
				FLAGS 16 4
				SOURCE_LOCATION 20 4
			]
		]

		EXPORT [
			size 16
			fields [
				EXTERNAL_NAME_STRING 0 4
				SYMBOL 4 4
				ORDINAL 8 4
				FLAGS 12 4
			]
		]

		RSIR_FUNCTION [
			size 40
			fields [
				SYMBOL 0 4
				SIGNATURE 4 4
				FLAGS 8 4
				FIRST_BLOCK 12 4
				BLOCK_COUNT 16 4
				ENTRY_BLOCK 20 4
				FIRST_LOCAL 24 4
				LOCAL_COUNT 28 4
				SOURCE_LOCATION 32 4
				RESERVED 36 4
			]
		]

		RSIR_LOCAL [
			size 32
			fields [
				FUNCTION 0 4
				NAME_STRING 4 4
				TYPE 8 4
				KIND 12 4
				FLAGS 16 4
				ALIGNMENT 20 4
				SOURCE_LOCATION 24 4
				ORDINAL 28 4
			]
		]

		RSIR_BLOCK [
			size 32
			fields [
				FUNCTION 0 4
				FLAGS 4 4
				FIRST_INSTRUCTION 8 4
				INSTRUCTION_COUNT 12 4
				FIRST_OUTGOING_EDGE 16 4
				OUTGOING_EDGE_COUNT 20 4
				SOURCE_LOCATION 24 4
				RESERVED 28 4
			]
		]

		RSIR_EDGE [
			size 24
			fields [
				SOURCE_BLOCK 0 4
				TARGET_BLOCK 4 4
				KIND 8 4
				SELECTOR_CONSTANT 12 4
				ORDINAL 16 4
				FLAGS 20 4
			]
		]

		RSIR_VALUE [
			size 24
			fields [
				DEFINITION_KIND 0 4
				DEFINITION_ID 4 4
				RESULT_ORDINAL 8 4
				TYPE 12 4
				FUNCTION 16 4
				FLAGS 20 4
			]
		]

		RSIR_INSTRUCTION [
			size 48
			fields [
				BLOCK 0 4
				OPCODE 4 4
				SUBOPCODE 8 4
				FLAGS 12 4
				FIRST_RESULT 16 4
				RESULT_COUNT 20 4
				FIRST_OPERAND 24 4
				OPERAND_COUNT 28 4
				EFFECT_FLAGS 32 4
				ALIAS_KIND 36 4
				ALIAS_ID 40 4
				SOURCE_LOCATION 44 4
			]
		]

		RSIR_OPERAND [
			size 16
			fields [
				KIND 0 4
				REFERENCE 4 4
				AUXILIARY 8 4
				FLAGS 12 4
			]
		]

		RSIR_CALL [
			size 32
			fields [
				INSTRUCTION 0 4
				SIGNATURE 4 4
				CALLEE_KIND 8 4
				CALLEE_REFERENCE 12 4
				FLAGS 16 4
				FIRST_ARGUMENT_OPERAND 20 4
				ARGUMENT_COUNT 24 4
				RESERVED 28 4
			]
		]

		RSIR_TARGET_FRAGMENT [
			size 32
			fields [
				TARGET 0 4
				ABI 4 4
				DATA_OFFSET 8 4
				DATA_SIZE 12 4
				RETURN_TYPE 16 4
				EFFECT_FLAGS 20 4
				CLOBBER_CLASS 24 4
				SOURCE_LOCATION 28 4
			]
		]

		SOURCE_LOCATION [
			size 16
			fields [
				FILE 0 4
				LINE 4 4
				COLUMN 8 4
				BYTE_OFFSET 12 4
			]
		]

		RSIR_EXCEPTION_REGION [
			size 24
			fields [
				FUNCTION 0 4
				FIRST_BLOCK_MEMBER 4 4
				BLOCK_MEMBER_COUNT 8 4
				HANDLER_BLOCK 12 4
				KIND 16 4
				FLAGS 20 4
			]
		]

		RSIR_EXCEPTION_BLOCK [
			size 8
			fields [
				REGION 0 4
				BLOCK 4 4
			]
		]

		RSCG_OUTPUT_SECTION [
			size 32
			fields [
				NAME_STRING 0 4
				CLASS 4 4
				FLAGS 8 4
				ALIGNMENT 12 4
				DATA_OFFSET 16 4
				FILE_SIZE 20 4
				MEMORY_SIZE 24 4
				RESERVED 28 4
			]
		]

		RSCG_SYMBOL [
			size 40
			fields [
				NAME_STRING 0 4
				KIND 4 4
				BINDING 8 4
				VISIBILITY 12 4
				OUTPUT_SECTION 16 4
				SECTION_OFFSET 20 4
				SIZE 24 4
				ALIGNMENT 28 4
				FLAGS 32 4
				ORIGIN_MODULE 36 4
			]
		]

		RSCG_RELOCATION [
			size 32
			fields [
				SOURCE_SECTION 0 4
				SOURCE_OFFSET 4 4
				KIND 8 4
				TARGET_SYMBOL 12 4
				RAW_ADDEND_LOW 16 4
				RAW_ADDEND_HIGH 20 4
				ENCODED_WIDTH 24 4
				FLAGS 28 4
			]
		]

		RSCG_FUNCTION [
			size 40
			fields [
				SYMBOL 0 4
				CODE_SECTION 4 4
				CODE_OFFSET 8 4
				CODE_SIZE 12 4
				FRAME_SIZE 16 4
				FLAGS 20 4
				FIRST_DEBUG_LINE 24 4
				DEBUG_LINE_COUNT 28 4
				FIRST_DEBUG_PARAMETER 32 4
				DEBUG_PARAMETER_COUNT 36 4
			]
		]

		RSCG_DEBUG_LINE [
			size 20
			fields [
				FUNCTION 0 4
				CODE_OFFSET 4 4
				FILE 8 4
				LINE 12 4
				COLUMN 16 4
			]
		]

		RSCG_DEBUG_PARAMETER [
			size 16
			fields [
				FUNCTION 0 4
				ORDINAL 4 4
				DEBUG_TYPE_CODE 8 4
				FLAGS 12 4
			]
		]

		RSCG_GC_FRAME [
			size 24
			fields [
				FUNCTION 0 4
				BITMAP_SECTION 4 4
				BITMAP_OFFSET 8 4
				BITMAP_SIZE 12 4
				FLAGS 16 4
				RESERVED 20 4
			]
		]

		RSCG_UNWIND_FUNCTION [
			size 24
			fields [
				FUNCTION 0 4
				CODE_OFFSET 4 4
				CODE_SIZE 8 4
				UNWIND_CODE_OFFSET 12 4
				UNWIND_CODE_SIZE 16 4
				FLAGS 20 4
			]
		]
	]
]
