Red [
	Title: "Hybrid compiler wire schema specification"
	File:  %wire-schema-spec.red
]

; This is the single source for generated Red and Red/System wire constants.
; Numeric values may change while docs/compiler-wire-format.md is a draft.
compiler-wire-schema-spec: [
	version [
		major 1
		minor 0
	]

	magics [
		RSIR "RSIR"
		RSCF "RSCF"
		RSCG "RSCG"
		RSDG "RSDG"
	]

	enums [
		TARGET [
			NONE 0
			X86_64 1
			ARM64 2
			ARM32 3
			X86 4
		]

		ABI [
			NONE 0
			WIN64 1
			SYSV_X64 2
			AAPCS64 3
			AAPCS32 4
			WIN32 5
		]

		ENDIAN [
			NONE 0
			LITTLE 1
			BIG 2
		]

		SECTION_FLAG [
			OPTIONAL 1
			SORTED 2
			DEDUPLICATED 4
		]

		SECTION_CARDINALITY [
			ANY 0
			ONE 1
			NONEMPTY 2
		]

		RSCF_SECTION [
			CONFIG 1
		]

		RSIR_SECTION [
			MODULE 1
			DATA_LAYOUT 2
			STRINGS 3
			STRING_DATA 4
			FILES 5
			FILE_CHECKSUM_DATA 6
			TYPES 7
			FIELDS 8
			SIGNATURES 9
			PARAMETERS 10
			SYMBOLS 11
			CONSTANTS 12
			CONSTANT_DATA 13
			CONSTANT_PARTS 14
			CONSTANT_BINDINGS 15
			GLOBALS 16
			IMPORTS 17
			EXPORTS 18
			FUNCTIONS 19
			LOCALS 20
			BLOCKS 21
			EDGES 22
			VALUES 23
			INSTRUCTIONS 24
			OPERANDS 25
			CALLS 26
			TARGET_FRAGMENTS 27
			SOURCE_LOCATIONS 28
			EXCEPTION_REGIONS 29
			EXCEPTION_BLOCKS 30
		]

		RSCG_SECTION [
			DATA_LAYOUT 1
			STRINGS 2
			STRING_DATA 3
			OUTPUT_SECTIONS 4
			OUTPUT_DATA 5
			SYMBOLS 6
			RELOCATIONS 7
			IMPORTS 8
			EXPORTS 9
			FUNCTIONS 10
			FILES 11
			FILE_CHECKSUM_DATA 12
			DEBUG_LINES 13
			DEBUG_PARAMETERS 14
			GC_FRAMES 15
			MODULES 16
			UNWIND_FUNCTIONS 17
		]

		RSDG_SECTION [
			STRINGS 1
			STRING_DATA 2
			DIAGNOSTICS 3
		]

		CONFIG_FLAG [
			DEBUG 1
			PIC 2
			DETERMINISTIC 4
		]

		MODULE_KIND [
			RUNTIME 1
			USER 2
			SUPPORT 3
			GLUE 4
		]

		IMAGE_KIND [
			EXECUTABLE 1
			DYNAMIC_LIBRARY 2
		]

		OPTIMIZATION_LEVEL [
			O0 0
			O1 1
			O2 2
		]

		CPU_BASELINE [
			NONE 0
			X86_64_BASE 1
		]

		CHECKSUM_KIND [
			NONE 0
			SHA256 1
		]

		CODE_MODEL [
			SMALL 1
		]

		RELOCATION_MODEL [
			STATIC 1
			PIC 2
		]

		DEBUG_FORMAT [
			NONE 0
			RED 1
		]

		TYPE_KIND [
			VOID 1
			LOGIC 2
			INTEGER 3
			FLOAT 4
			POINTER 5
			FUNCTION 6
			STRUCT 7
			UNION 8
		]

		TYPE_FLAG [
			SIGNED 1
			TAGGED 2
			C_STRING 4
		]

		GC_KIND [
			NONE 0
			POINTER 1
			HANDLE 2
		]

		SYMBOL_KIND [
			FUNCTION 1
			GLOBAL 2
			CONSTANT 3
			TYPE 4
		]

		CONSTANT_KIND [
			ZERO 1
			SCALAR 2
			STORAGE 3
			AGGREGATE 4
			ADDRESS 5
		]

		CONSTANT_PART_KIND [
			VALUE 1
			SYMBOL_ADDRESS 2
			CONSTANT_ADDRESS 3
			ABSOLUTE_ADDRESS 4
		]

		CONSTANT_FLAG [
			NONE 0
		]

		CONSTANT_PART_FLAG [
			NONE 0
		]

		GLOBAL_STORAGE_CLASS [
			MUTABLE 1
		]

		GLOBAL_FLAG [
			NONE 0
		]

		LINKAGE [
			LOCAL 1
			INTERNAL 2
			EXTERNAL 3
			IMPORT 4
			WEAK 5
		]

		VISIBILITY [
			DEFAULT 1
			HIDDEN 2
		]

		CALLING_CONVENTION [
			RED_SYSTEM 1
			CDECL 2
			STDCALL 3
			SYSCALL 4
		]

		FUNCTION_FLAG [
			VARIADIC 1
			TYPED 2
			CUSTOM 4
			CALLBACK 8
			NO_RETURN 32
			MAY_THROW 64
		]

		DEBUG_TYPE_CODE [
			LOGIC 1
			INTEGER 2
			BYTE 3
			FLOAT32 4
			FLOAT64 5
			C_STRING 6
			BYTE_POINTER 7
			INTEGER_POINTER 8
			FUNCTION 9
			POINTER_POINTER 10
			INT64 11
			UINT64 12
			INT8 13
			UINT8 14
			INT16 15
			UINT16 16
			UINT32 17
			AGGREGATE 100
		]

		LOCAL_KIND [
			ARGUMENT 1
			LOCAL 2
			TEMPORARY 3
			MERGE 4
		]

		EDGE_KIND [
			NORMAL 1
			TRUE 2
			FALSE 3
			SWITCH_CASE 4
			DEFAULT 5
			EXCEPTION 6
			UNREACHABLE 7
		]

		VALUE_DEFINITION [
			PARAMETER 1
			INSTRUCTION 2
		]

		VALUE_FLAG [
			NONE 0
		]

		OPERAND_KIND [
			VALUE 1
			CONSTANT 2
			SYMBOL 3
			BLOCK 4
			LOCAL 5
			TYPE 6
			FUNCTION 7
			TARGET_FRAGMENT 8
		]

		OPERAND_FLAG [
			NONE 0
		]

		INSTRUCTION_FLAG [
			CHECKED 1
		]

		CALL_KIND [
			DIRECT 1
			INDIRECT 2
			IMPORT 3
			SYSCALL 4
			CUSTOM 5
			SUBROUTINE 6
		]

		EFFECT_FLAG [
			READ 1
			WRITE 2
			CALL 4
			VOLATILE 8
			ATOMIC 16
			MAY_TRAP 32
			THROW 64
			SAFEPOINT 128
			CONTROL 256
			STACK 512
			OPAQUE 1024
		]

		ALIAS_KIND [
			NONE 0
			UNIVERSAL 1
			LOCAL 2
			GLOBAL 3
		]

		OPCODE [
			CONSTANT 1
			COPY 2
			CONVERT 3
			BITCAST 4
			ADD 5
			SUBTRACT 6
			MULTIPLY 7
			DIVIDE 8
			REMAINDER 9
			MODULO 10
			NEGATE 11
			BIT_NOT 12
			LOGIC_NOT 13
			SHIFT_LEFT 14
			SHIFT_RIGHT 15
			SHIFT_RIGHT_LOGICAL 16
			BIT_AND 17
			BIT_OR 18
			BIT_XOR 19
			COMPARE 20
			LOAD_LOCAL 21
			STORE_LOCAL 22
			ADDRESS_LOCAL 23
			LOAD_GLOBAL 24
			STORE_GLOBAL 25
			ADDRESS_GLOBAL 26
			LOAD_INDIRECT 27
			STORE_INDIRECT 28
			ADDRESS_FIELD 29
			AGGREGATE_BUILD 30
			AGGREGATE_COPY 31
			ATOMIC_LOAD 32
			ATOMIC_STORE 33
			ATOMIC_RMW 34
			ATOMIC_CAS 35
			ATOMIC_FENCE 36
			CALL 37
			BRANCH 38
			JUMP 39
			SWITCH 40
			RETURN 41
			THROW 42
			CATCH_ENTER 43
			CATCH_LEAVE 44
			UNREACHABLE 45
			KEEPALIVE 46
			STACK_ALLOC 47
			STACK_FREE 48
			STACK_PUSH 49
			STACK_POP 50
			PUSH_ALL 51
			POP_ALL 52
			PORT_READ 53
			PORT_WRITE 54
			GET_PC 55
			TARGET_FRAGMENT 56
		]

		COMPARE_KIND [
			EQUAL 1
			NOT_EQUAL 2
			LESS 3
			GREATER 4
			LESS_EQUAL 5
			GREATER_EQUAL 6
		]

		ATOMIC_ORDER [
			RELAXED 1
			ACQUIRE 2
			RELEASE 3
			ACQUIRE_RELEASE 4
			SEQUENTIAL 5
		]

		OUTPUT_SECTION_CLASS [
			CODE 1
			RODATA 2
			DATA 3
			BSS 4
			PLATFORM 5
		]

		SYMBOL_BINDING [
			LOCAL 1
			GLOBAL 2
			WEAK 3
		]

		RELOCATION_KIND [
			X64_REL32 1
			X64_RIP_REL32 2
			ABSOLUTE32 3
			ABSOLUTE64 4
		]

		CONTAINER_ERROR [
			SUCCESS 0
			INVALID_ARGUMENTS 1
			TRUNCATED_HEADER 2
			BAD_MAGIC 3
			UNSUPPORTED_VERSION 4
			BAD_HEADER_SIZE 5
			BAD_CONTAINER_FLAGS 6
			BAD_TOTAL_SIZE 7
			SCALAR_RANGE 8
			BAD_SCHEMA_FINGERPRINT 9
			BAD_TARGET 10
			BAD_ABI 11
			BAD_ENDIAN 12
			BAD_POINTER_SIZE 13
			BAD_DIRECTORY_OFFSET 14
			BAD_DIRECTORY_RECORD_SIZE 15
			DIRECTORY_RANGE 16
			SECTION_ORDER 17
			BAD_SECTION_FLAGS 18
			UNKNOWN_REQUIRED_SECTION 19
			BAD_RECORD_SIZE 20
			SECTION_PRODUCT 21
			BAD_ALIGNMENT 22
			EMPTY_SECTION_OFFSET 23
			SECTION_RANGE 24
			PAYLOAD_ORDER 25
			NONZERO_RESERVED 26
			NONZERO_PADDING 27
			MISSING_REQUIRED_SECTION 28
			BAD_SECTION_CARDINALITY 29
		]

		RSCF_ERROR [
			SUCCESS 0
			INVALID_ARGUMENTS 1
			INVALID_CONTAINER 2
			SCALAR_RANGE 3
			UNSUPPORTED_TARGET 4
			BAD_OPTIMIZATION_LEVEL 5
			BAD_CONFIG_FLAGS 6
			BAD_CODE_MODEL 7
			BAD_RELOCATION_MODEL 8
			BAD_DEBUG_FORMAT 9
			BAD_CPU_BASELINE 10
			FEATURE_MISMATCH 11
			UNSUPPORTED_CPU_FEATURES 12
			BAD_OUTPUT_LIMIT 13
			BAD_DIAGNOSTIC_LIMIT 14
			BAD_WORKER_COUNT 15
			BAD_DETERMINISTIC_SEED 16
			NONZERO_RESERVED 17
			INCONSISTENT_DEBUG 18
			INCONSISTENT_PIC 19
		]

		DATA_LAYOUT_ERROR [
			SUCCESS 0
			INVALID_ARGUMENTS 1
			INVALID_CONTAINER 2
			SCALAR_RANGE 3
			UNSUPPORTED_MESSAGE 4
			UNSUPPORTED_TARGET 5
			UNSUPPORTED_CPU_FEATURES 6
			BAD_ADDRESS_UNIT 7
			POINTER_SIZE_MISMATCH 8
			BAD_POINTER_ALIGNMENT 9
			BAD_STACK_ALIGNMENT 10
			BAD_MAX_SCALAR_ALIGNMENT 11
			BAD_MAX_AGGREGATE_ALIGNMENT 12
			BAD_INTEGER_REGISTER_WIDTH 13
			NONZERO_FLAGS 14
		]

		STRING_TABLE_ERROR [
			SUCCESS 0
			INVALID_ARGUMENTS 1
			INVALID_CONTAINER 2
			UNSUPPORTED_MESSAGE 3
			SCALAR_RANGE 4
			BAD_STRING_SECTION_FLAGS 5
			BAD_STRING_DATA_SECTION_FLAGS 6
			STRING_SLICE_RANGE 7
			STRING_DATA_COVERAGE 8
			INVALID_UTF8 9
			EMBEDDED_NUL 10
			BAD_EMPTY_STRING 11
			STRING_ORDER 12
			DUPLICATE_STRING 13
		]

		FILE_SOURCE_ERROR [
			SUCCESS 0
			INVALID_ARGUMENTS 1
			INVALID_CONTAINER 2
			UNSUPPORTED_MESSAGE 3
			INVALID_STRINGS 4
			SCALAR_RANGE 5
			BAD_FILES_SECTION_FLAGS 6
			BAD_CHECKSUM_DATA_SECTION_FLAGS 7
			FILE_PATH_ID 8
			EMPTY_FILE_PATH 9
			FILE_ORDER 10
			DUPLICATE_FILE 11
			BAD_CHECKSUM_KIND 12
			BAD_CHECKSUM_OFFSET 13
			BAD_CHECKSUM_SIZE 14
			BAD_CHECKSUM_SLICE_RANGE 15
			CHECKSUM_DATA_COVERAGE 16
			BAD_SOURCE_SECTION_FLAGS 17
			SOURCE_FILE_ID 18
			SOURCE_LINE 19
			SOURCE_COLUMN 20
			SOURCE_ORDER 21
			DUPLICATE_SOURCE 22
		]

		DIAGNOSTIC_ERROR [
			SUCCESS 0
			INVALID_ARGUMENTS 1
			INVALID_CONTAINER 2
			UNSUPPORTED_MESSAGE 3
			INVALID_STRINGS 4
			SCALAR_RANGE 5
			BAD_DIAGNOSTIC_SECTION_FLAGS 6
			BAD_STATUS 7
			INCONSISTENT_STATUS 8
			BAD_SEVERITY 9
			BAD_PRIMARY_SEVERITY 10
			BAD_PHASE 11
			BAD_STATUS_PHASE 12
			BAD_MESSAGE_STRING 13
			EMPTY_MESSAGE 14
			BAD_FLAGS 15
			SOURCE_WITHOUT_FILE 16
			BAD_FILE_ID 17
			BAD_LINE 18
			BAD_COLUMN 19
			INSTRUCTION_WITHOUT_FUNCTION 20
			BAD_FUNCTION_ID 21
			BAD_INSTRUCTION_ID 22
			CONTEXT_WITHOUT_TARGET 23
		]

		TYPE_LAYOUT_ERROR [
			SUCCESS 0
			INVALID_ARGUMENTS 1
			INVALID_CONTAINER 2
			INVALID_STRINGS 3
			INVALID_FILE_SOURCE 4
			INVALID_DATA_LAYOUT 5
			SCALAR_RANGE 6
			BAD_TYPE_SECTION_FLAGS 7
			BAD_FIELD_SECTION_FLAGS 8
			BAD_KIND 9
			BAD_FLAGS 10
			BAD_SIZE 11
			BAD_ALIGNMENT 12
			NONZERO_TYPE_RESERVED 13
			BAD_DETAIL_ID 14
			BAD_TYPE_ORDER 15
			BAD_FIELD_RANGE 16
			BAD_GC_KIND 17
			BAD_FIELD_OWNER 18
			BAD_FIELD_NAME_ID 19
			EMPTY_FIELD_NAME 20
			BAD_FIELD_TYPE 21
			BAD_FIELD_OFFSET 22
			NONZERO_FIELD_FLAGS 23
			BAD_FIELD_ORDINAL 24
			BAD_SOURCE_LOCATION 25
			NONZERO_RESERVED 26
		]

		MODULE_LIFECYCLE_ERROR [
			SUCCESS 0
			INVALID_ARGUMENTS 1
			INVALID_CONTAINER 2
			UNSUPPORTED_MESSAGE 3
			INVALID_STRINGS 4
			INVALID_FILE_SOURCE 5
			SCALAR_RANGE 6
			BAD_MODULE_SECTION_FLAGS 7
			BAD_NAME_ID 8
			EMPTY_NAME 9
			BAD_MODULE_KIND 10
			BAD_IMAGE_KIND 11
			BAD_INITIALIZER_ID 12
			BAD_FINALIZER_ID 13
			BAD_ENTRY_ID 14
			BAD_SOURCE_LOCATION 15
			NONZERO_FLAGS 16
			NONZERO_RESERVED 17
			BAD_LIFECYCLE_SHAPE 18
			IMAGE_KIND_MISMATCH 19
			MULTIPLE_GLUE_MODULES 20
			BAD_SYMBOL_ORIGIN_MODULE 21
			LIFECYCLE_SYMBOL_OWNER 22
		]

		FUNCTION_SIGNATURE_ERROR [
			SUCCESS 0
			INVALID_ARGUMENTS 1
			INVALID_CONTAINER 2
			INVALID_STRINGS 3
			INVALID_FILE_SOURCE 4
			INVALID_DATA_LAYOUT 5
			INVALID_TYPE_LAYOUT 6
			SCALAR_RANGE 7
			BAD_SIGNATURE_SECTION_FLAGS 8
			BAD_PARAMETER_SECTION_FLAGS 9
			BAD_FUNCTION_SECTION_FLAGS 10
			BAD_LOCAL_SECTION_FLAGS 11
			BAD_BLOCK_SECTION_FLAGS 12
			BAD_CALLING_CONVENTION 13
			BAD_SIGNATURE_FLAGS 14
			BAD_RETURN_TYPE 15
			BAD_PARAMETER_RANGE 16
			BAD_LOGICAL_ARITY 17
			BAD_SIGNATURE_SOURCE_LOCATION 18
			NONZERO_SIGNATURE_RESERVED 19
			BAD_PARAMETER_SIGNATURE 20
			BAD_PARAMETER_NAME_ID 21
			EMPTY_PARAMETER_NAME 22
			BAD_PARAMETER_TYPE 23
			NONZERO_PARAMETER_FLAGS 24
			BAD_PARAMETER_ORDINAL 25
			BAD_DEBUG_TYPE_CODE 26
			BAD_PARAMETER_SOURCE_LOCATION 27
			NONZERO_PARAMETER_RESERVED 28
			BAD_PARAMETER_COVERAGE 29
			BAD_PROTOCOL_PARAMETERS 30
			BAD_FUNCTION_SYMBOL 31
			BAD_FUNCTION_SIGNATURE 32
			NONZERO_FUNCTION_FLAGS 33
			BAD_FUNCTION_BLOCK_RANGE 34
			BAD_FUNCTION_ENTRY_BLOCK 35
			BAD_FUNCTION_LOCAL_RANGE 36
			BAD_FUNCTION_SOURCE_LOCATION 37
			NONZERO_FUNCTION_RESERVED 38
			BAD_BLOCK_OWNER 39
			BAD_BLOCK_COVERAGE 40
			NONZERO_BLOCK_FLAGS 41
			BAD_BLOCK_SOURCE_LOCATION 42
			NONZERO_BLOCK_RESERVED 43
			BAD_LOCAL_FUNCTION 44
			BAD_LOCAL_NAME_ID 45
			EMPTY_LOCAL_NAME 46
			BAD_LOCAL_TYPE 47
			BAD_LOCAL_KIND 48
			NONZERO_LOCAL_FLAGS 49
			BAD_LOCAL_ALIGNMENT 50
			BAD_LOCAL_SOURCE_LOCATION 51
			BAD_LOCAL_ORDINAL 52
			BAD_ARGUMENT_LOCAL 53
			BAD_LOCAL_COVERAGE 54
		]

		SYMBOL_LINKAGE_ERROR [
			SUCCESS 0
			INVALID_ARGUMENTS 1
			INVALID_CONTAINER 2
			INVALID_STRINGS 3
			INVALID_FILE_SOURCE 4
			INVALID_DATA_LAYOUT 5
			INVALID_TYPE_LAYOUT 6
			INVALID_FUNCTION_SIGNATURE 7
			INVALID_MODULE_LIFECYCLE 8
			SCALAR_RANGE 9
			BAD_SYMBOL_SECTION_FLAGS 10
			BAD_GLOBAL_SECTION_FLAGS 11
			BAD_IMPORT_SECTION_FLAGS 12
			BAD_EXPORT_SECTION_FLAGS 13
			BAD_SYMBOL_NAME_ID 14
			EMPTY_SYMBOL_NAME 15
			SYMBOL_ORDER 16
			DUPLICATE_SYMBOL_NAME 17
			BAD_SYMBOL_KIND 18
			BAD_LINKAGE 19
			BAD_VISIBILITY 20
			BAD_SYMBOL_TYPE_OR_SIGNATURE 21
			NONZERO_SYMBOL_FLAGS 22
			NONZERO_OWNER_SYMBOL 23
			BAD_SYMBOL_SOURCE_LOCATION 24
			BAD_LINKAGE_VISIBILITY 25
			BAD_SYMBOL_KIND_LINKAGE 26
			BAD_SYSCALL_DECLARATION 27
			BAD_GLOBAL_SYMBOL 28
			BAD_GLOBAL_SYMBOL_KIND 29
			GLOBAL_TYPE_MISMATCH 30
			GLOBAL_ORDER 31
			DUPLICATE_GLOBAL_DEFINITION 32
			IMPORTED_GLOBAL_DEFINITION 33
			BAD_GLOBAL_SOURCE_LOCATION 34
			NONZERO_GLOBAL_RESERVED 35
			BAD_FUNCTION_SYMBOL_KIND 36
			FUNCTION_SIGNATURE_MISMATCH 37
			FUNCTION_ORDER 38
			DUPLICATE_FUNCTION_DEFINITION 39
			IMPORTED_FUNCTION_DEFINITION 40
			BAD_IMPORT_LIBRARY_ID 41
			EMPTY_IMPORT_LIBRARY 42
			BAD_IMPORT_EXTERNAL_NAME_ID 43
			EMPTY_IMPORT_EXTERNAL_NAME 44
			BAD_IMPORT_SYMBOL 45
			BAD_IMPORT_SYMBOL_KIND 46
			BAD_IMPORT_LINKAGE 47
			BAD_IMPORT_CALLING_CONVENTION 48
			NONZERO_IMPORT_FLAGS 49
			BAD_IMPORT_SOURCE_LOCATION 50
			IMPORT_ORDER 51
			DUPLICATE_IMPORT_SYMBOL 52
			MISSING_IMPORT 53
			MISSING_GLOBAL_DEFINITION 54
			MISSING_FUNCTION_DEFINITION 55
			BAD_EXPORT_IMAGE_KIND 56
			BAD_EXPORT_EXTERNAL_NAME_ID 57
			EMPTY_EXPORT_EXTERNAL_NAME 58
			BAD_EXPORT_SYMBOL 59
			BAD_EXPORT_SYMBOL_KIND 60
			EXPORT_ORDER 61
			DUPLICATE_EXPORT_NAME 62
			NONZERO_EXPORT_ORDINAL 63
			NONZERO_EXPORT_FLAGS 64
			BAD_EXPORT_LINKAGE 65
			MISSING_EXPORT_DEFINITION 66
			BAD_EXPORT_SIGNATURE 67
			BAD_LIFECYCLE_FUNCTION 68
		]

		CONSTANT_INITIALIZER_ERROR [
			SUCCESS 0
			INVALID_ARGUMENTS 1
			INVALID_CONTAINER 2
			INVALID_STRINGS 3
			INVALID_FILE_SOURCE 4
			INVALID_DATA_LAYOUT 5
			INVALID_TYPE_LAYOUT 6
			INVALID_FUNCTION_SIGNATURE 7
			INVALID_MODULE_LIFECYCLE 8
			INVALID_SYMBOL_LINKAGE 9
			SCALAR_RANGE 10
			BAD_CONSTANT_SECTION_FLAGS 11
			BAD_CONSTANT_DATA_SECTION_FLAGS 12
			BAD_CONSTANT_PART_SECTION_FLAGS 13
			BAD_CONSTANT_BINDING_SECTION_FLAGS 14
			BAD_CONSTANT_TYPE 15
			BAD_CONSTANT_KIND 16
			NONZERO_CONSTANT_FLAGS 17
			BAD_CONSTANT_PART_RANGE 18
			BAD_ZERO_SHAPE 19
			BAD_SCALAR_TYPE 20
			BAD_SCALAR_DATA_SIZE 21
			BAD_SCALAR_SHAPE 22
			BAD_LOGIC_ENCODING 23
			BAD_STORAGE_TYPE 24
			BAD_STORAGE_COUNT 25
			BAD_STORAGE_DATA_SIZE 26
			BAD_STORAGE_PART_COUNT 27
			BAD_C_STRING_ENCODING 28
			BAD_AGGREGATE_TYPE 29
			BAD_AGGREGATE_PART_COUNT 30
			BAD_AGGREGATE_AUXILIARY 31
			BAD_ADDRESS_TYPE 32
			BAD_ADDRESS_SHAPE 33
			BAD_CONSTANT_DATA_OFFSET 34
			CONSTANT_DATA_RANGE 35
			BAD_PART_PARENT 36
			BAD_PART_TYPE 37
			BAD_PART_KIND 38
			BAD_PART_OFFSET 39
			BAD_CHILD_CONSTANT 40
			CONSTANT_ORDER 41
			PART_TYPE_MISMATCH 42
			BAD_TARGET_SYMBOL 43
			BAD_TARGET_SYMBOL_KIND 44
			BAD_ADDRESS_TARGET_TYPE 45
			BAD_ADDEND_OFFSET 46
			BAD_ADDEND_ENCODING 47
			NONZERO_PART_FLAGS 48
			BAD_PART_SHAPE 49
			CONSTANT_PART_COVERAGE 50
			CONSTANT_DATA_COVERAGE 51
			BAD_BINDING_SYMBOL 52
			BAD_BINDING_SYMBOL_KIND 53
			BAD_BINDING_CONSTANT 54
			BINDING_TYPE_MISMATCH 55
			BINDING_ORDER 56
			DUPLICATE_BINDING_SYMBOL 57
			MISSING_CONSTANT_BINDING 58
			BAD_GLOBAL_INITIALIZER 59
			GLOBAL_INITIALIZER_TYPE_MISMATCH 60
			BAD_GLOBAL_ALIGNMENT 61
			BAD_GLOBAL_STORAGE_CLASS 62
			NONZERO_GLOBAL_FLAGS 63
			BAD_UNION_FIELD 64
			PART_OVERLAP 65
			NONZERO_PART_PLACEHOLDER 66
		]

		SCALAR_OPERATION_ERROR [
			SUCCESS 0
			INVALID_ARGUMENTS 1
			INVALID_CONTAINER 2
			INVALID_STRINGS 3
			INVALID_FILE_SOURCE 4
			INVALID_DATA_LAYOUT 5
			INVALID_TYPE_LAYOUT 6
			INVALID_FUNCTION_SIGNATURE 7
			INVALID_MODULE_LIFECYCLE 8
			INVALID_SYMBOL_LINKAGE 9
			INVALID_CONSTANT_INITIALIZER 10
			SCALAR_RANGE 11
			BAD_VALUE_SECTION_FLAGS 12
			BAD_INSTRUCTION_SECTION_FLAGS 13
			BAD_OPERAND_SECTION_FLAGS 14
			BAD_VALUE_DEFINITION_KIND 15
			BAD_VALUE_DEFINITION_ID 16
			BAD_VALUE_RESULT_ORDINAL 17
			BAD_VALUE_TYPE 18
			BAD_VALUE_FUNCTION 19
			NONZERO_VALUE_FLAGS 20
			BAD_BLOCK_INSTRUCTION_RANGE 21
			BAD_INSTRUCTION_COVERAGE 22
			BAD_INSTRUCTION_BLOCK 23
			BAD_OPCODE 24
			BAD_INSTRUCTION_RESULT_RANGE 25
			BAD_INSTRUCTION_OPERAND_RANGE 26
			BAD_INSTRUCTION_SOURCE_LOCATION 27
			BAD_OPERAND_KIND 28
			BAD_OPERAND_REFERENCE 29
			BAD_OPERAND_FUNCTION 30
			NONZERO_OPERAND_FLAGS 31
			BAD_OPERAND_COVERAGE 32
			BAD_PARAMETER_VALUE 33
			BAD_VALUE_COVERAGE 34
			BAD_RESULT_VALUE 35
			BAD_SCALAR_SUBOPCODE 36
			BAD_SCALAR_INSTRUCTION_FLAGS 37
			BAD_SCALAR_EFFECTS 38
			BAD_SCALAR_ALIAS 39
			BAD_SCALAR_OPERAND_COUNT 40
			BAD_SCALAR_RESULT_COUNT 41
			BAD_SCALAR_OPERAND_KIND 42
			NONZERO_SCALAR_OPERAND_AUXILIARY 43
			SCALAR_TYPE_MISMATCH 44
			BAD_SCALAR_TYPE 45
			BAD_CONVERSION 46
			BAD_BITCAST 47
			BAD_COMPARE_KIND 48
			BAD_COMPARE_TYPE 49
			BAD_CHECKED_OPERATION 50
			BAD_CHECKED_RESULT 51
			BAD_SHIFT_COUNT_TYPE 52
		]

		STATUS [
			SUCCESS 0
			INVALID_ARGUMENTS 1
			INVALID_CONFIGURATION 2
			INVALID_RSIR 3
			UNSUPPORTED_TARGET 4
			CODEGEN_FAILURE 5
			INVALID_ARTIFACT 6
		]

		DIAGNOSTIC_SEVERITY [
			NOTE 1
			WARNING 2
			ERROR 3
			FATAL 4
		]

		DIAGNOSTIC_PHASE [
			BRIDGE 1
			CONFIGURATION 2
			DECODE 3
			VERIFY 4
			OPTIMIZE 5
			SELECT 6
			ALLOCATE 7
			ENCODE 8
			ARTIFACT 9
		]

		DIAGNOSTIC_FLAG [
			FILE 1
			SOURCE 2
			FUNCTION 4
			INSTRUCTION 8
		]
	]

	profiles [
		RSCF [
			CONFIG RSCF_CONFIG REQUIRED ONE 4
		]

		RSIR [
			MODULE RSIR_MODULE REQUIRED ONE 4
			DATA_LAYOUT DATA_LAYOUT REQUIRED ONE 4
			STRINGS STRING REQUIRED ANY 4
			STRING_DATA BYTE REQUIRED ANY 1
			FILES FILE REQUIRED ANY 4
			FILE_CHECKSUM_DATA BYTE REQUIRED ANY 1
			TYPES RSIR_TYPE REQUIRED ANY 4
			FIELDS RSIR_FIELD REQUIRED ANY 4
			SIGNATURES RSIR_SIGNATURE REQUIRED ANY 4
			PARAMETERS RSIR_PARAMETER REQUIRED ANY 4
			SYMBOLS RSIR_SYMBOL REQUIRED ANY 4
			CONSTANTS RSIR_CONSTANT REQUIRED ANY 4
			CONSTANT_DATA BYTE REQUIRED ANY 1
			CONSTANT_PARTS RSIR_CONSTANT_PART REQUIRED ANY 4
			CONSTANT_BINDINGS RSIR_CONSTANT_BINDING REQUIRED ANY 4
			GLOBALS RSIR_GLOBAL REQUIRED ANY 4
			IMPORTS IMPORT REQUIRED ANY 4
			EXPORTS EXPORT REQUIRED ANY 4
			FUNCTIONS RSIR_FUNCTION REQUIRED ANY 4
			LOCALS RSIR_LOCAL REQUIRED ANY 4
			BLOCKS RSIR_BLOCK REQUIRED ANY 4
			EDGES RSIR_EDGE REQUIRED ANY 4
			VALUES RSIR_VALUE REQUIRED ANY 4
			INSTRUCTIONS RSIR_INSTRUCTION REQUIRED ANY 4
			OPERANDS RSIR_OPERAND REQUIRED ANY 4
			CALLS RSIR_CALL REQUIRED ANY 4
			TARGET_FRAGMENTS RSIR_TARGET_FRAGMENT REQUIRED ANY 4
			SOURCE_LOCATIONS SOURCE_LOCATION REQUIRED ANY 4
			EXCEPTION_REGIONS RSIR_EXCEPTION_REGION REQUIRED ANY 4
			EXCEPTION_BLOCKS RSIR_EXCEPTION_BLOCK REQUIRED ANY 4
		]

		RSCG [
			DATA_LAYOUT DATA_LAYOUT REQUIRED ONE 4
			STRINGS STRING REQUIRED ANY 4
			STRING_DATA BYTE REQUIRED ANY 1
			OUTPUT_SECTIONS RSCG_OUTPUT_SECTION REQUIRED ANY 4
			OUTPUT_DATA BYTE REQUIRED ANY 1
			SYMBOLS RSCG_SYMBOL REQUIRED ANY 4
			RELOCATIONS RSCG_RELOCATION REQUIRED ANY 4
			IMPORTS IMPORT REQUIRED ANY 4
			EXPORTS EXPORT REQUIRED ANY 4
			FUNCTIONS RSCG_FUNCTION REQUIRED ANY 4
			FILES FILE REQUIRED ANY 4
			FILE_CHECKSUM_DATA BYTE REQUIRED ANY 1
			DEBUG_LINES RSCG_DEBUG_LINE REQUIRED ANY 4
			DEBUG_PARAMETERS RSCG_DEBUG_PARAMETER REQUIRED ANY 4
			GC_FRAMES RSCG_GC_FRAME REQUIRED ANY 4
			MODULES RSCG_MODULE REQUIRED NONEMPTY 4
			UNWIND_FUNCTIONS RSCG_UNWIND_FUNCTION OPTIONAL ANY 4
		]

		RSDG [
			STRINGS STRING REQUIRED NONEMPTY 4
			STRING_DATA BYTE REQUIRED NONEMPTY 1
			DIAGNOSTICS RSDG_DIAGNOSTIC REQUIRED NONEMPTY 4
		]
	]

	records [
		HEADER [
			size 64
			fields [
				MAGIC 0 4
				VERSION_MAJOR 4 2
				VERSION_MINOR 6 2
				HEADER_SIZE 8 4
				CONTAINER_FLAGS 12 4
				TOTAL_SIZE 16 4
				SECTION_COUNT 20 4
				DIRECTORY_OFFSET 24 4
				DIRECTORY_RECORD_SIZE 28 4
				TARGET 32 4
				ABI 36 4
				TARGET_ENDIAN 40 4
				POINTER_SIZE 44 4
				FEATURE_MASK_LOW 48 4
				FEATURE_MASK_HIGH 52 4
				PRODUCER_BUILD 56 4
				SCHEMA_FINGERPRINT 60 4
			]
		]

		DIRECTORY [
			size 32
			fields [
				KIND 0 4
				FLAGS 4 4
				PAYLOAD_OFFSET 8 4
				PAYLOAD_SIZE 12 4
				RECORD_COUNT 16 4
				RECORD_SIZE 20 4
				ALIGNMENT 24 4
				RESERVED 28 4
			]
		]

		RSCF_CONFIG [
			size 64
			fields [
				OPTIMIZATION_LEVEL 0 4
				FLAGS 4 4
				CODE_MODEL 8 4
				RELOCATION_MODEL 12 4
				DEBUG_FORMAT 16 4
				CPU_BASELINE 20 4
				CPU_FEATURES_LOW 24 4
				CPU_FEATURES_HIGH 28 4
				MAX_OUTPUT_BYTES 32 4
				MAX_DIAGNOSTIC_BYTES 36 4
				WORKER_COUNT 40 4
				DETERMINISTIC_SEED 44 4
				RESERVED_0 48 4
				RESERVED_1 52 4
				RESERVED_2 56 4
				RESERVED_3 60 4
			]
		]

		RSDG_DIAGNOSTIC [
			size 40
			fields [
				STATUS 0 4
				SEVERITY 4 4
				PHASE 8 4
				MESSAGE_STRING 12 4
				FILE 16 4
				LINE 20 4
				COLUMN 24 4
				FUNCTION_SYMBOL 28 4
				INSTRUCTION 32 4
				FLAGS 36 4
			]
		]

		STRING [
			size 8
			fields [
				OFFSET 0 4
				SIZE 4 4
			]
		]

		FILE [
			size 16
			fields [
				PATH_STRING 0 4
				CHECKSUM_KIND 4 4
				CHECKSUM_OFFSET 8 4
				CHECKSUM_SIZE 12 4
			]
		]

		DATA_LAYOUT [
			size 32
			fields [
				ADDRESS_UNIT 0 4
				POINTER_SIZE 4 4
				POINTER_ALIGNMENT 8 4
				STACK_ALIGNMENT 12 4
				MAX_SCALAR_ALIGNMENT 16 4
				MAX_AGGREGATE_ALIGNMENT 20 4
				INTEGER_REGISTER_WIDTH 24 4
				FLAGS 28 4
			]
		]

		RSIR_MODULE [
			size 32
			fields [
				NAME_STRING 0 4
				KIND 4 4
				IMAGE_KIND 8 4
				INITIALIZER_FUNCTION 12 4
				FINALIZER_FUNCTION 16 4
				ENTRY_FUNCTION 20 4
				SOURCE_LOCATION 24 4
				FLAGS 28 4
			]
		]

		RSCG_MODULE [
			size 32
			fields [
				NAME_STRING 0 4
				KIND 4 4
				IMAGE_KIND 8 4
				INITIALIZER_SYMBOL 12 4
				FINALIZER_SYMBOL 16 4
				ENTRY_SYMBOL 20 4
				FLAGS 24 4
				RESERVED 28 4
			]
		]

		RSIR_TYPE [
			size 40
			fields [
				KIND 0 4
				FLAGS 4 4
				SIZE 8 4
				ALIGNMENT 12 4
				RESERVED_0 16 4
				DETAIL_ID 20 4
				RESERVED_1 24 4
				FIRST_FIELD 28 4
				FIELD_COUNT 32 4
				GC_KIND 36 4
			]
		]

		RSIR_FIELD [
			size 32
			fields [
				OWNER_TYPE 0 4
				NAME_STRING 4 4
				TYPE 8 4
				BYTE_OFFSET 12 4
				FLAGS 16 4
				ORDINAL 20 4
				SOURCE_LOCATION 24 4
				RESERVED 28 4
			]
		]

		RSIR_SIGNATURE [
			size 32
			fields [
				CALLING_CONVENTION 0 4
				FLAGS 4 4
				RETURN_TYPE 8 4
				FIRST_PARAMETER 12 4
				PARAMETER_COUNT 16 4
				LOGICAL_ARITY 20 4
				SOURCE_LOCATION 24 4
				RESERVED 28 4
			]
		]

		RSIR_PARAMETER [
			size 32
			fields [
				SIGNATURE 0 4
				NAME_STRING 4 4
				TYPE 8 4
				FLAGS 12 4
				ORDINAL 16 4
				DEBUG_TYPE_CODE 20 4
				SOURCE_LOCATION 24 4
				RESERVED 28 4
			]
		]

		RSIR_SYMBOL [
			size 32
			fields [
				NAME_STRING 0 4
				KIND 4 4
				LINKAGE 8 4
				VISIBILITY 12 4
				TYPE_OR_SIGNATURE 16 4
				FLAGS 20 4
				OWNER_SYMBOL 24 4
				SOURCE_LOCATION 28 4
			]
		]

		RSIR_CONSTANT [
			size 32
			fields [
				TYPE 0 4
				KIND 4 4
				FLAGS 8 4
				DATA_OFFSET 12 4
				DATA_SIZE 16 4
				FIRST_PART 20 4
				PART_COUNT 24 4
				AUXILIARY 28 4
			]
		]

		RSIR_CONSTANT_PART [
			size 32
			fields [
				PARENT_CONSTANT 0 4
				BYTE_OFFSET 4 4
				TYPE 8 4
				KIND 12 4
				CHILD_CONSTANT 16 4
				TARGET_SYMBOL 20 4
				RAW_ADDEND_DATA_OFFSET 24 4
				FLAGS 28 4
			]
		]

		RSIR_CONSTANT_BINDING [
			size 8
			fields [
				SYMBOL 0 4
				CONSTANT 4 4
			]
		]

		RSIR_GLOBAL [
			size 32
			fields [
				SYMBOL 0 4
				TYPE 4 4
				INITIALIZER_CONSTANT 8 4
				ALIGNMENT 12 4
				STORAGE_CLASS 16 4
				FLAGS 20 4
				SOURCE_LOCATION 24 4
				RESERVED 28 4
			]
		]

		IMPORT [
			size 24
			fields [
				LIBRARY_STRING 0 4
				EXTERNAL_NAME_STRING 4 4
				SYMBOL 8 4
				CALLING_CONVENTION 12 4
				FLAGS 16 4
				SOURCE_LOCATION 20 4
			]
		]

		EXPORT [
			size 16
			fields [
				EXTERNAL_NAME_STRING 0 4
				SYMBOL 4 4
				ORDINAL 8 4
				FLAGS 12 4
			]
		]

		RSIR_FUNCTION [
			size 40
			fields [
				SYMBOL 0 4
				SIGNATURE 4 4
				FLAGS 8 4
				FIRST_BLOCK 12 4
				BLOCK_COUNT 16 4
				ENTRY_BLOCK 20 4
				FIRST_LOCAL 24 4
				LOCAL_COUNT 28 4
				SOURCE_LOCATION 32 4
				RESERVED 36 4
			]
		]

		RSIR_LOCAL [
			size 32
			fields [
				FUNCTION 0 4
				NAME_STRING 4 4
				TYPE 8 4
				KIND 12 4
				FLAGS 16 4
				ALIGNMENT 20 4
				SOURCE_LOCATION 24 4
				ORDINAL 28 4
			]
		]

		RSIR_BLOCK [
			size 32
			fields [
				FUNCTION 0 4
				FLAGS 4 4
				FIRST_INSTRUCTION 8 4
				INSTRUCTION_COUNT 12 4
				FIRST_OUTGOING_EDGE 16 4
				OUTGOING_EDGE_COUNT 20 4
				SOURCE_LOCATION 24 4
				RESERVED 28 4
			]
		]

		RSIR_EDGE [
			size 24
			fields [
				SOURCE_BLOCK 0 4
				TARGET_BLOCK 4 4
				KIND 8 4
				SELECTOR_CONSTANT 12 4
				ORDINAL 16 4
				FLAGS 20 4
			]
		]

		RSIR_VALUE [
			size 24
			fields [
				DEFINITION_KIND 0 4
				DEFINITION_ID 4 4
				RESULT_ORDINAL 8 4
				TYPE 12 4
				FUNCTION 16 4
				FLAGS 20 4
			]
		]

		RSIR_INSTRUCTION [
			size 48
			fields [
				BLOCK 0 4
				OPCODE 4 4
				SUBOPCODE 8 4
				FLAGS 12 4
				FIRST_RESULT 16 4
				RESULT_COUNT 20 4
				FIRST_OPERAND 24 4
				OPERAND_COUNT 28 4
				EFFECT_FLAGS 32 4
				ALIAS_KIND 36 4
				ALIAS_ID 40 4
				SOURCE_LOCATION 44 4
			]
		]

		RSIR_OPERAND [
			size 16
			fields [
				KIND 0 4
				REFERENCE 4 4
				AUXILIARY 8 4
				FLAGS 12 4
			]
		]

		RSIR_CALL [
			size 32
			fields [
				INSTRUCTION 0 4
				SIGNATURE 4 4
				CALLEE_KIND 8 4
				CALLEE_REFERENCE 12 4
				FLAGS 16 4
				FIRST_ARGUMENT_OPERAND 20 4
				ARGUMENT_COUNT 24 4
				RESERVED 28 4
			]
		]

		RSIR_TARGET_FRAGMENT [
			size 32
			fields [
				TARGET 0 4
				ABI 4 4
				DATA_OFFSET 8 4
				DATA_SIZE 12 4
				RETURN_TYPE 16 4
				EFFECT_FLAGS 20 4
				CLOBBER_CLASS 24 4
				SOURCE_LOCATION 28 4
			]
		]

		SOURCE_LOCATION [
			size 16
			fields [
				FILE 0 4
				LINE 4 4
				COLUMN 8 4
				BYTE_OFFSET 12 4
			]
		]

		RSIR_EXCEPTION_REGION [
			size 24
			fields [
				FUNCTION 0 4
				FIRST_BLOCK_MEMBER 4 4
				BLOCK_MEMBER_COUNT 8 4
				HANDLER_BLOCK 12 4
				KIND 16 4
				FLAGS 20 4
			]
		]

		RSIR_EXCEPTION_BLOCK [
			size 8
			fields [
				REGION 0 4
				BLOCK 4 4
			]
		]

		RSCG_OUTPUT_SECTION [
			size 32
			fields [
				NAME_STRING 0 4
				CLASS 4 4
				FLAGS 8 4
				ALIGNMENT 12 4
				DATA_OFFSET 16 4
				FILE_SIZE 20 4
				MEMORY_SIZE 24 4
				RESERVED 28 4
			]
		]

		RSCG_SYMBOL [
			size 40
			fields [
				NAME_STRING 0 4
				KIND 4 4
				BINDING 8 4
				VISIBILITY 12 4
				OUTPUT_SECTION 16 4
				SECTION_OFFSET 20 4
				SIZE 24 4
				ALIGNMENT 28 4
				FLAGS 32 4
				ORIGIN_MODULE 36 4
			]
		]

		RSCG_RELOCATION [
			size 32
			fields [
				SOURCE_SECTION 0 4
				SOURCE_OFFSET 4 4
				KIND 8 4
				TARGET_SYMBOL 12 4
				RAW_ADDEND_LOW 16 4
				RAW_ADDEND_HIGH 20 4
				ENCODED_WIDTH 24 4
				FLAGS 28 4
			]
		]

		RSCG_FUNCTION [
			size 40
			fields [
				SYMBOL 0 4
				CODE_SECTION 4 4
				CODE_OFFSET 8 4
				CODE_SIZE 12 4
				FRAME_SIZE 16 4
				FLAGS 20 4
				FIRST_DEBUG_LINE 24 4
				DEBUG_LINE_COUNT 28 4
				FIRST_DEBUG_PARAMETER 32 4
				DEBUG_PARAMETER_COUNT 36 4
			]
		]

		RSCG_DEBUG_LINE [
			size 20
			fields [
				FUNCTION 0 4
				CODE_OFFSET 4 4
				FILE 8 4
				LINE 12 4
				COLUMN 16 4
			]
		]

		RSCG_DEBUG_PARAMETER [
			size 16
			fields [
				FUNCTION 0 4
				ORDINAL 4 4
				DEBUG_TYPE_CODE 8 4
				FLAGS 12 4
			]
		]

		RSCG_GC_FRAME [
			size 24
			fields [
				FUNCTION 0 4
				BITMAP_SECTION 4 4
				BITMAP_OFFSET 8 4
				BITMAP_SIZE 12 4
				FLAGS 16 4
				RESERVED 20 4
			]
		]

		RSCG_UNWIND_FUNCTION [
			size 24
			fields [
				FUNCTION 0 4
				CODE_OFFSET 4 4
				CODE_SIZE 8 4
				UNWIND_CODE_OFFSET 12 4
				UNWIND_CODE_SIZE 16 4
				FLAGS 20 4
			]
		]
	]
]
