name: Linux-ARMel

on: push

jobs:
  Build-ARMel-Tests:
    runs-on: windows-latest
    name: Build RPi Tests
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Download Rebol
      run: |
        $url = "http://static.red-lang.org/build/rebview.exe"
        $output = "$Env:GITHUB_WORKSPACE\rebview.exe"
        (New-Object System.Net.WebClient).DownloadFile($url, $output)

    - name: Build Tests
      run: rebview.exe -qws tests/build-arm-tests.r -t Linux-ARM
      shell: cmd

    - uses: actions/upload-artifact@v2
      with:
        name: rpi-tests-bin
        path: quick-test/runnable/arm-tests/red
        retention-days: 3

  ARMel-Unittest:

    runs-on: ubuntu-latest
    needs: Build-ARMel-Tests
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Retrieve tests
      uses: actions/download-artifact@v2
      with:
        name: armel-tests-bin
        path: quick-test/runnable/arm-tests/red

    - name: Chmod files
      run: |
        chmod +x quick-test/runnable/arm-tests/red/*

    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
      with:
        platforms: arm

    - name: Run Tests
      uses: ./CI/ARMel
      with:
        command: cd quick-test/runnable/arm-tests/red && ./run-all.sh

    # upload log file if any test failed
    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: ARMel-Tests-log
        path: ${{ github.workspace }}/quick-test/quick-test.log
