name: Linux-ARMhf

on: push

jobs:
  Run-ARMhf-Tests:

    runs-on: ubuntu-latest
   
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: pguyot/arm-runner-action@HEAD
      with:
        optimize_image: no
        exit_on_fail: no
        copy_artifact_path: quick-test/runnable/arm-tests/red/quick-test.log
        cpu: cortex-a8
        commands: |
          uname -m
          apt-get update -y
          apt-get install --no-install-recommends -y libgdk-pixbuf2.0-0
          cd quick-test/runnable/arm-tests/red
          chmod +x ./run-all.sh
          ./run-all.sh

    # upload log file if any test failed
    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: ARMhf-Tests-log
        path: quick-test.log
