name: Windows

on: [push]

jobs:
  Core:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: setup red repo
      run: |
        $url = "http://static.red-lang.org/build/rebview.exe"
        $output = "$Env:GITHUB_WORKSPACE\rebview.exe"
        (New-Object System.Net.WebClient).DownloadFile($url, $output)
    - name: run view test
      run: |
        rebview.exe -qws tests\run-core-tests.r --batch
        rebview.exe -qws system\tests\run-all.r --batch
      shell: cmd

    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: core-test-log
        path: quick-test/quick-test.log

  View:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: setup red repo
      run: |
        $url = "http://static.red-lang.org/build/rebview.exe"
        $output = "$Env:GITHUB_WORKSPACE\rebview.exe"
        (New-Object System.Net.WebClient).DownloadFile($url, $output)
    - name: run view test
      run: rebview.exe -qws tests\run-view-tests.r --batch
      shell: cmd

    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: view-test-log
        path: quick-test/quick-test.log

  Regression:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: setup red repo
      run: |
        $url = "http://static.red-lang.org/build/rebview.exe"
        $output = "$Env:GITHUB_WORKSPACE\rebview.exe"
        (New-Object System.Net.WebClient).DownloadFile($url, $output)
    - name: run regression test
      run: rebview.exe -qws tests\run-regression-tests.r --batch
      shell: cmd

    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: regression-test-log
        path: quick-test/quick-test.log

  Each-Mode:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: setup red repo
      run: |
        $url = "http://static.red-lang.org/build/rebview.exe"
        $output = "$Env:GITHUB_WORKSPACE\rebview.exe"
        (New-Object System.Net.WebClient).DownloadFile($url, $output)
    - name: run view test
      run: |
        rebview.exe -qws tests\run-all.r --each
        rebview.exe -qws system\tests\run-all.r --each
      shell: cmd

    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: each-test-log
        path: quick-test/quick-test.log
