name: Windows

on: [push, pull_request]

jobs:
  Core-Debug:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: setup red repo
      run: |
        $url = "http://static.red-lang.org/build/rebview.exe"
        $output = "$Env:GITHUB_WORKSPACE\rebview.exe"
        (New-Object System.Net.WebClient).DownloadFile($url, $output)
    - name: run core test
      run: rebview.exe -qws tests\run-core-tests.r --batch --debug
      shell: cmd

    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: core-debug-test-log
        path: quick-test/quick-test.log

  Each-Mode-Debug:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: setup red repo
      run: |
        $url = "http://static.red-lang.org/build/rebview.exe"
        $output = "$Env:GITHUB_WORKSPACE\rebview.exe"
        (New-Object System.Net.WebClient).DownloadFile($url, $output)
    - name: run each test
      run: rebview.exe -qws tests\run-core-tests.r --ci-each --debug
      shell: cmd

    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: each-debug-test-log
        path: quick-test/quick-test.log