name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: setup red repo
      run: |
        $url = "http://static.red-lang.org/build/rebview.exe"
        $output = "$Env:GITHUB_WORKSPACE\rebview.exe"
        (New-Object System.Net.WebClient).DownloadFile($url, $output)
    - name: run view test
      run: rebview.exe -qws tests\run-view-tests.r --batch
      shell: cmd

    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: quick-test.log
        path: quick-test/quick-test.log

  Regression:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: setup red repo
      run: |
        sudo apt-get install libcurl3:i386
        sudo curl -o /bin/rebol https://static.red-lang.org/tmp/rebol
        sudo chmod +x /bin/rebol
        rebol -qws tests/run-all.r --batch