name: Windows

on: [push, pull_request]

jobs:
  Core-Release:

    runs-on: windows-latest
   
    steps:
    - uses: actions/checkout@v4
    - name: setup red repo
      run: |
        $url = "http://static.red-lang.org/build/rebview.exe"
        $output = "$Env:GITHUB_WORKSPACE\rebview.exe"
        (New-Object System.Net.WebClient).DownloadFile($url, $output)
    - name: run core test
      run: rebview.exe -qws tests\run-core-tests.r --batch --release
      shell: cmd

    - uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: core-test-release-log
        path: quick-test/quick-test.log