name: RPi

on: push

jobs:
  Build-RPi-Tests:
    runs-on: ubuntu-latest
    name: Build RPi Tests
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build Red/System Tests
      uses: ./CI/Linux-32
      with:
        command: rebol -qws system/tests/build-arm-tests.r -t RPi

    - uses: actions/upload-artifact@v4
      with:
        name: rpi-rs-bin
        path: quick-test/runnable/arm-tests/system
        retention-days: 3

  Run-RS-tests-ubuntux:
    runs-on: ubuntu-24.04-arm
    needs: Build-RPi-Tests

    steps:
    - name: Install 32bit libs
      run: |
        sudo dpkg --add-architecture armhf
        sudo apt update
        sudo apt install libc6:armhf libgdk-pixbuf-2.0-0:armhf libssl3t64:armhf
        sudo ln -s /lib/arm-linux-gnueabihf/libcrypto.so.3 /lib/arm-linux-gnueabihf/libcrypto.so.1.1

    - name: Retrieve tests
      uses: actions/download-artifact@v4
      with:
        name: rpi-rs-bin

    - name: Run tests
      run: |
        export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/.
        chmod +x run-all.sh
        ./run-all.sh

    # upload log file if any test failed
    - uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: RS-Tests-Armbian-log
        path: quick-test.log