name: Send Message to Telegram

on: watch

jobs:
  Notify:
    runs-on: ubuntu-latest
    steps:
    - name: send message
      env:
        TG_CHAT_ID: ${{ secrets.TelegramChatId }}
        TG_BOT_TOKEN: ${{ secrets.TelegramBotToken }}
      run: |
        curl -k --data chat_id="$TG_CHAT_ID" "https://api.telegram.org/bot/sendMessage" \
        --data-raw 'text=${{github.actor}} starred red/red'